//! `cargo jackioh spec check` and `cargo jackioh spec index`: the spec graph's structural checks
//! (SURFACE §15, part 28). They replace `packages/engine/test/rulings.test.ts`'s index and
//! `packages/engine/scripts/rulings-coverage.ts`.
//!
//! `spec/` is the specification as notes: one per section (`spec/NN-<slug>.md`, its `## N.` and
//! `### N.M` headings the section ids) and one per ruling (`spec/rulings/R<nnnn>.md`), whose front
//! matter is
//!
//! ```text
//! ---
//! id: R195
//! title: When a card glows yellow (`conditionActive`)
//! cards: "§10.8, §10.9, #10, …"
//! proven_in:
//!   - crates/engine/tests/rules/condition_active.rs
//! ---
//! ```
//!
//! `check` holds four rules:
//!
//! 1. every ruling note's `id` matches its file name (`R195` is `R0195.md`), and ids are unique;
//! 2. every note lists at least one `proven_in` path, and each exists and holds a proof of the id: a
//!    Rust `fn` or `mod` whose name has the `_`-delimited token `r<n>`, a TypeScript `it(`, `test(`
//!    or `describe(` whose title has `R<n>` as a word, or an SQL evidence script's
//!    `\echo '### R<n>: … ###'` heading (the heading form `rulings.test.ts` credited; a mention in
//!    prose is not a proof);
//! 3. every `r<n>` token of a Rust `fn` or `mod` name, and every `R<n>` cited in `crates/`,
//!    `apps/web/src/` and `e2e/` (comments included, recursively), has a note;
//! 4. every `[[…]]` link in `spec/` resolves: `[[R113]]` to a ruling note, `[[§10.3]]` to a section
//!    heading, anything else to a note's file name. Links inside code are not links.
//!
//! It reads ids, file names, headings and test names, never the wording (#133): a reworded sentence
//! fails nothing. `index` rewrites `spec/INDEX.md` from the ruling notes: id, title, note and the
//! files that prove it, one line each.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::patches::repo_root;

/// `jackioh spec check | index`.
#[derive(clap::Args)]
pub struct Args {
    /// The repository root (default: the workspace this binary was built from, as every other
    /// command reads it).
    #[arg(long)]
    pub root: Option<PathBuf>,
    #[command(subcommand)]
    pub command: SpecCommand,
}

#[derive(clap::Subcommand)]
pub enum SpecCommand {
    /// The four structural checks (SURFACE §15): ids and file names, proofs, citations, links.
    Check,
    /// Rewrite `spec/INDEX.md` from the ruling notes.
    Index,
}

pub fn run(args: Args) -> Result<()> {
    let root = args.root.unwrap_or_else(repo_root);
    match args.command {
        SpecCommand::Check => check(&root),
        SpecCommand::Index => index(&root),
    }
}

/// The directories `check`'s third rule reads, recursively.
const CITING_ROOTS: &[&str] = &["crates", "apps/web/src", "e2e"];

/// Directories never read: build output, dependencies, test artefacts and generated packages.
const SKIPPED_DIRS: &[&str] = &[
    ".git",
    "target",
    "node_modules",
    "dist",
    "coverage",
    "artifacts",
    "pkg",
    "screenshots",
    "videos",
    "downloads",
];

/// The files whose text counts as code for the third rule. Data (JSON, golden traces) and prose
/// (Markdown) do not cite rulings.
const CODE_EXTENSIONS: &[&str] = &[
    "rs", "sql", "toml", "ts", "tsx", "mts", "cts", "js", "jsx", "mjs", "cjs", "css", "html",
];

/// The file extensions a TypeScript proof may have.
const TS_EXTENSIONS: &[&str] = &["ts", "tsx", "mts", "cts", "js", "jsx", "mjs", "cjs"];

const INDEX_HEADER: &str = "# Rulings index\n\nGenerated by `cargo jackioh spec index` from the notes in `rulings/`: edit a note, never this file, then run the command again.\n\n| id | title | note | proven in |\n| --- | --- | --- | --- |\n";

/* ------------------------------------------------------------------------------------- notes */

/// One ruling note, as its front matter states it.
#[derive(Debug, Clone, PartialEq, Eq)]
struct RulingNote {
    /// The path relative to the root, `spec/rulings/R0195.md`.
    path: String,
    /// The file name without `.md`, `R0195`.
    stem: String,
    id: Option<String>,
    title: Option<String>,
    proven_in: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum Field {
    Scalar(String),
    List(Vec<String>),
}

/// The front matter of a note: the `---` block it starts with, as `key: value` scalars and
/// `key:` lists of `  - item` lines (or `key: []`). Quoted scalars are unquoted.
fn front_matter(text: &str) -> Result<Vec<(String, Field)>, String> {
    let mut lines = text.lines().map(|line| line.trim_end_matches('\r'));
    if lines.next() != Some("---") {
        return Err("no front matter: the note must start with a `---` line".to_string());
    }
    let mut fields: Vec<(String, Field)> = Vec::new();
    let mut closed = false;
    for line in lines {
        if line == "---" {
            closed = true;
            break;
        }
        if line.trim().is_empty() {
            continue;
        }
        let trimmed = line.trim_start();
        if let Some(item) = trimmed.strip_prefix("- ") {
            match fields.last_mut() {
                Some((_, Field::List(items))) => items.push(unquote(item.trim())),
                _ => return Err(format!("a list item outside a list: `{line}`")),
            }
            continue;
        }
        let Some((key, value)) = line.split_once(':') else {
            return Err(format!("not a `key: value` line: `{line}`"));
        };
        let key = key.trim().to_string();
        let value = value.trim();
        let field = if value.is_empty() {
            Field::List(Vec::new())
        } else if let Some(inner) = value.strip_prefix('[').and_then(|rest| rest.strip_suffix(']')) {
            Field::List(
                inner
                    .split(',')
                    .map(str::trim)
                    .filter(|item| !item.is_empty())
                    .map(unquote)
                    .collect(),
            )
        } else {
            Field::Scalar(unquote(value))
        };
        fields.push((key, field));
    }
    if !closed {
        return Err("the front matter has no closing `---` line".to_string());
    }
    Ok(fields)
}

/// A YAML scalar as written: `"…"` with backslash escapes, `'…'` with `''`, or plain.
fn unquote(value: &str) -> String {
    if value.len() < 2 {
        return value.to_string();
    }
    if let Some(inner) = value.strip_prefix('"').and_then(|rest| rest.strip_suffix('"')) {
        let mut out = String::with_capacity(inner.len());
        let mut chars = inner.chars();
        while let Some(c) = chars.next() {
            if c == '\\' {
                match chars.next() {
                    Some('n') => out.push('\n'),
                    Some('t') => out.push('\t'),
                    Some(other) => out.push(other),
                    None => out.push('\\'),
                }
            } else {
                out.push(c);
            }
        }
        return out;
    }
    if let Some(inner) = value.strip_prefix('\'').and_then(|rest| rest.strip_suffix('\'')) {
        return inner.replace("''", "'");
    }
    value.to_string()
}

fn parse_note(path: String, stem: String, text: &str) -> Result<RulingNote, String> {
    let fields = front_matter(text)?;
    let mut note = RulingNote {
        path,
        stem,
        id: None,
        title: None,
        proven_in: Vec::new(),
    };
    for (key, field) in fields {
        match (key.as_str(), field) {
            ("id", Field::Scalar(value)) => note.id = Some(value),
            ("title", Field::Scalar(value)) => note.title = Some(value),
            ("proven_in", Field::List(items)) => note.proven_in = items,
            ("proven_in", Field::Scalar(value)) => note.proven_in = vec![value],
            _ => {}
        }
    }
    Ok(note)
}

/// Every ruling note under `spec/rulings/`, in file-name order.
fn read_notes(root: &Path) -> Result<Vec<RulingNote>> {
    let dir = root.join("spec").join("rulings");
    let mut files: Vec<PathBuf> = fs::read_dir(&dir)
        .with_context(|| format!("reading {}", dir.display()))?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == "md"))
        .collect();
    files.sort();
    let mut notes = Vec::with_capacity(files.len());
    for file in files {
        let text = fs::read_to_string(&file).with_context(|| format!("reading {}", file.display()))?;
        let stem = file
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_default();
        let path = relative(root, &file);
        let note =
            parse_note(path.clone(), stem, &text).map_err(|error| anyhow::anyhow!("{path}: {error}"))?;
        notes.push(note);
    }
    Ok(notes)
}

/// `R195` → 195.
fn ruling_number(id: &str) -> Option<u64> {
    let digits = id.strip_prefix('R')?;
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    digits.parse().ok()
}

/// The file name a ruling's note must have, without `.md`: four digits, zero-padded.
fn note_stem(number: u64) -> String {
    format!("R{number:04}")
}

/* ------------------------------------------------------------------------------- the scanners */

fn is_word_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

pub(crate) fn is_ident_char(c: char) -> bool {
    c.is_alphanumeric() || c == '_'
}

/// Every `R<n>` cited as a word in a text, with its byte offset: `R113`, `(R113)`, `R113's`, not
/// `XR113` or `R113a`.
fn citations(text: &str) -> Vec<(usize, u64)> {
    let bytes = text.as_bytes();
    let mut found = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'R' && (i == 0 || !is_word_byte(bytes[i - 1])) {
            let start = i + 1;
            let mut end = start;
            while end < bytes.len() && bytes[end].is_ascii_digit() {
                end += 1;
            }
            if end > start && (end == bytes.len() || !is_word_byte(bytes[end])) {
                if let Ok(number) = text[start..end].parse::<u64>() {
                    found.push((i, number));
                }
                i = end;
                continue;
            }
        }
        i += 1;
    }
    found
}

/// Rust source with its comments, string literals and char literals blanked out, so a name in a
/// comment or a string is not a test. Line breaks are kept, so line numbers still hold.
fn rust_code_only(src: &str) -> String {
    let chars: Vec<char> = src.chars().collect();
    let mut out = String::with_capacity(src.len());
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        let next = chars.get(i + 1).copied();
        let end = if c == '/' && next == Some('/') {
            let mut j = i;
            while j < chars.len() && chars[j] != '\n' {
                j += 1;
            }
            j
        } else if c == '/' && next == Some('*') {
            block_comment_end(&chars, i)
        } else if c == '"' || (c == 'r' && raw_string_start(&chars, i)) {
            string_end(&chars, i)
        } else if c == '\'' {
            // A char literal ('x', '\n', '"') is blanked; a lifetime ('a) is one quote.
            char_literal_end(&chars, i).unwrap_or(i + 1)
        } else {
            out.push(c);
            i += 1;
            continue;
        };
        // What was skipped reads as one space, plus the line breaks it held.
        out.push(' ');
        out.extend(chars[i..end].iter().filter(|c| **c == '\n'));
        i = end.max(i + 1);
    }
    out
}

/// The index just past the (possibly nested) block comment that starts at `i`.
fn block_comment_end(chars: &[char], i: usize) -> usize {
    let mut depth = 0usize;
    let mut j = i;
    while j < chars.len() {
        if chars[j] == '/' && chars.get(j + 1) == Some(&'*') {
            depth += 1;
            j += 2;
        } else if chars[j] == '*' && chars.get(j + 1) == Some(&'/') {
            depth = depth.saturating_sub(1);
            j += 2;
            if depth == 0 {
                return j;
            }
        } else {
            j += 1;
        }
    }
    chars.len()
}

/// Whether `r` at `i` opens a raw string (`r"…"`, `r#"…"#`, `br"…"`) rather than being part of an
/// identifier.
fn raw_string_start(chars: &[char], i: usize) -> bool {
    if i > 0 {
        let before = chars[i - 1];
        let byte_prefix = before == 'b' && (i < 2 || !is_ident_char(chars[i - 2]));
        if is_ident_char(before) && !byte_prefix {
            return false;
        }
    }
    let mut j = i + 1;
    while j < chars.len() && chars[j] == '#' {
        j += 1;
    }
    j < chars.len() && chars[j] == '"'
}

/// The index just past the string literal that starts at `i` (`"…"` or a raw string).
fn string_end(chars: &[char], i: usize) -> usize {
    if chars[i] == '"' {
        let mut j = i + 1;
        while j < chars.len() {
            match chars[j] {
                '\\' => j += 2,
                '"' => return j + 1,
                _ => j += 1,
            }
        }
        return chars.len();
    }
    let mut j = i + 1;
    let mut hashes = 0;
    while j < chars.len() && chars[j] == '#' {
        hashes += 1;
        j += 1;
    }
    j += 1; // the opening quote
    while j < chars.len() {
        if chars[j] == '"' && (0..hashes).all(|k| chars.get(j + 1 + k) == Some(&'#')) {
            return j + 1 + hashes;
        }
        j += 1;
    }
    chars.len()
}

/// The index just past a char literal starting at `i`, or `None` for a lifetime.
fn char_literal_end(chars: &[char], i: usize) -> Option<usize> {
    match chars.get(i + 1) {
        // '\n', '\'', '\\', '\u{1F600}': the escape's first character is never the closing quote.
        Some('\\') => (i + 3..chars.len().min(i + 14))
            .find(|j| chars[*j] == '\'')
            .map(|j| j + 1),
        Some(_) if chars.get(i + 2) == Some(&'\'') => Some(i + 3),
        _ => None,
    }
}

/// The name of every `fn` and `mod` in Rust source (comments and strings excluded), with its line.
fn rust_item_names(src: &str) -> Vec<(usize, String)> {
    let code = rust_code_only(src);
    let mut names = Vec::new();
    let mut previous: Option<String> = None;
    let mut line = 1;
    let mut word = String::new();
    for c in code.chars().chain(std::iter::once(' ')) {
        if is_ident_char(c) {
            word.push(c);
            continue;
        }
        if !word.is_empty() {
            if matches!(previous.as_deref(), Some("fn" | "mod")) {
                names.push((line, word.clone()));
            }
            previous = Some(std::mem::take(&mut word));
        }
        if !c.is_whitespace() {
            previous = None;
        }
        if c == '\n' {
            line += 1;
        }
    }
    names
}

/// The ruling numbers a Rust item name carries as `_`-delimited `r<n>` tokens: `r90_r81_x` → 90, 81.
fn name_tokens(name: &str) -> Vec<u64> {
    name.split('_')
        .filter_map(|token| {
            let digits = token.strip_prefix('r')?;
            if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
                return None;
            }
            digits.parse().ok()
        })
        .collect()
}

/// The title of every `it(…)`, `test(…)` and `describe(…)` in TypeScript source (`.only`, `.skip`
/// and the like allowed between the name and the parenthesis), as written between its quotes.
fn ts_test_titles(src: &str) -> Vec<String> {
    let bytes = src.as_bytes();
    let mut titles = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        let rest = &bytes[i..];
        let name_len = ["describe", "test", "it"]
            .iter()
            .find(|name| rest.starts_with(name.as_bytes()))
            .map(|name| name.len());
        let Some(len) = name_len else {
            i += 1;
            continue;
        };
        if i > 0 && is_word_byte(bytes[i - 1]) {
            i += 1;
            continue;
        }
        let mut j = i + len;
        if j < bytes.len() && is_word_byte(bytes[j]) {
            i += 1;
            continue;
        }
        // `.only`, `.skip`, `.concurrent`, …
        while j < bytes.len() && bytes[j] == b'.' {
            let mut k = j + 1;
            while k < bytes.len() && is_word_byte(bytes[k]) {
                k += 1;
            }
            if k == j + 1 {
                break;
            }
            j = k;
        }
        if j >= bytes.len() || bytes[j] != b'(' {
            i += 1;
            continue;
        }
        j += 1;
        while j < bytes.len() && bytes[j].is_ascii_whitespace() {
            j += 1;
        }
        if j >= bytes.len() || !matches!(bytes[j], b'"' | b'\'' | b'`') {
            i = j;
            continue;
        }
        let quote = bytes[j];
        let start = j + 1;
        let mut k = start;
        while k < bytes.len() && bytes[k] != quote {
            if bytes[k] == b'\\' {
                k += 1;
            }
            k += 1;
        }
        let end = k.min(bytes.len());
        titles.push(src[start..end].to_string());
        i = end + 1;
    }
    titles
}

/// The headings an SQL evidence script announces its checks with: `\echo '### … ###'` or
/// `\echo '=== … ==='`, as the text between the delimiters. Prose between checks is not read.
fn sql_headings(src: &str) -> Vec<String> {
    let mut headings = Vec::new();
    let mut rest = src;
    while let Some(at) = rest.find("\\echo") {
        rest = &rest[at + "\\echo".len()..];
        let after = rest.trim_start();
        let Some(quoted) = after.strip_prefix('\'') else {
            continue;
        };
        let quoted = quoted.trim_start();
        let Some(body) = quoted.strip_prefix("###").or_else(|| quoted.strip_prefix("===")) else {
            continue;
        };
        let Some(close) = body.find('\'') else { continue };
        let heading = body[..close].trim();
        let heading = heading
            .strip_suffix("###")
            .or_else(|| heading.strip_suffix("==="))
            .unwrap_or(heading);
        headings.push(heading.trim().to_string());
    }
    headings
}

/// Whether an SQL heading names ruling `number` where a name goes: `R104: …` or `(R105): …`.
fn sql_heading_names(heading: &str, number: u64) -> bool {
    citations(heading).into_iter().any(|(at, cited)| {
        if cited != number {
            return false;
        }
        let digits = heading[at + 1..].bytes().take_while(u8::is_ascii_digit).count();
        let after = heading[at + 1 + digits..].trim_start();
        after.starts_with(':') || after.starts_with(')')
    })
}

/// Whether a file holds a proof of ruling `number`, in its own idiom for a test name.
fn proves(path: &str, src: &str, number: u64) -> Result<bool, String> {
    let extension = Path::new(path)
        .extension()
        .map(|ext| ext.to_string_lossy().into_owned())
        .unwrap_or_default();
    if extension == "rs" {
        return Ok(rust_item_names(src)
            .iter()
            .any(|(_, name)| name_tokens(name).contains(&number)));
    }
    if extension == "sql" {
        return Ok(sql_headings(src)
            .iter()
            .any(|heading| sql_heading_names(heading, number)));
    }
    if TS_EXTENSIONS.contains(&extension.as_str()) {
        return Ok(ts_test_titles(src)
            .iter()
            .any(|title| citations(title).iter().any(|(_, cited)| *cited == number)));
    }
    Err("is not a Rust, TypeScript or SQL test file".to_string())
}

/* --------------------------------------------------------------------------------- the walk */

fn relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

/// Every file under `dir`, recursively and in name order, skipping SKIPPED_DIRS.
fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    let mut paths: Vec<PathBuf> = entries
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .collect();
    paths.sort();
    for path in paths {
        let name = path
            .file_name()
            .map(|name| name.to_string_lossy().into_owned())
            .unwrap_or_default();
        if path.is_dir() {
            if !SKIPPED_DIRS.contains(&name.as_str()) {
                walk(&path, out);
            }
        } else {
            out.push(path);
        }
    }
}

fn line_of(text: &str, offset: usize) -> usize {
    text[..offset].bytes().filter(|b| *b == b'\n').count() + 1
}

/* ------------------------------------------------------------------------------- the links */

/// Every `[[…]]` link outside code in a Markdown note, with its line number and its target (the
/// part before any `|alias` or `#heading`).
fn wiki_links(text: &str) -> Vec<(usize, String, String)> {
    let mut links = Vec::new();
    let mut fenced = false;
    for (index, line) in text.lines().enumerate() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            fenced = !fenced;
            continue;
        }
        if fenced {
            continue;
        }
        let prose = without_code_spans(line);
        let mut rest = prose.as_str();
        while let Some(open) = rest.find("[[") {
            let after = &rest[open + 2..];
            let Some(close) = after.find("]]") else { break };
            let inner = &after[..close];
            let target = inner
                .split('|')
                .next()
                .unwrap_or("")
                .split('#')
                .next()
                .unwrap_or("")
                .trim();
            links.push((index + 1, inner.to_string(), target.to_string()));
            rest = &after[close + 2..];
        }
    }
    links
}

/// A line with its inline code spans (`…`) removed.
fn without_code_spans(line: &str) -> String {
    let mut out = String::with_capacity(line.len());
    let mut rest = line;
    while let Some(open) = rest.find('`') {
        out.push_str(&rest[..open]);
        let ticks = rest[open..].bytes().take_while(|b| *b == b'`').count();
        let fence = &rest[open..open + ticks];
        let after = &rest[open + ticks..];
        match after.find(fence) {
            Some(close) => rest = &after[close + ticks..],
            None => {
                out.push_str(&rest[open..]);
                return out;
            }
        }
    }
    out.push_str(rest);
    out
}

/// The section ids a note's headings define: `## 10.` is `10`, `### 10.3 …` is `10.3`.
fn section_ids(text: &str) -> Vec<String> {
    let mut ids = Vec::new();
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("### ") {
            let id: String = rest
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '.')
                .collect();
            let id = id.trim_end_matches('.');
            if !id.is_empty() && rest[id.len()..].starts_with([' ', '.']) {
                ids.push(id.to_string());
            }
        } else if let Some(rest) = line.strip_prefix("## ") {
            let id: String = rest.chars().take_while(char::is_ascii_digit).collect();
            if !id.is_empty() && rest[id.len()..].starts_with('.') {
                ids.push(id);
            }
        }
    }
    ids
}

/* ------------------------------------------------------------------------------- the checks */

fn check(root: &Path) -> Result<()> {
    let notes = read_notes(root)?;
    let mut problems: Vec<String> = Vec::new();

    // 1. Every note's id matches its file name, and ids are unique.
    let mut ids: BTreeMap<u64, String> = BTreeMap::new();
    for note in &notes {
        let Some(id) = note.id.as_deref() else {
            problems.push(format!("{}: no `id` in the front matter", note.path));
            continue;
        };
        let Some(number) = ruling_number(id) else {
            problems.push(format!("{}: `id: {id}` is not a ruling id (R<n>)", note.path));
            continue;
        };
        if note.stem != note_stem(number) {
            problems.push(format!(
                "{}: `id: {id}` belongs in {}.md",
                note.path,
                note_stem(number)
            ));
        }
        if let Some(other) = ids.get(&number) {
            problems.push(format!("{}: R{number} is also the id of {other}", note.path));
        } else {
            ids.insert(number, note.path.clone());
        }
    }

    // 2. Every note is proved, and every proof path exists and names the ruling.
    let mut proofs = 0usize;
    let mut sources: BTreeMap<String, Option<String>> = BTreeMap::new();
    for note in &notes {
        let Some(number) = note.id.as_deref().and_then(ruling_number) else {
            continue;
        };
        if note.proven_in.is_empty() {
            problems.push(format!("{}: R{number} lists no `proven_in` file", note.path));
        }
        for proof in &note.proven_in {
            let src = sources
                .entry(proof.clone())
                .or_insert_with(|| fs::read_to_string(root.join(proof)).ok());
            let Some(src) = src.as_deref() else {
                problems.push(format!("{}: `proven_in` {proof} does not exist", note.path));
                continue;
            };
            match proves(proof, src, number) {
                Ok(true) => proofs += 1,
                Ok(false) => problems.push(format!(
                    "{}: `proven_in` {proof} has no test named after R{number} (a fn or mod with the token r{number}, an it/describe title with R{number}, or an SQL `### R{number}: …` heading)",
                    note.path
                )),
                Err(why) => problems.push(format!("{}: `proven_in` {proof} {why}", note.path)),
            }
        }
    }

    // 3. Every r<n> test token and every R<n> cited in code has a note.
    let mut files = Vec::new();
    for dir in CITING_ROOTS {
        walk(&root.join(dir), &mut files);
    }
    let mut cited = 0usize;
    let mut citing_files = 0usize;
    for file in &files {
        let extension = file
            .extension()
            .map(|ext| ext.to_string_lossy().into_owned())
            .unwrap_or_default();
        if !CODE_EXTENSIONS.contains(&extension.as_str()) {
            continue;
        }
        let Ok(text) = fs::read_to_string(file) else {
            continue;
        };
        let path = relative(root, file);
        let found = citations(&text);
        if !found.is_empty() {
            citing_files += 1;
        }
        for (offset, number) in found {
            cited += 1;
            if !ids.contains_key(&number) {
                problems.push(format!(
                    "{path}:{}: R{number} has no note in spec/rulings/",
                    line_of(&text, offset)
                ));
            }
        }
        if extension == "rs" {
            for (line, name) in rust_item_names(&text) {
                for number in name_tokens(&name) {
                    if !ids.contains_key(&number) {
                        problems.push(format!(
                            "{path}:{line}: `{name}` names r{number}, which has no note in spec/rulings/"
                        ));
                    }
                }
            }
        }
    }

    // 4. Every [[…]] link in spec/ resolves to a note or a section.
    let mut spec_files = Vec::new();
    walk(&root.join("spec"), &mut spec_files);
    spec_files.retain(|path| path.extension().is_some_and(|ext| ext == "md"));
    let mut texts: Vec<(String, String)> = Vec::new();
    let mut sections: BTreeSet<String> = BTreeSet::new();
    let mut stems: BTreeSet<String> = BTreeSet::new();
    for file in &spec_files {
        let text = fs::read_to_string(file).with_context(|| format!("reading {}", file.display()))?;
        sections.extend(section_ids(&text));
        if let Some(stem) = file.file_stem() {
            stems.insert(stem.to_string_lossy().into_owned());
        }
        texts.push((relative(root, file), text));
    }
    let mut links = 0usize;
    for (path, text) in &texts {
        for (line, inner, target) in wiki_links(text) {
            links += 1;
            let resolves = if let Some(number) = ruling_number(&target) {
                ids.contains_key(&number)
            } else if let Some(section) = target.strip_prefix('§') {
                sections.contains(section)
            } else {
                stems.contains(&target)
            };
            if !resolves {
                problems.push(format!(
                    "{path}:{line}: [[{inner}]] resolves to no note or section"
                ));
            }
        }
    }

    for problem in &problems {
        println!("{problem}");
    }
    if !problems.is_empty() {
        bail!("spec check: {} problem(s)", problems.len());
    }
    println!(
        "spec check: {} rulings, {proofs} proofs, {cited} citations in {citing_files} files, {links} links: ok",
        notes.len()
    );
    Ok(())
}

/* -------------------------------------------------------------------------------- the index */

fn render_index(notes: &[RulingNote]) -> Result<String> {
    let mut rows: Vec<(u64, &RulingNote)> = Vec::with_capacity(notes.len());
    for note in notes {
        let id = note
            .id
            .as_deref()
            .with_context(|| format!("{}: no `id` in the front matter", note.path))?;
        let number =
            ruling_number(id).with_context(|| format!("{}: `id: {id}` is not a ruling id", note.path))?;
        rows.push((number, note));
    }
    rows.sort_by_key(|(number, _)| *number);
    let mut out = String::from(INDEX_HEADER);
    for (_, note) in rows {
        let id = note.id.as_deref().unwrap_or("");
        let title = note.title.as_deref().unwrap_or("").replace('|', "\\|");
        let stem = &note.stem;
        let proofs: Vec<String> = note.proven_in.iter().map(|path| format!("`{path}`")).collect();
        writeln!(
            out,
            "| {id} | {title} | [{stem}](rulings/{stem}.md) | {} |",
            proofs.join(", ")
        )?;
    }
    Ok(out)
}

fn index(root: &Path) -> Result<()> {
    let notes = read_notes(root)?;
    let out = render_index(&notes)?;
    let path = root.join("spec").join("INDEX.md");
    fs::write(&path, out).with_context(|| format!("writing {}", path.display()))?;
    println!("spec index: wrote spec/INDEX.md ({} rulings)", notes.len());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const NOTE: &str = "---\nid: R195\ntitle: When a card glows yellow (`conditionActive`)\ncards: \"§10.8, §10.9, #10\"\nproven_in:\n  - crates/engine/tests/rules/condition_active.rs\n  - crates/cards/tests/cross/condition_active.rs\n---\nThe ruling ([[R113]], [[§10.8]]).\n";

    #[test]
    fn reads_a_ruling_notes_front_matter() {
        let note = parse_note("spec/rulings/R0195.md".into(), "R0195".into(), NOTE).unwrap();
        assert_eq!(note.id.as_deref(), Some("R195"));
        assert_eq!(
            note.title.as_deref(),
            Some("When a card glows yellow (`conditionActive`)")
        );
        assert_eq!(
            note.proven_in,
            vec![
                "crates/engine/tests/rules/condition_active.rs".to_string(),
                "crates/cards/tests/cross/condition_active.rs".to_string()
            ]
        );
    }

    #[test]
    fn unquotes_yaml_scalars() {
        assert_eq!(unquote("\"\\\"Lose health\\\"\""), "\"Lose health\"");
        assert_eq!(unquote("'it''s'"), "it's");
        assert_eq!(unquote("C #15 Nose Hunter"), "C #15 Nose Hunter");
        let fields = front_matter("---\nproven_in: []\ncards: \"\"\n---\n").unwrap();
        assert_eq!(fields[0], ("proven_in".to_string(), Field::List(Vec::new())));
        assert_eq!(fields[1], ("cards".to_string(), Field::Scalar(String::new())));
    }

    #[test]
    fn refuses_a_note_without_front_matter() {
        assert!(front_matter("id: R1\n").is_err());
        assert!(front_matter("---\nid: R1\n").is_err());
    }

    #[test]
    fn names_a_rulings_file_with_four_digits() {
        assert_eq!(note_stem(1), "R0001");
        assert_eq!(note_stem(195), "R0195");
        assert_eq!(ruling_number("R195"), Some(195));
        assert_eq!(ruling_number("R"), None);
        assert_eq!(ruling_number("§10.3"), None);
    }

    #[test]
    fn finds_citations_as_words_only() {
        // Only ids with a note here: this file is itself in what `check` reads (rule 3).
        let found: Vec<u64> = citations("R1, (R113), R113's, R244–R245; XR5, R5a, R_6, R0195")
            .into_iter()
            .map(|(_, n)| n)
            .collect();
        assert_eq!(found, vec![1, 113, 113, 244, 245, 195]);
    }

    #[test]
    fn reads_ruling_tokens_from_rust_item_names() {
        let src = "#[test]\nfn r90_r81_no_legal_target() {}\nmod r195_glow {\n    fn plain() {}\n}\n// fn r999_commented() {}\nfn arr195_not() {}\nlet s = \"fn r998_in_a_string\";\n";
        let names: Vec<String> = rust_item_names(src).into_iter().map(|(_, name)| name).collect();
        assert_eq!(
            names,
            vec!["r90_r81_no_legal_target", "r195_glow", "plain", "arr195_not"]
        );
        assert_eq!(name_tokens("r90_r81_no_legal_target"), vec![90, 81]);
        assert_eq!(name_tokens("arr195_not"), Vec::<u64>::new());
        assert_eq!(name_tokens("glows_r195"), vec![195]);
        assert!(proves("x.rs", src, 195).unwrap());
        assert!(!proves("x.rs", src, 999).unwrap());
        assert!(!proves("x.rs", src, 998).unwrap());
    }

    #[test]
    fn keeps_line_numbers_through_comments() {
        let src = "/* a\nblock */\nfn r7_x() {}\n";
        assert_eq!(rust_item_names(src), vec![(3, "r7_x".to_string())]);
        let lifetimes = "fn r8_y<'a>(x: &'a str) -> char { '\"' }\nfn r9_z() {}\n";
        let names: Vec<String> = rust_item_names(lifetimes)
            .into_iter()
            .map(|(_, name)| name)
            .collect();
        assert_eq!(names, vec!["r8_y", "r9_z"]);
    }

    #[test]
    fn reads_typescript_test_titles() {
        let src = "describe(\"R143 — the optional seed\", () => {\n  it(\"plays (R112)\", () => {});\n  it.skip('R5 skipped', () => {});\n  test(`R191 B5 ${row.name}`, () => {});\n  submit(\"R7 not a test\");\n});\n";
        assert_eq!(
            ts_test_titles(src),
            vec![
                "R143 — the optional seed",
                "plays (R112)",
                "R5 skipped",
                "R191 B5 ${row.name}"
            ]
        );
        assert!(proves("a.test.ts", src, 112).unwrap());
        assert!(proves("a.test.tsx", src, 191).unwrap());
        assert!(!proves("a.test.ts", src, 7).unwrap());
        assert!(!proves("a.test.ts", src, 11).unwrap());
    }

    #[test]
    fn credits_an_sql_proof_only_from_a_heading() {
        let src = "-- R107, R108 and R109 are not proved here\n\\echo '### R104: the alphabet ###'\n\\echo '=== CHECK 15 (R105): stale version ==='\n\\echo '### R110: reusable (R142) ###'\n\\echo '-- R109 prose'\n";
        assert!(proves("x.sql", src, 104).unwrap());
        assert!(proves("x.sql", src, 105).unwrap());
        assert!(proves("x.sql", src, 142).unwrap());
        assert!(!proves("x.sql", src, 107).unwrap());
        assert!(!proves("x.sql", src, 109).unwrap());
        assert!(!proves("x.sql", src, 10).unwrap());
    }

    #[test]
    fn refuses_a_proof_that_is_not_a_test_file() {
        assert!(proves("notes.md", "R1", 1).is_err());
    }

    #[test]
    fn finds_links_outside_code() {
        let text = "See [[R113]] and [[§10.3]], `[[R1]]` is code.\n```\n[[R2]]\n```\n[[INDEX|the index]] [[11-rulings#provenance]]\n";
        let targets: Vec<String> = wiki_links(text)
            .into_iter()
            .map(|(_, _, target)| target)
            .collect();
        assert_eq!(targets, vec!["R113", "§10.3", "INDEX", "11-rulings"]);
        assert_eq!(wiki_links(text)[2].0, 5);
    }

    #[test]
    fn reads_section_ids_from_headings() {
        let text = "## 10. Engine implementation guide\n\n### 10.3 Events and triggers\n### 10.10 Client rendering\n## Not a section\n#### 10.3.1 too deep\n";
        assert_eq!(section_ids(text), vec!["10", "10.3", "10.10"]);
    }

    #[test]
    fn renders_the_index_in_id_order() {
        let notes = vec![
            parse_note(
                "spec/rulings/R0010.md".into(),
                "R0010".into(),
                "---\nid: R10\ntitle: a | b\nproven_in: []\n---\n",
            )
            .unwrap(),
            parse_note(
                "spec/rulings/R0002.md".into(),
                "R0002".into(),
                "---\nid: R2\ntitle: Two\nproven_in:\n  - x.rs\n  - y.ts\n---\n",
            )
            .unwrap(),
        ];
        let out = render_index(&notes).unwrap();
        assert!(out.starts_with(INDEX_HEADER));
        assert_eq!(
            &out[INDEX_HEADER.len()..],
            "| R2 | Two | [R0002](rulings/R0002.md) | `x.rs`, `y.ts` |\n| R10 | a \\| b | [R0010](rulings/R0010.md) |  |\n"
        );
    }
}
