//! BUILD M4-T2 acceptance: the registry test. It proves the contract the card files and the test
//! harness are written against — that `REGISTRY` (TS `CARDS`) is keyed by catalog id, that every def
//! is the catalog's own, that `register_all()` hands the engine the whole catalog and the scripts, and
//! that a card with no script file yet degrades to `empty_script()` (TS `EMPTY_SCRIPT`) instead of
//! crashing.
//!
//! It also owns the unit tests for `scripts/naming.ts`, the id <-> filename convention that
//! `gen-registry.ts` (which files exist) and `missing-tests.ts` (which tests are missing) shared. In
//! Rust the registry is generated by `crates/cards/build.rs` (SURFACE §7.4), which also refuses a file
//! without `ID`, an `ID` the catalog lacks and two files claiming one card, so the TS `buildRegistry`
//! error paths are proved here as the properties the build guarantees; `naming.ts` itself is the
//! tools' (`crates/tools/src/patches.rs`), out of this crate's reach, so its rules are copied below
//! (`mod naming`, fullsend builder rule 5) and held to the catalog as the TS tests held them.
//!
//! Port of `packages/cards/test/registry.test.ts`.

use indexmap::{IndexMap, IndexSet};
use jackioh_cards::{CATALOG, CATALOG_IDS, CATALOG_VERSION, REGISTRY, card_def, register_all, scripts_of};
use jackioh_engine::{CardDefs, CardScripts, Script, empty_script};
use serde_json::{Value, json};

use naming::{
    compare_sort_keys, expected_basename, expected_rel_path, folder_of, matches_card, module_alias_of,
    prefix_rank, resolve_basename, resolve_rel_path, set_segment_of, slug_prefix_of, slugify, sort_key,
};

/// The whole catalog, however many entries it holds. `catalog.rs` proves the census (SPEC §8 + §7
/// and B2.1's per-set sizes).
fn catalog_size() -> usize {
    CATALOG_IDS.len()
}

/// BUILD M4-T2's gate is "every catalog id has a script and every script has a catalog entry".
///
/// The second half is strict today. The first half cannot be: the card waves write the script files,
/// and this test has to stay green while they land one at a time. So the ids with no script are
/// compared against an allowlist, and this flag is the whole gate:
///
///   every card filed -> set EXPECT_ALL_SCRIPTS = true (this one line). The allowlist becomes empty
///   and the test then fails, by id, for every card still missing its script file.
///
/// The allowlist is computed instead of transcribed on purpose: with many agents adding card files in
/// parallel, a hand-listed one would funnel all of them through the same line of this file.
const EXPECT_ALL_SCRIPTS: bool = false;

/// Core's files have all landed (M4-T4), so a Core card without a script is a regression; the
/// Classic and Classic+ scripts land in their own card waves (B10.2, M9-T6 … M9-T8).
fn ids_allowed_without_script() -> Vec<String> {
    if EXPECT_ALL_SCRIPTS {
        Vec::new()
    } else {
        CATALOG_IDS
            .iter()
            .filter(|id| set_segment_of(id) != Some("core"))
            .cloned()
            .collect()
    }
}

/// TS `Object.keys(CARDS)`: every scripted id, in `REGISTRY`'s order.
fn scripted_ids() -> Vec<String> {
    REGISTRY.iter().map(|(id, _)| (*id).to_string()).collect()
}

/// TS `CATALOG_IDS.filter((id) => CARDS[id] === undefined)`.
fn ids_without_script() -> Vec<String> {
    let scripted: IndexSet<String> = scripted_ids().into_iter().collect();
    CATALOG_IDS
        .iter()
        .filter(|id| !scripted.contains(id.as_str()))
        .cloned()
        .collect()
}

/// Any real card, for the error-path tests. #1 Big D-fender is index 1 (SPEC §8).
fn some_id() -> String {
    CATALOG_IDS
        .first()
        .cloned()
        .unwrap_or_else(|| "core-001".to_string())
}

/// `CARDS[id]`: the card file's scripts, for an id the test already knows is present.
fn module_for(id: &str) -> CardScripts {
    match REGISTRY.iter().find(|(entry, _)| *entry == id) {
        Some((_, script)) => script(),
        None => panic!("no script registered for \"{id}\""),
    }
}

/// What a script declares, as data: which hooks it has, its declarations and its trigger, resume and
/// check names. A script holds closures, so two scripts are compared by this (TS compared the
/// objects by identity, which a script rebuilt by its file's `script()` cannot keep).
fn fingerprint(script: &Script) -> Value {
    let trigger_ids = |triggers: &[jackioh_engine::TriggerDef]| -> Vec<String> {
        triggers.iter().map(|trigger| trigger.id.clone()).collect()
    };
    json!({
        "hooks": {
            "cost": script.cost.is_some(),
            "cry": script.cry.is_some(),
            "death": script.death.is_some(),
            "startOfGame": script.start_of_game.is_some(),
            "entersHand": script.enters_hand.is_some(),
            "delayed": script.delayed.is_some(),
            "setStat": script.set_stat.is_some(),
            "startOfTurn": script.start_of_turn.is_some(),
            "endOfTurn": script.end_of_turn.is_some(),
            "aura": script.aura.is_some(),
            "onPlayHook": script.on_play_hook.is_some(),
            "staticFlags": script.static_flags.is_some(),
            "conditionMet": script.condition_met.is_some(),
            "preview": script.preview.is_some(),
            "costAura": script.cost_aura.is_some(),
            "graveyardPlay": script.graveyard_play.is_some(),
            "targetingDiscards": script.targeting_discards.is_some(),
            "recordsPlayAs": script.records_play_as.is_some(),
            "drawLimit": script.draw_limit.is_some(),
            "heroGuard": script.hero_guard.is_some(),
            "conditionalKeywords": script.conditional_keywords.is_some(),
            "afterAttack": script.after_attack.is_some(),
            "afterAttacked": script.after_attacked.is_some(),
            "plagueMultiplier": script.plague_multiplier.is_some(),
            "quests": script.quests.is_some(),
            "tributeWhen": script.tribute_when.is_some(),
            "wouldCounter": script.would_counter.is_some(),
            "startOfOpponentTurn": script.start_of_opponent_turn.is_some(),
            "attackMods": script.attack_mods.is_some(),
        },
        "resume": script.resume.keys().map(|key| (*key).to_string()).collect::<Vec<_>>(),
        "triggers": trigger_ids(&script.triggers),
        "handTriggers": trigger_ids(&script.hand_triggers),
        "deckTriggers": trigger_ids(&script.deck_triggers),
        "graveyardTriggers": trigger_ids(&script.graveyard_triggers),
        "targets": serde_json::to_value(&script.targets).expect("target declarations serialise"),
        "modes": serde_json::to_value(&script.modes).expect("mode declarations serialise"),
        "activations": script.activations.len(),
        "targetChecks": script.target_checks.keys().map(|key| (*key).to_string()).collect::<Vec<_>>(),
        "replacements": script.replacements.len(),
    })
}

mod registry_build_m4_t2 {
    use super::*;

    #[test]
    fn keys_cards_by_catalog_id_and_takes_every_def_from_the_catalog() {
        for id in scripted_ids() {
            assert!(CATALOG_IDS.contains(&id), "\"{id}\" is not a catalog id");
            // A script file names its card by `ID` alone and build.rs takes the def from catalog.json
            // (SURFACE §7.4), so its def is the one the engine and the client see: a hand-written def
            // cannot exist to drift from catalog.json.
            assert_eq!(card_def(&id).id, id, "{id}: def must come from the catalog");
        }
    }

    #[test]
    fn has_no_duplicate_def_id() {
        // build.rs refuses a duplicate `ID`, so the count check is what catches two files that both
        // compile to the same card.
        let ids = scripted_ids();
        assert_eq!(scripts_of().len(), REGISTRY.len());
        assert_eq!(ids.iter().collect::<IndexSet<_>>().len(), REGISTRY.len());
    }

    #[test]
    fn two_scripts_never_claim_one_card_build_rs_refuses_it() {
        // TS: `buildRegistry([mod, mod])` threw /two card scripts claim/. build.rs is that check now
        // (SURFACE §7.4): what reaches the registry has one file per id, sorted by id.
        let ids = scripted_ids();
        let mut sorted = ids.clone();
        sorted.sort();
        assert_eq!(ids, sorted, "REGISTRY is sorted by ID");
        let mut claimed: IndexMap<String, usize> = IndexMap::new();
        for id in &ids {
            *claimed.entry(id.clone()).or_insert(0) += 1;
        }
        let twice: Vec<String> = claimed
            .into_iter()
            .filter(|(_, n)| *n > 1)
            .map(|(id, _)| format!("two card scripts claim \"{id}\""))
            .collect();
        assert_eq!(twice, Vec::<String>::new());
        assert!(CATALOG.contains_key(some_id().as_str()));
    }

    #[test]
    fn a_script_s_def_is_always_a_catalog_card_build_rs_refuses_one_that_is_not() {
        // TS: a def whose id was "core-999" threw /not in/. build.rs refuses an `ID` the catalog lacks.
        let strangers: Vec<String> = scripted_ids()
            .into_iter()
            .filter(|id| !CATALOG.contains_key(id.as_str()))
            .map(|id| format!("\"{id}\" is not in crates/cards/catalog.json"))
            .collect();
        assert_eq!(strangers, Vec::<String>::new());
        assert!(!CATALOG.contains_key("core-999"));
    }

    #[test]
    fn register_all_registers_every_def_and_the_catalog_version() {
        register_all();
        let registered = jackioh_engine::catalog::registered_catalog();
        assert_eq!(registered.len(), catalog_size());
        for id in CATALOG_IDS.iter() {
            assert_eq!(
                registered.get(id.as_str()),
                Some(&card_def(id)),
                "\"{id}\" reached the engine"
            );
        }
        assert_eq!(jackioh_engine::catalog::catalog_version(), CATALOG_VERSION);
    }

    #[test]
    fn register_all_is_idempotent_and_cheap_to_repeat() {
        register_all();
        let catalog_after_first: &'static CardDefs = jackioh_engine::catalog::registered_catalog();
        let scripts_after_first: Vec<String> = scripts_of().keys().cloned().collect();
        register_all();
        register_all();
        assert!(std::ptr::eq(
            jackioh_engine::catalog::registered_catalog(),
            catalog_after_first
        ));
        assert_eq!(jackioh_engine::catalog::registered_catalog(), &*CATALOG);
        assert_eq!(
            scripts_of().keys().cloned().collect::<Vec<_>>(),
            scripts_after_first
        );
        assert_eq!(jackioh_engine::catalog::catalog_version(), CATALOG_VERSION);
    }

    #[test]
    fn register_all_puts_the_real_registries_back_after_a_fixture_catalog() {
        register_all();
        // An engine test registers its own fixtures (BUILD §0). In Rust a fixture registration is the
        // testkit's thread-local override (SURFACE §8), so it is in force on its own thread and never
        // anywhere else: the registries every other thread reads are the real ones.
        std::thread::scope(|scope| {
            scope.spawn(|| {
                jackioh_engine::testkit::register_catalog(CardDefs::new());
                jackioh_engine::testkit::register_scripts(IndexMap::new());
                assert!(jackioh_engine::catalog::registered_catalog().is_empty());
            });
        });
        register_all();
        assert_eq!(jackioh_engine::catalog::registered_catalog(), &*CATALOG);
        assert_eq!(jackioh_engine::catalog::catalog_version(), CATALOG_VERSION);
    }

    #[test]
    fn gives_the_engine_each_module_s_own_base_and_radiant_script() {
        register_all();
        let game = jackioh_engine::testkit::scenario(json!({}));
        for id in scripted_ids() {
            let module = module_for(&id);
            let entry = jackioh_engine::scripts::scripts_for(game.state(), &id);
            assert_eq!(
                fingerprint(&entry.base),
                fingerprint(&module.base),
                "{id}: base script"
            );
            assert_eq!(
                fingerprint(&entry.radiant),
                fingerprint(&module.radiant),
                "{id}: radiant script"
            );
        }
    }

    #[test]
    fn falls_back_to_empty_script_for_a_catalog_id_with_no_script_so_nothing_crashes() {
        register_all();
        // The first uncovered card while the card waves are in flight; once every card has a script
        // there is no such id, and an unregistered defId exercises the same engine fallback.
        let unscripted = ids_without_script()
            .first()
            .cloned()
            .unwrap_or_else(|| "core-not-a-card".to_string());
        let game = jackioh_engine::testkit::scenario(json!({}));
        let entry = jackioh_engine::scripts::scripts_for(game.state(), &unscripted);
        assert_eq!(fingerprint(&entry.base), fingerprint(&empty_script()));
        assert_eq!(fingerprint(&entry.radiant), fingerprint(&empty_script()));
    }

    #[test]
    fn every_catalog_id_has_a_script_and_every_script_has_a_catalog_entry() {
        // Strict: a script file can never name a card the catalog does not ship.
        let strangers: Vec<String> = scripted_ids()
            .into_iter()
            .filter(|id| !CATALOG_IDS.contains(id))
            .collect();
        assert_eq!(strangers, Vec::<String>::new());
        // Strict once EXPECT_ALL_SCRIPTS flips (see the comment on the flag).
        let allowed = ids_allowed_without_script();
        let missing: Vec<String> = ids_without_script()
            .into_iter()
            .filter(|id| !allowed.contains(id))
            .collect();
        assert_eq!(missing, Vec::<String>::new());
        if EXPECT_ALL_SCRIPTS {
            assert_eq!(scripted_ids().len(), catalog_size());
        }
    }
}

mod naming_build_m4_t2_m4_t3 {
    use super::*;

    fn ids() -> Vec<String> {
        (*CATALOG_IDS).clone()
    }

    fn name_of(id: &str) -> String {
        card_def(id).name
    }

    #[test]
    fn turns_a_catalog_id_into_its_filename_prefix() {
        assert_eq!(slug_prefix_of("core-001").as_deref(), Ok("001"));
        assert_eq!(slug_prefix_of("core-043").as_deref(), Ok("043"));
        assert_eq!(slug_prefix_of("core-051-1").as_deref(), Ok("051-1"));
        assert_eq!(slug_prefix_of("core-t-rush").as_deref(), Ok("t-rush"));
        assert_eq!(slug_prefix_of("classicplus-012-1").as_deref(), Ok("012-1"));
        assert_eq!(slug_prefix_of("classicplus-t-ai-01").as_deref(), Ok("t-ai-01"));
        assert!(slug_prefix_of("core").is_err_and(|error| error.contains("not a catalog id")));
    }

    #[test]
    fn files_each_set_in_its_own_folder_b2_2_core_at_the_top_classic_and_classic_plus() {
        assert_eq!(set_segment_of("core-043"), Some("core"));
        assert_eq!(set_segment_of("classic-043"), Some("classic"));
        assert_eq!(set_segment_of("classicplus-043"), Some("classicplus"));
        assert_eq!(set_segment_of("boss-001"), None);
        assert_eq!(folder_of("core-043"), "");
        assert_eq!(folder_of("classic-043"), "classic");
        assert_eq!(folder_of("classicplus-012-1"), "classic-plus");
        assert_eq!(
            expected_rel_path("core-043", &name_of("core-043")),
            "043-big-felinor"
        );
        assert_eq!(
            expected_rel_path("classic-043", &name_of("classic-043")),
            "classic/043-plague-nuke"
        );
        assert_eq!(
            expected_rel_path("classicplus-012-1", &name_of("classicplus-012-1")),
            "classic-plus/012-1-devour"
        );
        // The AI generated cards are shared tokens of Classic+, but carry their slug (their prefix alone
        // names no card), unlike Core's §7 tokens.
        assert_eq!(
            expected_rel_path("classicplus-t-ai-01", &name_of("classicplus-t-ai-01")),
            "classic-plus/t-ai-01-helpful-assistant"
        );
        assert_eq!(
            expected_rel_path("core-t-rush", &name_of("core-t-rush")),
            "t-rush"
        );
    }

    #[test]
    fn resolves_a_file_by_its_folder_s_set_since_an_index_repeats_across_sets() {
        let ids = ids();
        assert_eq!(
            resolve_rel_path("043-big-felinor", &ids).as_deref(),
            Some("core-043")
        );
        assert_eq!(
            resolve_rel_path("classic/043-plague-nuke", &ids).as_deref(),
            Some("classic-043")
        );
        assert_eq!(
            resolve_rel_path("classic-plus/043-ai-slop", &ids).as_deref(),
            Some("classicplus-043")
        );
        // A misspelled slug still lands on its card, in its own set only.
        assert_eq!(
            resolve_rel_path("classic/043-plague-nuk", &ids).as_deref(),
            Some("classic-043")
        );
        assert_eq!(
            resolve_rel_path("classic-plus/012-1-devour", &ids).as_deref(),
            Some("classicplus-012-1")
        );
        assert_eq!(
            resolve_rel_path("classic-plus/012-the-mother-pancake", &ids).as_deref(),
            Some("classicplus-012")
        );
        assert_eq!(
            resolve_rel_path("classic-plus/t-ai-10-fine-tuning", &ids).as_deref(),
            Some("classicplus-t-ai-10")
        );
        assert_eq!(resolve_rel_path("classic/091-no-such-card", &ids), None);
        assert_eq!(resolve_rel_path("legacy/043-big-felinor", &ids), None);
        assert_eq!(
            resolve_basename("043-plague-nuke", &ids, "classic").as_deref(),
            Some("classic-043")
        );
    }

    #[test]
    fn slugifies_a_card_name_the_way_the_shipped_filenames_spell_it() {
        assert_eq!(slugify("Big D-fender"), "big-d-fender");
        assert_eq!(slugify("KY's Empty Notebook"), "kys-empty-notebook"); // apostrophe drops out
        assert_eq!(slugify("CN-Virus"), "cn-virus");
        assert_eq!(slugify("/fullsend"), "fullsend");
        assert_eq!(
            slugify("Call to Chaos (Core Edition)"),
            "call-to-chaos-core-edition"
        );
        assert_eq!(slugify("\"Miss\" Mrow"), "miss-mrow");
        assert_eq!(slugify("4-mana 7/7"), "4-mana-7-7");
    }

    #[test]
    fn names_the_file_each_card_expects() {
        assert_eq!(
            expected_basename("core-001", &name_of("core-001")),
            "001-big-d-fender"
        );
        assert_eq!(
            expected_basename("core-043", &name_of("core-043")),
            "043-big-felinor"
        );
        assert_eq!(
            expected_basename("core-051-1", &name_of("core-051-1")),
            "051-1-kys-empty-notebook"
        );
        assert_eq!(
            expected_basename("core-090-1", &name_of("core-090-1")),
            "090-1-cn-virus"
        );
        // SPEC §7's shared tokens are filed under the bare prefix.
        assert_eq!(
            expected_basename("core-t-rush", &name_of("core-t-rush")),
            "t-rush"
        );
        assert_eq!(
            expected_basename("core-t-bread", &name_of("core-t-bread")),
            "t-bread"
        );
    }

    #[test]
    fn a_token_sub_index_after_a_card_prefix_is_not_a_slug_051_vs_051_1() {
        let ids = ids();
        // The hard case: KY's Empty Notebook (#51.1) lives next to KY's Private Tutor (#51).
        assert!(matches_card("051-1-kys-empty-notebook", "core-051-1", None));
        assert!(!matches_card("051-1-kys-empty-notebook", "core-051", None));
        assert!(matches_card("051-kys-private-tutor", "core-051", None));
        assert!(!matches_card("051-kys-private-tutor", "core-051-1", None));
        // Same shape, same answers, with the exact catalog-aware resolution.
        assert!(matches_card(
            "051-1-kys-empty-notebook",
            "core-051-1",
            Some(ids.as_slice())
        ));
        assert!(!matches_card(
            "051-1-kys-empty-notebook",
            "core-051",
            Some(ids.as_slice())
        ));
    }

    #[test]
    fn matches_the_slugless_shared_token_form_and_rejects_a_bare_prefix_mismatch() {
        assert!(matches_card("t-rush", "core-t-rush", None));
        assert!(matches_card("t-rush-token", "core-t-rush", None));
        assert!(!matches_card("t-rush", "core-t-sheep", None));
        assert!(!matches_card("1-big-d-fender", "core-001", None)); // unpadded prefix
        assert!(!matches_card("0011-big-d-fender", "core-001", None));
    }

    #[test]
    fn needs_all_ids_for_25_whose_own_slug_starts_with_a_digit_segment() {
        let ids = ids();
        // "4-mana 7/7" slugifies to `4-mana-7-7`, so the heuristic reads the leading `4-` as a token
        // sub-index; the catalog says otherwise, because `core-025-4` does not exist. This is why every
        // script in this package resolves against the id list.
        assert!(!matches_card("025-4-mana-7-7", "core-025", None));
        assert!(matches_card("025-4-mana-7-7", "core-025", Some(ids.as_slice())));
        assert_eq!(
            resolve_basename("025-4-mana-7-7", &ids, "").as_deref(),
            Some("core-025")
        );
    }

    #[test]
    fn round_trips_every_catalog_id_through_its_expected_filename() {
        let ids = ids();
        // The whole catalog at once: no two cards may claim one path, and every expected path must
        // resolve back to the card that expects it — which is what made `missing-tests.ts` a
        // trustworthy gate.
        let mut seen: IndexMap<String, String> = IndexMap::new();
        for id in &ids {
            let path = expected_rel_path(id, &name_of(id));
            let owner = seen.get(&path).cloned();
            assert_eq!(owner, None, "{path}.ts is claimed by both {owner:?} and {id}");
            seen.insert(path.clone(), id.clone());
            assert_eq!(
                resolve_rel_path(&path, &ids).as_deref(),
                Some(id.as_str()),
                "{path} -> {id}"
            );
            assert!(matches_card(
                &expected_basename(id, &name_of(id)),
                id,
                Some(ids.as_slice())
            ));
        }
        assert_eq!(seen.len(), catalog_size());
    }

    #[test]
    fn resolves_nothing_for_a_filename_that_names_no_card() {
        let ids = ids();
        assert_eq!(resolve_basename("harness", &ids, ""), None);
        assert_eq!(resolve_basename("15-hit-job", &ids, ""), None); // unpadded
        assert_eq!(resolve_basename("core-001-big-d-fender", &ids, ""), None); // id, not prefix
    }

    #[test]
    fn orders_files_by_spec_5_index_card_tokens_after_their_card_shared_tokens_last() {
        assert_eq!(prefix_rank("001"), 1.0);
        assert_eq!(prefix_rank("025"), 25.0);
        assert!((prefix_rank("051-1") - 51.1).abs() < 0.005);
        assert_eq!(prefix_rank("t-rush"), f64::INFINITY);

        let mut entries: Vec<(String, String)> = CATALOG_IDS
            .iter()
            .map(|id| (id.clone(), expected_rel_path(id, &name_of(id))))
            .collect();
        entries.sort_by(|a, b| {
            compare_sort_keys(
                &sort_key(&a.1, Some(a.0.as_str())),
                &sort_key(&b.1, Some(b.0.as_str())),
            )
        });
        let ordered: Vec<String> = entries.into_iter().map(|(_, path)| path).collect();
        let index_of = |path: &str| ordered.iter().position(|entry| entry == path);

        // Catalog order: Core, then Classic, then Classic+ (B2.2), each by §5 index.
        assert_eq!(ordered[0], "001-big-d-fender");
        assert_eq!(
            index_of("051-1-kys-empty-notebook"),
            index_of("051-kys-private-tutor").map(|at| at + 1)
        );
        assert_eq!(index_of("100-ceaseless-void"), Some(111 - 7));
        assert_eq!(
            ordered[105..111].to_vec(),
            ["t-bread", "t-coin", "t-felinor", "t-ghoul", "t-rush", "t-sheep"]
                .map(String::from)
                .to_vec()
        );
        assert_eq!(ordered[111], "classic/001-curse-of-the-forgotten-classic");
        // Classic's 90 cards, then its one shared token, Glitch (R674).
        assert_eq!(ordered[201], "classic/t-glitch-glitch");
        assert_eq!(ordered[202], "classic-plus/001-doom-shroom");
        assert_eq!(
            index_of("classic-plus/012-8-frostspatula"),
            index_of("classic-plus/012-the-mother-pancake").map(|at| at + 8)
        );
        // Classic+ ends with its ten shared tokens, the AI generated cards; a set after it in catalog
        // order (Meditative, R1420) follows them.
        let classic_plus_end = ordered
            .iter()
            .rposition(|path| path.starts_with("classic-plus/"))
            .expect("Classic+ has files");
        assert_eq!(
            ordered[classic_plus_end - 9],
            "classic-plus/t-ai-01-helpful-assistant"
        );
        assert_eq!(ordered[classic_plus_end], "classic-plus/t-ai-10-fine-tuning");
        assert!(
            ordered[classic_plus_end + 1..]
                .iter()
                .all(|path| path.starts_with("meditative/")),
            "only a set after Classic+ follows it"
        );
        // Catalog.json's own order, but for the shared tokens, which the files sort by name.
        let shared = |path: &str| path.starts_with("t-") || path.contains("/t-");
        let catalog_order: Vec<String> = CATALOG_IDS
            .iter()
            .map(|id| expected_rel_path(id, &name_of(id)))
            .filter(|path| !shared(path))
            .collect();
        let file_order: Vec<String> = ordered.iter().filter(|path| !shared(path)).cloned().collect();
        assert_eq!(catalog_order, file_order);
        // Unrecognised filenames sort after everything, so the barrel stays deterministic.
        assert_eq!(
            compare_sort_keys(
                &sort_key("t-rush", Some("core-t-rush")),
                &sort_key("mystery", None)
            ),
            std::cmp::Ordering::Less
        );
    }

    #[test]
    fn makes_a_legal_unique_module_alias_for_each_filename() {
        assert_eq!(module_alias_of("001-big-d-fender"), "m001_big_d_fender");
        assert_eq!(
            module_alias_of("051-1-kys-empty-notebook"),
            "m051_1_kys_empty_notebook"
        );
        assert_eq!(module_alias_of("t-rush"), "mt_rush");
        assert_eq!(
            module_alias_of("classic/043-plague-nuke"),
            "mclassic_043_plague_nuke"
        );
        assert_eq!(
            module_alias_of("classic-plus/043-ai-slop"),
            "mclassic_plus_043_ai_slop"
        );
        let aliases: IndexSet<String> = CATALOG_IDS
            .iter()
            .map(|id| module_alias_of(&expected_rel_path(id, &name_of(id))))
            .collect();
        assert_eq!(aliases.len(), catalog_size());
    }
}

/// `packages/cards/scripts/naming.ts`'s rules, copied (fullsend builder rule 5: the tools' port in
/// `crates/tools/src/patches.rs` is a binary crate this test cannot link). The catalog-id <-> filename
/// convention for the TS card scripts and card tests (BUILD M4-T2 `cards/src/scripts/NNN-slug.ts`,
/// M4-T3 `cards/test/NNN-slug.test.ts`, SPEC §10.9, and patch v0.2.0's set folders, B2.2):
///
///   core-001             "Big D-fender"         src/scripts/001-big-d-fender.ts
///   core-051-1           "KY's Empty Notebook"  src/scripts/051-1-kys-empty-notebook.ts
///   core-t-rush          "Rush Token"           src/scripts/t-rush.ts
///   classic-043          "Plague Nuke"          src/scripts/classic/043-plague-nuke.ts
///   classicplus-012-1    "Devour"               src/scripts/classic-plus/012-1-devour.ts
///   classicplus-t-ai-01  "Helpful Assistant"    src/scripts/classic-plus/t-ai-01-helpful-assistant.ts
///
/// A file's path is its set's folder (none for Core) and a basename `<prefix>-<slug>`, where the prefix
/// is the id minus its set segment, except for Core's named tokens of SPEC §7 — the four shared ones,
/// The Coin and the Ghoul Token — which are filed under the bare prefix (`t-rush`, `t-coin`). An index
/// repeats across sets, so the folder, never the basename alone, says which set a file belongs to.
mod naming {
    use std::cmp::Ordering;

    /// Every shipped id is `<set>-<prefix>`, the set segment holding no hyphen (`classicplus`, B2.2).
    const SET_SEGMENT_SEPARATOR: char = '-';

    /// The catalog's sets' id segments and the folder each one's scripts and tests live in, in catalog
    /// order: Core at the top of `src/scripts/` and `test/`, the others in a folder of their own. A set
    /// that has not shipped (R1420) is listed too: its cards are in the catalog and have files.
    const SET_FOLDERS: &[(&str, &str)] = &[
        ("core", ""),
        ("classic", "classic"),
        ("classicplus", "classic-plus"),
        ("meditative", "meditative"),
    ];

    /// `classic-043` -> `classic`; `None` for an id whose set segment names no shipped set.
    pub fn set_segment_of(id: &str) -> Option<&'static str> {
        let cut = id.find(SET_SEGMENT_SEPARATOR)?;
        if cut == 0 {
            return None;
        }
        let segment = &id[..cut];
        SET_FOLDERS
            .iter()
            .find(|(known, _)| *known == segment)
            .map(|(known, _)| *known)
    }

    /// The folder a catalog id's script and test live in: `""` for Core, `classic`, `classic-plus`.
    pub fn folder_of(id: &str) -> &'static str {
        match set_segment_of(id) {
            Some(segment) => SET_FOLDERS
                .iter()
                .find(|(known, _)| *known == segment)
                .map_or("", |(_, folder)| *folder),
            None => "",
        }
    }

    /// The set segment a folder holds (`""` -> `core`), or `None` for a folder that holds none.
    pub fn segment_of_folder(folder: &str) -> Option<&'static str> {
        SET_FOLDERS
            .iter()
            .find(|(_, known)| *known == folder)
            .map(|(segment, _)| *segment)
    }

    /// Catalog order of the sets (Core, Classic, Classic+, Meditative), for sorting; an unknown set sorts last.
    pub fn set_rank(id: Option<&str>) -> usize {
        match id.and_then(set_segment_of) {
            Some(segment) => SET_FOLDERS
                .iter()
                .position(|(known, _)| *known == segment)
                .unwrap_or(SET_FOLDERS.len()),
            None => SET_FOLDERS.len(),
        }
    }

    /// The filename prefix of a catalog id: the id minus its leading set segment.
    /// `core-001` -> `001`, `core-051-1` -> `051-1`, `core-t-rush` -> `t-rush`,
    /// `classicplus-t-ai-01` -> `t-ai-01`. TS threw on a string that is no catalog id.
    pub fn slug_prefix_of(id: &str) -> Result<String, String> {
        match id.find(SET_SEGMENT_SEPARATOR) {
            Some(cut) if cut > 0 && cut != id.len() - 1 => Ok(id[cut + 1..].to_string()),
            _ => Err(format!(
                "\"{id}\" is not a catalog id (expected \"<set>-<prefix>\", e.g. \"core-043\")"
            )),
        }
    }

    /// A catalog id's prefix, for an id the catalog holds (TS let the throw propagate).
    fn prefix_of_catalog_id(id: &str) -> String {
        slug_prefix_of(id).unwrap_or_else(|error| panic!("{error}"))
    }

    /// `/^\d+$/`.
    fn all_digits(text: &str) -> bool {
        !text.is_empty() && text.bytes().all(|b| b.is_ascii_digit())
    }

    /// `051-1` and `t-rush` are token prefixes; `051` is a card prefix. Nothing nests deeper.
    pub fn is_token_prefix(prefix: &str) -> bool {
        if prefix.starts_with("t-") {
            return true;
        }
        // `/^\d+-\d+$/`
        match prefix.split_once('-') {
            Some((main, sub)) => all_digits(main) && all_digits(sub),
            None => false,
        }
    }

    /// A shared token's prefix (`t-rush`, `t-ai-01`): a token no one card defines. Core's (SPEC §7's
    /// four shared ones, The Coin and the Ghoul Token) are filed under the bare prefix (`t-rush.ts`);
    /// Classic+'s AI generated cards carry their slug like any card (`t-ai-01-helpful-assistant.ts`).
    pub fn is_shared_token_prefix(prefix: &str) -> bool {
        prefix.starts_with("t-")
    }

    /// A card name as a filename slug: lowercase, apostrophes dropped, every other run of
    /// non-alphanumerics collapsed to one `-`.
    ///
    /// Checked against every name, so: "Big D-fender" -> `big-d-fender`, "KY's Empty Notebook" ->
    /// `kys-empty-notebook` (the apostrophe vanishes rather than becoming a dash), "CN-Virus" ->
    /// `cn-virus`, "/fullsend" -> `fullsend`, "Call to Chaos (Core Edition)" ->
    /// `call-to-chaos-core-edition`, `"Miss" Mrow` -> `miss-mrow`, "4-mana 7/7" -> `4-mana-7-7`,
    /// "Forever&" -> `forever`, "BOOM! Big Max" -> `boom-big-max`.
    pub fn slugify(name: &str) -> String {
        let lower: String = name
            .to_lowercase()
            .chars()
            .filter(|c| !matches!(c, '\'' | '\u{2018}' | '\u{2019}'))
            .collect();
        let mut out = String::with_capacity(lower.len());
        let mut in_gap = false;
        for c in lower.chars() {
            if c.is_ascii_lowercase() || c.is_ascii_digit() {
                // `.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")`: a gap becomes one dash,
                // and none is left at either end.
                if in_gap && !out.is_empty() {
                    out.push('-');
                }
                in_gap = false;
                out.push(c);
            } else {
                in_gap = true;
            }
        }
        out
    }

    /// The canonical basename (no extension, no folder) for a catalog entry: what `gen-registry.ts`
    /// expected to import and what `missing-tests.ts` printed as the file a card still needs.
    pub fn expected_basename(id: &str, name: &str) -> String {
        let prefix = prefix_of_catalog_id(id);
        // Core's SPEC §7 shared tokens are one word already ("Rush Token" under `t-rush`), so the prefix
        // is the whole filename; anything else carries its slug.
        if is_shared_token_prefix(&prefix) && set_segment_of(id) == Some("core") {
            return prefix;
        }
        format!("{prefix}-{}", slugify(name))
    }

    /// The path under `src/scripts/` or `test/`, without an extension: `classic/043-plague-nuke`.
    pub fn expected_rel_path(id: &str, name: &str) -> String {
        let folder = folder_of(id);
        let basename = expected_basename(id, name);
        if folder.is_empty() {
            basename
        } else {
            format!("{folder}/{basename}")
        }
    }

    /// Whether `basename` (no extension) is the file of catalog id `id`, in that id's own set folder.
    ///
    /// The slug itself is not checked: the prefix decides which card a file belongs to, so a misspelled
    /// slug still lands on the right card. The one hard case is the prefix boundary:
    /// `051-1-kys-empty-notebook` belongs to `core-051-1` and must NOT be read as a slug of `core-051`.
    ///
    /// With `all_ids` (every catalog id) the answer is exact: the longest id prefix of that set the
    /// basename carries wins. Without it the rule is the heuristic "a lone digit segment right after a
    /// card prefix is a token sub-index", which is right for every shipped id except #25 "4-mana 7/7".
    pub fn matches_card(basename: &str, id: &str, all_ids: Option<&[String]>) -> bool {
        if let Some(all_ids) = all_ids {
            return resolve_basename(basename, all_ids, folder_of(id)).as_deref() == Some(id);
        }

        let prefix = prefix_of_catalog_id(id);
        if basename == prefix {
            return true; // the slugless form: `t-rush.ts`
        }
        let Some(rest) = basename.strip_prefix(&format!("{prefix}-")) else {
            return false;
        };
        if rest.is_empty() {
            return false;
        }
        if is_token_prefix(&prefix) {
            return true; // a token id has no sub-token, so the rest is a slug
        }
        // `!/^\d(-|$)/.test(rest)`
        let bytes = rest.as_bytes();
        !(bytes[0].is_ascii_digit() && (bytes.len() == 1 || bytes[1] == b'-'))
    }

    /// Which catalog id a basename in `folder` (`""`, Core's, by default) belongs to, by longest prefix
    /// among that folder's set: `051-1-kys-empty-notebook` matches the prefixes `051` and `051-1`, and
    /// the longer one is the card that owns the file. `None` means the filename names no card of that
    /// set (a typo'd or unpadded prefix), or the folder holds no set.
    pub fn resolve_basename(basename: &str, all_ids: &[String], folder: &str) -> Option<String> {
        let segment = segment_of_folder(folder)?;
        let mut best: Option<String> = None;
        let mut best_length: Option<usize> = None;
        for id in all_ids {
            if set_segment_of(id) != Some(segment) {
                continue;
            }
            let prefix = prefix_of_catalog_id(id);
            if basename != prefix && !basename.starts_with(&format!("{prefix}-")) {
                continue;
            }
            if best_length.is_none_or(|length| prefix.len() > length) {
                best = Some(id.clone());
                best_length = Some(prefix.len());
            }
        }
        best
    }

    /// `classic/043-plague-nuke` -> its folder and basename; a Core path has the folder `""`.
    pub fn split_rel_path(rel_path: &str) -> (&str, &str) {
        match rel_path.rfind('/') {
            None => ("", rel_path),
            Some(cut) => (&rel_path[..cut], &rel_path[cut + 1..]),
        }
    }

    /// Which catalog id a path under `src/scripts/` or `test/` (no extension) belongs to.
    pub fn resolve_rel_path(rel_path: &str, all_ids: &[String]) -> Option<String> {
        let (folder, basename) = split_rel_path(rel_path);
        resolve_basename(basename, all_ids, folder)
    }

    /// A filename prefix as a sortable number, mirroring the engine's index ranking
    /// (`engine/src/catalog.rs` `index_rank`): `001` -> 1, `051-1` -> 51.1 (so a card-defined token
    /// sorts straight after its card), `t-rush` -> +Infinity (shared tokens sort last within their set).
    pub fn prefix_rank(prefix: &str) -> f64 {
        // `/^(\d+)(?:-(\d+))?$/`
        let (main, sub) = match prefix.split_once('-') {
            Some((main, sub)) => (main, Some(sub)),
            None => (prefix, None),
        };
        if !all_digits(main) || sub.is_some_and(|sub| !all_digits(sub)) {
            return f64::INFINITY;
        }
        let text = match sub {
            None => main.to_string(),
            Some(sub) => format!("{main}.{sub}"),
        };
        match text.parse::<f64>() {
            Ok(rank) if rank.is_finite() => rank,
            _ => f64::INFINITY,
        }
    }

    /// A sort key: `[named-no-card tier, set, §5 index rank, path]`.
    pub type SortKey = (u8, usize, f64, String);

    /// The deterministic ordering every tool uses: catalog order — set (Core, Classic, Classic+), then
    /// SPEC §5 index ascending, card-defined tokens after their card, shared tokens last within the set —
    /// and anything that names no catalog card after all of it; then the path, so the order never
    /// depends on the order the filesystem listed a directory.
    pub fn sort_key(path: &str, id: Option<&str>) -> SortKey {
        let tier = if id.is_none() { 1 } else { 0 };
        let set = set_rank(id);
        let rank = match id {
            None => f64::INFINITY,
            Some(id) => prefix_rank(&prefix_of_catalog_id(id)),
        };
        (tier, set, rank, path.to_string())
    }

    /// Compares two `sort_key`s.
    pub fn compare_sort_keys(a: &SortKey, b: &SortKey) -> Ordering {
        if a.0 != b.0 {
            return a.0.cmp(&b.0);
        }
        if a.1 != b.1 {
            return a.1.cmp(&b.1);
        }
        if a.2 != b.2 {
            // Infinity - Infinity is NaN, so compare, don't subtract
            return if a.2 < b.2 {
                Ordering::Less
            } else {
                Ordering::Greater
            };
        }
        a.3.cmp(&b.3)
    }

    /// A legal, unique JS identifier for the namespace import of a script file: paths are unique within
    /// `src/scripts/`, the folder is part of the alias (`classic/043-…` -> `mclassic_043_…`), and the `m`
    /// guard keeps `001-…` from starting an identifier with a digit.
    pub fn module_alias_of(rel_path: &str) -> String {
        let mut out = String::from("m");
        let mut in_gap = false;
        for c in rel_path.chars() {
            if c.is_ascii_alphanumeric() {
                out.push(c);
                in_gap = false;
            } else if !in_gap {
                out.push('_');
                in_gap = true;
            }
        }
        out
    }
}
