//! Writes `apps/web/src/wire/serverConfig.ts` (SURFACE §5.1, §10.4): one
//! `export const NAME = <JSON value>;` line per constant of `crates/server/src/config.rs` that a file
//! under `apps/web/src` or `e2e/` imported from `apps/server/src/config.ts` before the rewrite, sorted
//! by name, so the client keeps reading the server's numbers (CLAUDE.md rule 9) without importing the
//! server. Part 21 points those imports at `@jackioh/server-config`, the alias for this file; CI runs
//! this test and fails on a diff.
//!
//! The list is the 50 names `apps/web/src` and `e2e/` imported from it (multi-line imports and
//! `export { … } from` included), web tests and e2e specs among them: the 42 a one-line grep found,
//! and the 8 the e2e specs import in multi-line lists (`05-reconnect`, `06-room-code`,
//! `10-invite-gate`, `19-queue-modes-and-series`; v0.3.0 part 36). A name added to it needs a
//! constant in `config.rs`; a name the client stops importing can leave it. `ROOM_CODE_FORMAT` joined
//! them for the lobby's room links (R767), and `REPLAY_LIST_PAGE` and `REPLAY_REQUESTS_PER_MINUTE`
//! for the online replays' list and allowance (R768).

use serde_json::{Value, json};

use jackioh_server::config as c;

/// The generated file, relative to this crate.
const OUTPUT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../apps/web/src/wire/serverConfig.ts"
);

const HEADER: &str = "// Generated by crates/server/tests/export_config.rs from crates/server/src/config.rs\n// (SURFACE §5.1). Do not edit: change the constant in config.rs and run the test.\n";

/// Every exported constant and its JSON value. The two objects are written out field by field in
/// TS's key spelling (`groupSize`, `"Classic+"`), which the client indexes by.
fn constants() -> Vec<(&'static str, Value)> {
    vec![
        (
            "API_REQUEST_TIMEOUT_SECONDS",
            json!(c::API_REQUEST_TIMEOUT_SECONDS),
        ),
        (
            "AUTH_EMAIL_RESEND_COOLDOWN_SECONDS",
            json!(c::AUTH_EMAIL_RESEND_COOLDOWN_SECONDS),
        ),
        ("AUTH_PASSWORD_MAX_LENGTH", json!(c::AUTH_PASSWORD_MAX_LENGTH)),
        ("AUTH_PASSWORD_MIN_LENGTH", json!(c::AUTH_PASSWORD_MIN_LENGTH)),
        (
            "AUTH_PENDING_ADDRESS_TTL_SECONDS",
            json!(c::AUTH_PENDING_ADDRESS_TTL_SECONDS),
        ),
        (
            "AUTH_PROVIDER_TIMEOUT_SECONDS",
            json!(c::AUTH_PROVIDER_TIMEOUT_SECONDS),
        ),
        (
            "AUTH_SESSION_REFRESH_MARGIN_SECONDS",
            json!(c::AUTH_SESSION_REFRESH_MARGIN_SECONDS),
        ),
        (
            "AUTH_SESSION_RENEWAL_FLOOR_SECONDS",
            json!(c::AUTH_SESSION_RENEWAL_FLOOR_SECONDS),
        ),
        ("AUTH_SIGN_OUT_WAIT_SECONDS", json!(c::AUTH_SIGN_OUT_WAIT_SECONDS)),
        (
            "CATALOG_NUMBER_SET_OFFSETS",
            json!({
                "Core": c::CATALOG_NUMBER_SET_OFFSETS.core,
                "Classic": c::CATALOG_NUMBER_SET_OFFSETS.classic,
                "Classic+": c::CATALOG_NUMBER_SET_OFFSETS.classic_plus,
            }),
        ),
        ("CODE_ALPHABET", json!(c::CODE_ALPHABET)),
        (
            "CODE_ATTEMPTS_PER_PROFILE_PER_HOUR",
            json!(c::CODE_ATTEMPTS_PER_PROFILE_PER_HOUR),
        ),
        (
            "CODE_ATTEMPT_RETENTION_DAYS",
            json!(c::CODE_ATTEMPT_RETENTION_DAYS),
        ),
        (
            "CODE_ATTEMPT_WINDOW_SECONDS",
            json!(c::CODE_ATTEMPT_WINDOW_SECONDS),
        ),
        (
            "CODE_STATUS_RECHECK_FLOOR_SECONDS",
            json!(c::CODE_STATUS_RECHECK_FLOOR_SECONDS),
        ),
        ("DECK_AUTOSAVE_DEBOUNCE_MS", json!(c::DECK_AUTOSAVE_DEBOUNCE_MS)),
        (
            "DECK_AUTOSAVE_RETRY_SECONDS",
            json!(c::DECK_AUTOSAVE_RETRY_SECONDS),
        ),
        (
            "DECK_CODE_CORE_ONLY_VERSION",
            json!(c::DECK_CODE_CORE_ONLY_VERSION),
        ),
        ("DECK_CODE_MAX_INPUT_LENGTH", json!(c::DECK_CODE_MAX_INPUT_LENGTH)),
        ("DECK_CODE_VERSION", json!(c::DECK_CODE_VERSION)),
        ("DECK_NAME_MAX_LENGTH", json!(c::DECK_NAME_MAX_LENGTH)),
        ("DISCONNECT_GRACE_MS", json!(c::DISCONNECT_GRACE_MS)),
        ("DISCONNECT_GRACE_SECONDS", json!(c::DISCONNECT_GRACE_SECONDS)),
        ("GATE_SLOW_NOTICE_SECONDS", json!(c::GATE_SLOW_NOTICE_SECONDS)),
        (
            "INVITE_CODE_FORMAT",
            json!({
                "alphabet": c::INVITE_CODE_FORMAT.alphabet,
                "length": c::INVITE_CODE_FORMAT.length,
                "groupSize": c::INVITE_CODE_FORMAT.group_size,
                "separator": c::INVITE_CODE_FORMAT.separator,
                "maxInputLength": c::INVITE_CODE_FORMAT.max_input_length,
            }),
        ),
        ("INVITE_CODE_GROUP_SIZE", json!(c::INVITE_CODE_GROUP_SIZE)),
        ("INVITE_CODE_LENGTH", json!(c::INVITE_CODE_LENGTH)),
        ("INVITE_CODE_SEPARATOR", json!(c::INVITE_CODE_SEPARATOR)),
        (
            "MATCHMAKER_SWEEP_INTERVAL_SECONDS",
            json!(c::MATCHMAKER_SWEEP_INTERVAL_SECONDS),
        ),
        (
            "MATCH_ACTION_RETENTION_DAYS",
            json!(c::MATCH_ACTION_RETENTION_DAYS),
        ),
        ("MATCH_CEILING_MS", json!(c::MATCH_CEILING_MS)),
        ("MATCH_FOUND_NAV_DELAY_MS", json!(c::MATCH_FOUND_NAV_DELAY_MS)),
        ("MAX_SAVED_DECKS", json!(c::MAX_SAVED_DECKS)),
        ("MAX_SAVED_TRIOS", json!(c::MAX_SAVED_TRIOS)),
        ("MULLIGAN_CLOCK_MS", json!(c::MULLIGAN_CLOCK_MS)),
        ("PROMPT_CLOCK_MS", json!(c::PROMPT_CLOCK_MS)),
        ("PROMPT_CLOCK_SECONDS", json!(c::PROMPT_CLOCK_SECONDS)),
        (
            "RATING_WINDOW_UNCAPPED_AFTER_SECONDS",
            json!(c::RATING_WINDOW_UNCAPPED_AFTER_SECONDS),
        ),
        ("REDEMPTION_IDENTICAL_ERROR", json!(c::REDEMPTION_IDENTICAL_ERROR)),
        (
            "REDEMPTION_RESPONSE_FLOOR_MS",
            json!(c::REDEMPTION_RESPONSE_FLOOR_MS),
        ),
        ("REPLAY_LIST_PAGE", json!(c::REPLAY_LIST_PAGE)),
        ("REPLAY_REQUESTS_PER_MINUTE", json!(c::REPLAY_REQUESTS_PER_MINUTE)),
        (
            "ROOM_CODE_FORMAT",
            json!({
                "alphabet": c::ROOM_CODE_FORMAT.alphabet,
                "length": c::ROOM_CODE_FORMAT.length,
                "groupSize": c::ROOM_CODE_FORMAT.group_size,
                "separator": c::ROOM_CODE_FORMAT.separator,
                "maxInputLength": c::ROOM_CODE_FORMAT.max_input_length,
            }),
        ),
        ("ROOM_CODE_LENGTH", json!(c::ROOM_CODE_LENGTH)),
        ("SERIES_MAX_GAMES", json!(c::SERIES_MAX_GAMES)),
        ("SERIES_PICK_SECONDS", json!(c::SERIES_PICK_SECONDS)),
        ("SERIES_POLL_SECONDS", json!(c::SERIES_POLL_SECONDS)),
        ("SERIES_WINS_NEEDED", json!(c::SERIES_WINS_NEEDED)),
        (
            "TRIO_CODE_CORE_ONLY_VERSION",
            json!(c::TRIO_CODE_CORE_ONLY_VERSION),
        ),
        ("TRIO_CODE_MAX_INPUT_LENGTH", json!(c::TRIO_CODE_MAX_INPUT_LENGTH)),
        ("TRIO_CODE_VERSION", json!(c::TRIO_CODE_VERSION)),
        ("TURN_CLOCK_MS", json!(c::TURN_CLOCK_MS)),
        ("TURN_CLOCK_SECONDS", json!(c::TURN_CLOCK_SECONDS)),
    ]
}

/// The file's text: the header, then one line per constant, sorted by name.
fn render(mut constants: Vec<(&'static str, Value)>) -> String {
    constants.sort_by(|a, b| a.0.cmp(b.0));
    let mut out = String::from(HEADER);
    for (name, value) in constants {
        out.push_str(&format!("export const {name} = {value};\n"));
    }
    out
}

#[test]
fn every_name_is_listed_once() {
    let mut names: Vec<&str> = constants().iter().map(|(name, _)| *name).collect();
    let listed = names.len();
    names.sort_unstable();
    names.dedup();
    assert_eq!(names.len(), listed, "a constant is listed twice");
    assert_eq!(
        listed, 53,
        "the 50 names the client imported from apps/server/src/config.ts, ROOM_CODE_FORMAT (R767), and \
         REPLAY_LIST_PAGE and REPLAY_REQUESTS_PER_MINUTE (R768)"
    );
}

#[test]
fn the_output_is_deterministic() {
    assert_eq!(
        render(constants()),
        render(constants().into_iter().rev().collect())
    );
}

#[test]
fn export_server_config() {
    let text = render(constants());
    let current = std::fs::read_to_string(OUTPUT).unwrap_or_default();
    if current != text {
        if let Some(parent) = std::path::Path::new(OUTPUT).parent() {
            std::fs::create_dir_all(parent).unwrap_or_else(|error| panic!("{}: {error}", parent.display()));
        }
        std::fs::write(OUTPUT, &text).unwrap_or_else(|error| panic!("{OUTPUT}: {error}"));
    }
}
