// The card catalog is static data shipped with the client (§9.4), so the engine reads it from a
// registry rather than carrying it in GameState, which stays serializable. Fused and crafted
// definitions live in `state.transientDefs` and win over the registry.

import type { CardDef, CardDefs, CardType, CatalogQuery, FusedIngredient, Rarity, SetName, Tag } from "@jackioh/shared";
import { SHIPPED_SETS } from "@jackioh/shared";
import {
  GLITCH_DEF_ID,
  GLITCH_ODDS_DENOMINATOR,
  GLITCH_ODDS_PER_SYSTEM_PLAY,
  GRAPE_ODDS,
  POOL_TOKEN_TAGS,
} from "./config";
import type { Rng } from "./rng";

let registered: CardDefs = {};
let version = "0";

export function registerCatalog(defs: CardDefs, catalogVersion = "test"): void {
  registered = defs;
  version = catalogVersion;
}

export function registeredCatalog(): CardDefs {
  return registered;
}

/**
 * Tokens and cards are also reachable by their §5 index ("43", "51.1", "T-rush") — within their set,
 * since an index is unique only there (B2.2: Core's "43" and Classic's "43" are two cards).
 */
export function defByIndex(set: SetName, index: string): CardDef | undefined {
  return Object.values(registered).find((def) => def.set === set && def.index === index);
}

export function catalogVersion(): string {
  return version;
}

export type TransientHolder = { transientDefs: Readonly<Record<string, CardDef>> };

export function findDef(state: TransientHolder | null, defId: string): CardDef | undefined {
  return state?.transientDefs[defId] ?? registered[defId];
}

/** Throws when a def is missing: a card instance always has a definition. */
export function defOf(state: TransientHolder | null, defId: string): CardDef {
  const def = findDef(state, defId);
  if (def === undefined) throw new Error(`unknown defId "${defId}": register the catalog first`);
  return def;
}

// ---------------------------------------------------------------------------
// §5.1's one query function, and the cost every filter reads (R65).
// ---------------------------------------------------------------------------

/**
 * R65 outside play: "an embiggen card's printed cost is its base price and an X-cost card's is 0".
 * Every pool, filter and comparison that looks at a *definition* rather than at a played instance
 * goes through this, so #7's cost brackets, #30's highest/lowest, #94's odd costs and Recruit all
 * read one number. The in-play calculation is `mana.effectiveCost`, which starts from the instance.
 */
export function queryCost(def: CardDef): number {
  const cost = def.cost;
  if (cost === "X") return 0;
  if (typeof cost === "number") return cost;
  return cost.base;
}

/**
 * §5.1's `catalog.query({type, cost, costRange, tags, notTags, rarity, set, excludeDefId})`, plus the
 * identity fields a card needs to name a pool by hand. Every field is a narrowing filter, and `{}` is
 * every non-token card of every set (R380).
 */
export type CatalogQueryArgs = CatalogQuery & {
  /** A catalog id, or several, for a pool a script names card by card or builds from ids it holds. */
  defId?: string | string[];
  /** §5.1: `true` asks for tokens only, `false` forbids them (the default already does). */
  token?: boolean;
};

function asList<T>(value: T | readonly T[] | undefined): readonly T[] {
  if (value === undefined) return [];
  return Array.isArray(value) ? value : [value as T];
}

/**
 * §5.1: "Random pools never include Token-tagged cards … unless the card names the pool itself".
 * A query names the token pool by asking for the Token tag or rarity, by setting `token: true`, or
 * by naming its members outright through `defId`. `withTokens` (R382) lets tokens in beside cards.
 */
function asksForTokens(args: CatalogQueryArgs): boolean {
  if (args.token !== undefined) return args.token;
  if (args.withTokens === true) return true;
  if (args.tags?.includes("Token") === true) return true;
  if (asList<Rarity>(args.rarity).includes("Token")) return true;
  return asList(args.defId).length > 0;
}

function isToken(def: CardDef): boolean {
  return def.token || def.tags.includes("Token");
}

/**
 * R382: a pool named by one of `POOL_TOKEN_TAGS` (a Fruit pool) holds that tag's tokens too — the
 * five Grapes are Tokens "that can be generated by any Fruit card". No other pool reaches them.
 */
function tagPoolTakesToken(args: CatalogQueryArgs, def: CardDef): boolean {
  const asked = args.tags ?? [];
  return asked.some((tag: Tag) => POOL_TOKEN_TAGS.includes(tag) && def.tags.includes(tag));
}

function matchesQuery(def: CardDef, args: CatalogQueryArgs, tokensAllowed: boolean): boolean {
  // R674: Glitch is in no pool, not even one that takes every token; only R673's roll makes one.
  if (def.id === GLITCH_DEF_ID && !asList(args.defId).includes(def.id)) return false;
  if (!tokensAllowed && isToken(def) && !tagPoolTakesToken(args, def)) return false;
  if (args.token !== undefined && isToken(def) !== args.token) return false;

  const types = asList<CardType>(args.type);
  if (types.length > 0 && !types.includes(def.type)) return false;
  const rarities = asList<Rarity>(args.rarity);
  if (rarities.length > 0 && !rarities.includes(def.rarity)) return false;
  const sets = asList<SetName>(args.set);
  if (sets.length > 0 && !sets.includes(def.set)) return false;

  const defIds = asList(args.defId);
  if (defIds.length > 0 && !defIds.includes(def.id)) return false;
  // R387, §5.1: a random pool never offers the card that generated it, named by its id.
  if (asList(args.excludeDefId).includes(def.id)) return false;

  // `tags` means "has every listed tag"; `notTags` means "has none of them".
  if (args.tags !== undefined && !args.tags.every((tag) => def.tags.includes(tag))) return false;
  if (args.notTags !== undefined && args.notTags.some((tag) => def.tags.includes(tag))) return false;

  // R65: costs are read out of play, so X counts as 0 and an embiggen card as its base price.
  const cost = queryCost(def);
  if (args.cost !== undefined && cost !== args.cost) return false;
  if (args.costRange?.min !== undefined && cost < args.costRange.min) return false;
  if (args.costRange?.max !== undefined && cost > args.costRange.max) return false;
  return true;
}

/**
 * R77, R102: the catalog ids a definition stands for when it generates — its own id, or, for a fused
 * definition (R179's `t-<n>:<a>+<b>`), every ingredient's, its fused ingredients' included, so a
 * fused card never generates any card it was made from (B4.1 rule 2). A crafted definition with no
 * ingredients stands for itself, which no pool can reach anyway.
 */
export function selfDefIds(defId: string): string[] {
  const ingredients = fusedIdParts(defId);
  if (ingredients === null) return [defId];
  return ingredients.flatMap((id) => selfDefIds(id));
}

/**
 * R179: the ingredient ids a fused id (`t-<n>:<a>+<b>`, a fused ingredient in parentheses) names,
 * split at the top-level `+` signs; null for any other id. `fuse.fusedIngredients` is its reader
 * with R77's two-ingredient minimum. R469's Radiant mark (`<a>*`) is dropped here, since what a
 * card stands for is the definition, whichever face went in; R468's digest id (`t-<n>:#<hex>`)
 * reads its list from the definitions this process has seen minted or entered
 * (`registerFusedIngredients`).
 */
export function fusedIdParts(defId: string): string[] | null {
  const specs = fusedIdSpecs(defId);
  return specs === null ? null : specs.map((spec) => spec.defId);
}

/** R468: what follows `t-<n>:` in a digest id, which names its ingredients by a hash of them alone. */
export const FUSED_DIGEST_MARK = "#";

/** R469: the mark an ingredient that went in on its Radiant face carries in a readable fused id. */
export const RADIANT_INGREDIENT_MARK = "*";

/**
 * R468: the ingredient lists of the digest ids this process knows — a process-wide table like the
 * script registry (`scripts.ts`), and right for every match in it for the same reason: a digest
 * names one list (R179), so an entry is true whoever wrote it. `subsystems/fuse` writes it as it
 * mints a definition and again for every transient definition of a state it enters, so a state
 * that came through JSON into a fresh process reads its own digest ids.
 */
const digestIngredients = new Map<string, FusedIngredient[]>();

/** R468: record what a digest-named fused definition was made of (see `digestIngredients`). */
export function registerFusedIngredients(defId: string, ingredients: readonly FusedIngredient[]): void {
  if (!isDigestId(defId) || digestIngredients.has(defId)) return;
  digestIngredients.set(defId, ingredients.map(copySpec));
}

/** R468: whether a fused id is a digest of its ingredients rather than their names. */
export function isDigestId(defId: string): boolean {
  const head = /^t-\d+:/.exec(defId);
  return head !== null && defId[head[0].length] === FUSED_DIGEST_MARK;
}

function copySpec(entry: FusedIngredient): FusedIngredient {
  return { defId: entry.defId, ...(entry.radiant === true ? { radiant: true as const } : {}) };
}

/**
 * R179, R468, R469: the ingredients a fused id names, in order, each with its Radiant mark; null for
 * an id no Fuse minted, or a digest this process has not been told. A readable id is split at its
 * top-level `+` signs (a fused ingredient in parentheses, a Radiant one followed by `*`); a digest
 * id is looked up.
 */
export function fusedIdSpecs(defId: string): FusedIngredient[] | null {
  const head = /^t-\d+:/.exec(defId);
  if (head === null) return null;
  if (isDigestId(defId)) {
    const known = digestIngredients.get(defId);
    return known === undefined ? null : known.map(copySpec);
  }
  const specs: FusedIngredient[] = [];
  let depth = 0;
  let start = head[0].length;
  for (let at = start; at <= defId.length; at += 1) {
    const char = defId[at];
    if (char === "(") depth += 1;
    else if (char === ")") depth -= 1;
    else if ((char === "+" && depth === 0) || at === defId.length) {
      let part = defId.slice(start, at);
      const radiant = part.endsWith(RADIANT_INGREDIENT_MARK);
      if (radiant) part = part.slice(0, -RADIANT_INGREDIENT_MARK.length);
      const name = part.startsWith("(") && part.endsWith(")") ? part.slice(1, -1) : part;
      specs.push({ defId: name, ...(radiant ? { radiant: true as const } : {}) });
      start = at + 1;
    }
  }
  return specs.every((spec) => spec.defId.length > 0) ? specs : null;
}

/**
 * §5.1, R387: "a random pool never includes the generating card's own definition". The running
 * card's ids (`selfDefIds`) are ADDED to whatever the caller already excludes, never put in its
 * place: a card whose text names its own exclusion keeps it when the card running that text is a
 * fused one (R77, R102).
 */
export function excludingDefId(args: CatalogQueryArgs, defId: string | undefined): CatalogQueryArgs {
  if (defId === undefined) return args;
  const already = asList(args.excludeDefId);
  const added = selfDefIds(defId).filter((id) => !already.includes(id));
  return added.length === 0 ? args : { ...args, excludeDefId: [...already, ...added] };
}

/** §5's index as a number, so "2" sorts before "10" and a token index ("T-rush") sorts last. */
function indexRank(index: string): number {
  const parsed = Number.parseFloat(index);
  return Number.isFinite(parsed) ? parsed : Number.POSITIVE_INFINITY;
}

/** B2.2: a set's place in the catalog order; a set the order does not name sorts last. */
function setRank(set: SetName): number {
  const at = (SHIPPED_SETS as readonly SetName[]).indexOf(set);
  return at === -1 ? SHIPPED_SETS.length : at;
}

/**
 * §5.1's single source of random pools and Discover: every definition the filters allow, set by set
 * (catalog order, `SHIPPED_SETS`: Core, Classic, Classic+), each set in §5 index order. The order is a strict total order (set, index as a
 * number, then the index itself, then the unique catalog id), so it never depends on the order the
 * registry happened to hand the defs over and a seeded `rng.pick`/`rng.shuffle` over the result
 * replays identically (R58, R60, §9.3).
 *
 * Only the registered catalog is searched: fused and crafted definitions live on the instance's
 * `transientDefs` and are not catalog cards, so no pool can generate one.
 */
export function query(args: CatalogQueryArgs = {}): CardDef[] {
  const tokensAllowed = asksForTokens(args);
  return Object.values(registered)
    .filter((def) => matchesQuery(def, args, tokensAllowed))
    .sort((a, b) => {
      const setA = setRank(a.set);
      const setB = setRank(b.set);
      if (setA !== setB) return setA < setB ? -1 : 1;
      // Compared, not subtracted: two token indexes are both +Infinity, and `Infinity - Infinity`
      // is NaN, which `sort` reads as 0 while `NaN !== 0` is true — so subtracting returned early
      // with NaN and skipped both tie-breaks, leaving the tokens in registry insertion order and
      // breaking the total order this function promises (R58, R60, §9.3).
      const rankA = indexRank(a.index);
      const rankB = indexRank(b.index);
      if (rankA !== rankB) return rankA < rankB ? -1 : 1;
      if (a.index !== b.index) return a.index < b.index ? -1 : 1;
      return a.id < b.id ? -1 : 1;
    });
}

// ---------------------------------------------------------------------------
// Grapes (C+ #65, #66; R382)
// ---------------------------------------------------------------------------

/**
 * R382, BUILD §2: one Grape, rolled by `GRAPE_ODDS` — one draw of the match rng over the percents'
 * sum, walked in the table's order. `lucky` extra rolls (§6.1 Lucky X) keep the best, and the best is
 * the later entry, since the table runs from worst to best (Rotten < Normal < Large < Golden < Mythic).
 * Returns the Grape's def id.
 */
export function rollGrape(rng: Rng, lucky = 0): string {
  const roll = (): number => {
    const total = GRAPE_ODDS.reduce((sum, grape) => sum + grape.percent, 0);
    let at = rng.int(total);
    for (let i = 0; i < GRAPE_ODDS.length; i += 1) {
      const grape = GRAPE_ODDS[i];
      if (grape === undefined) break;
      if (at < grape.percent) return i;
      at -= grape.percent;
    }
    return GRAPE_ODDS.length - 1;
  };
  const extra = Math.max(0, Math.trunc(lucky));
  const index = extra === 0 ? roll() : rng.lucky(extra, roll, (a, b) => Math.max(a, b));
  const grape = GRAPE_ODDS[index] ?? GRAPE_ODDS[GRAPE_ODDS.length - 1];
  return grape?.defId ?? "";
}

/** The def ids `GRAPE_ODDS` rolls: a pool pick naming one of these is re-rolled (R382). */
const GRAPE_DEF_IDS: ReadonlySet<string> = new Set(GRAPE_ODDS.map((grape) => grape.defId));

/**
 * R382: draw the generated card from a pool — as `rng.pick` today, except that a Grape pick is
 * rolled again on `GRAPE_ODDS` and the Grape that roll names is generated instead, so the Grape
 * rarity pool persists across every kind of Grape generation. One extra rng draw, only when a
 * Grape was picked; every other pick draws exactly as before. A caller generating into a hand or a
 * deck passes the state as `glitch`, and the pick may then become Glitch (R673).
 */
export function pickGenerated(rng: Rng, pool: readonly CardDef[], glitch?: GlitchOdds): CardDef | undefined {
  const picked = rng.pick(pool);
  const def = picked === undefined || !GRAPE_DEF_IDS.has(picked.id) ? picked : (findDef(null, rollGrape(rng)) ?? picked);
  return def === undefined || glitch === undefined ? def : glitchOrNot(rng, def, glitch);
}

/** R673: what the Glitch roll reads — the match's count of "… in the System" plays. */
export type GlitchOdds = { readonly systemPlays?: number };

/**
 * R673: after a card is picked for a hand or a deck, n/10000 that it is Glitch instead, n the match's
 * System plays. One rng draw, and only when n is above 0, so a match no System card was played in
 * draws exactly as before; a catalog without Glitch keeps the pick.
 */
export function glitchOrNot(rng: Rng, def: CardDef, glitch: GlitchOdds): CardDef {
  const plays = glitch.systemPlays ?? 0;
  if (plays <= 0) return def;
  const roll = rng.int(GLITCH_ODDS_DENOMINATOR);
  if (roll >= plays * GLITCH_ODDS_PER_SYSTEM_PLAY) return def;
  return findDef(null, GLITCH_DEF_ID) ?? def;
}
