// Every rules constant lives here (BUILD §2). The engine never hard-codes these numbers.
// Rows SPEC §11 marks "decide" (R1, R2, R4, R5, R14, R26, R39) are flipped here in one line.

import type { Tag } from "@jackioh/shared";

/** §2.6 */
export const DECK_SIZE = 20;
/** §2.6, §9.4 */
export const MAX_COPIES = 1;
/** §2.3 */
export const MAX_MANA = 4;
/** §2 */
export const HERO_HEALTH = 30;

/**
 * BUILD M1-T1 (`createGame` yields `turn = 0`): the turn number §2.1's setup runs at. Setup is no
 * player's turn — p1 takes the first turn after it (§2.1 step 5) — so nothing played during it
 * belongs to a turn of its controller's (R155, R241).
 */
export const SETUP_TURN = 0;
/**
 * §2.5, R2, R389 (patch v0.2.0, docs/classic-sets.md B4.3): the cap counts player-turns, so 60 means
 * 30 each. Two 20-card decks that do nothing fatigue out at player-turn 48 (§2.4, R3), so the cap is a
 * backstop for games that heal, gain Armor or refill a deck, and fatigue is a long game's usual end.
 */
export const TURN_CAP_PLAYER_TURNS = 60;
/** §2.4, R4 (decide): a card drawn or added to a full hand is burned. */
export const HAND_CAP = 10;

/** §2.1: indexed by seat; the Nth seat (1-based) draws N+2. */
export const OPENING_DRAW: readonly number[] = [3, 4];

/**
 * §2.1, R244: indexed by seat like `OPENING_DRAW`, the copies of The Coin each seat is dealt once both
 * mulligans are answered. Hearthstone's rule: the player going second gets one, the first none.
 */
export const OPENING_COINS: readonly number[] = [0, 1];
/** §7, R245: the catalog id of The Coin, the one token a rule deals rather than a card. */
export const COIN_DEF_ID = "core-t-coin";

/**
 * R382: a pool named by one of these tags also holds that tag's tokens. The five Grapes are Fruit
 * Tokens "that can be generated by any Fruit card", and appear in no other pool but one that takes
 * every token (`withTokens`).
 */
export const POOL_TOKEN_TAGS: readonly Tag[] = ["Fruit"];

/** §3 */
export const UNIT_ZONES = 5;
/** §3 */
export const BACKROW_ZONES = 5;
/** §3.1: "midlane", the middle lane of UNIT_ZONES — Classic #22 Mid Runner's lane 3 (SPEC §8.6 row 22, BUILD §2). */
export const MID_LANE = 3;
/**
 * Classic #18 Glitch in the System's number choice (SPEC §8.6 row 18, BUILD §2): the numbers 0 to 10,
 * the same eleven options every time, so the options reveal nothing about any hand or deck.
 */
export const GLITCH_NUMBERS: readonly number[] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

/** R5 (decide): any unit may attack any enemy unit or hero, subject to Taunt. */
export const LANE_RESTRICTED_ATTACKS: boolean = false;
/** R1 (decide): Cry fires only when played from hand or cast by an effect. */
export const CRY_ON_PLAY_ONLY: boolean = true;
/** R14 (decide): units and backrow form two independent rings. */
export const ROTATION_RING = "two-rings" as const;
/** R26 (decide): Genn's Greed exiles odd current-cost cards. */
export const GENN_GREED_EXILES = "odd" as const;
/** R39 (decide): Felinor Fiender = printed stats plus the sum of your Felinors. */
export const FIENDER_STATS_MODE = "printed-plus-sum" as const;

/** R3: the Nth draw from an empty library deals N damage. */
export const FATIGUE_DAMAGE = (n: number): number => n;

/** §2.5, R36: offers allowed per player per turn. */
export const DRAW_OFFERS_PER_TURN = 1;
/** §2.5, R36: a declined offer blocks that player for this many of their turns. */
export const DRAW_OFFER_BLOCK_TURNS = 3;
/**
 * §2.5, R79: the most prompts one `timeout` answers for the active player. A chain of prompts is a
 * handful (KY's Private Tutor asks three times), after which the turn ends. This only bounds a card
 * that would keep asking, so one `timeout` always returns: if a prompt is still open after this many
 * answers, the timeout stops there with the turn still running, and the next expiry carries on. No
 * Core card can reach it.
 */
export const TIMEOUT_ANSWER_CAP = 500;

/** R28 */
export const CALL_TO_CHAOS_CHAIN_CAP = 20;
/** R58: cast-on-draw cards one draw may cast before the next one goes to hand uncast. */
export const CAST_ON_DRAW_CHAIN_CAP = 20;
/** §8 #73: largest single damage instance a hero with Anti-oneshot Armor takes. */
export const ANTI_ONESHOT_CAP = { base: 5, radiant: 3 } as const;
/**
 * §8 #84 Going Long: the Armor it gives its controller's hero (§4.4 step 2), by face and by which
 * price was paid — "Armor 2. Paid (4): Armor 4", radiant "Armor 4. Paid (4): Armor 8" (patch
 * v0.1.1). `paid` is the printed cost 2, `embiggen` the embiggen price 4 (R81 records which on the
 * instance).
 */
export const HERO_ARMOR = {
  base: { paid: 2, embiggen: 4 },
  radiant: { paid: 4, embiggen: 8 },
} as const;
/**
 * §8 #38 Quickstriker, R281: the multiple of X each granted Combo deals to the enemy hero, by the
 * granting card's face — "Combo X: deal X damage", radiant "deal 2X damage", one hit either way.
 */
export const QUICKSTRIKER_COMBO_MULTIPLE = { base: 1, radiant: 2 } as const;

/**
 * R21: Plastic Surgery and Zao Gao draw from this pool; a unit never gets a keyword it has. R346:
 * patch v0.1.1 added Pierce, at the end.
 */
export const RANDOM_KEYWORD_POOL = [
  "Taunt",
  "Armor 1",
  "Rush",
  "Charge",
  "First Strike",
  "Poisonous",
  "Lifesteal",
  "Reborn",
  "Divine Shield",
  "Trample",
  "Cleave",
  "Pierce",
] as const;

/**
 * R349: a Unit that prints no Radiant form (the Ghoul Token) is, made Radiant, its base face with
 * its attack and health multiplied by this — a summon's X/X included (§7).
 */
export const RADIANT_FALLBACK_FACTOR = 2;

/**
 * R348: the least X a player may choose for an X-cost card whose X is theirs to choose (#24, #74).
 * Heroic Power's X is its power's and never chosen (R43), so this does not reach it.
 */
export const MIN_CHOSEN_X = 1;

/** R25: KY's Math Equation; the index clamps at 11. */
export const FIB = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89] as const;

export function fib(index: number): number {
  const clamped = Math.min(Math.max(Math.trunc(index), 0), FIB.length - 1);
  return FIB[clamped] ?? 0;
}

/** R80: a library holds at most this many cards. */
export const LIBRARY_CAP = 60;

/** §6.3 */
export const FUSE_COST_CAP = 4;
/** R9: replacements are drawn before the returned cards are shuffled back. */
export const MULLIGAN_ORDER = "draw-then-shuffle" as const;
/** §10.7: the random policy ends its turn with this probability when other actions exist. */
export const AI_END_TURN_PROBABILITY = 0.1;
/** R90: the most choice combinations `legalActions` enumerates for one play. */
export const MAX_CHOICE_COMBINATIONS = 64;
/** §9.3: how many answered nonces the state remembers for dedupe. */
export const NONCE_HISTORY = 64;

/** §2.4: the draws each start of turn makes before any handicap (R183). */
export const DRAWS_PER_TURN = 1;

/**
 * §9.9, R180: the resources one seat plays with. Every field is a non-negative integer. The type
 * lives here because `config.ts` imports nothing; `state.ts` stores it on a `PlayerState`.
 */
export type Handicap = {
  /** R184: exactly how many cards `createGame` requires in this seat's deck. */
  readonly deckSize: number;
  /** R181: crystals added to the turns-started count before the cap. */
  readonly manaBonus: number;
  /** R181: the most max mana a refresh gives, before persistent modifiers. */
  readonly manaCap: number;
  /** R182: cards added to §2.1's opening draw. */
  readonly extraOpeningCards: number;
  /** R183: separate draws after DRAWS_PER_TURN at each start of turn. */
  readonly extraDrawsPerTurn: number;
  /**
   * R290: the health this seat's hero starts the game with, in place of HERO_HEALTH. Absent means
   * HERO_HEALTH, which is why the three practice tiers never set it and hash exactly as before the
   * field existed. Only the tutorial's handicap (`AI_TUTORIAL`) sets it, and only lower.
   */
  readonly heroHealth?: number;
};

/** R180: this spec's own resources. A seat with no handicap plays with these. */
export const HUMAN_HANDICAP: Handicap = {
  deckSize: DECK_SIZE,
  manaBonus: 0,
  manaCap: MAX_MANA,
  extraOpeningCards: 0,
  extraDrawsPerTurn: 0,
};

/** §9.9: the three practice tiers. */
export type Difficulty = "easy" | "medium" | "hard";
export const DIFFICULTIES: readonly Difficulty[] = ["easy", "medium", "hard"];

/**
 * §9.9's table (R180): the AI seat's handicap per tier. The AI itself is identical at every tier;
 * only these resources differ. Easy is a human's resources exactly, so an Easy game stores no
 * handicap and hashes like any other game.
 */
export const AI_DIFFICULTY: Readonly<Record<Difficulty, Handicap>> = {
  easy: HUMAN_HANDICAP,
  medium: { deckSize: 25, manaBonus: 1, manaCap: 5, extraOpeningCards: 1, extraDrawsPerTurn: 0 },
  hard: { deckSize: 30, manaBonus: 1, manaCap: 7, extraOpeningCards: 1, extraDrawsPerTurn: 1 },
};

/**
 * §9.10, R290: the tutorial opponent's handicap, the one below Easy. It is a handicap like the
 * three tiers (R180) and lowers the AI seat's resources instead of raising them: a 12-card deck
 * (each lesson's own list, R291, so it runs out and fatigues sooner), at most 3 mana crystals, and
 * a hero that starts at 20 health. The AI's search, evaluation and budget are the ones every tier
 * plays with. It is not in `DIFFICULTIES`: nobody picks it, the tutorial deals it.
 */
export const AI_TUTORIAL: Handicap = {
  deckSize: 12,
  manaBonus: 0,
  manaCap: 3,
  extraOpeningCards: 0,
  extraDrawsPerTurn: 0,
  heroHealth: 20,
};

// ---------------------------------------------------------------------------------------------
// Patch v0.2.0 (docs/classic-sets.md B3–B5). Every number the new rules state, by workstream.
// ---------------------------------------------------------------------------------------------

// ---- v0.2.0 constants: instance data (B3.3 Brittle, B3.4 Degrade and Upgrade) ----

/**
 * B3.3, R385 (the designer's B9 #41: t + 2): a Brittle count started on player-turn t first ticks at
 * the first start of its controller's turn numbered t + this or later, so the card lives through the
 * rest of the turn it got the count on and a whole turn of the other player's first.
 */
export const BRITTLE_FIRST_TICK_TURNS = 2;
/** B3.3 rule 2: how much one start-of-turn tick takes off a Brittle count. */
export const BRITTLE_TICK = 1;
/**
 * B3.3 rule 5, B3.4: how far one Degrade or Upgrade moves a numbered keyword, a Brittle count or an
 * X-cost card's X — one step of "one X on the card gets 1 worse / better".
 */
export const TUNE_X_STEP = 1;
/** B3.4 rule 3: how far one Degrade or Upgrade moves a card's cost (`costMod`). */
export const TUNE_COST_STEP = 1;
/** B3.4 rule 3, the designer's "Increase cost by (1) (up to 4)": a Degrade never lifts a cost above this. */
export const TUNE_COST_CAP = 4;
/** B3.4 rule 3: an Upgrade never takes a cost below this. */
export const TUNE_COST_FLOOR = 0;
/**
 * B3.4 rule 3, the designer's "reduces the stats … by a total of 4": the split one stats change
 * rolls, k in 0 to this to attack and the rest to health.
 */
export const TUNE_STAT_TOTAL = 4;
/** B3.4 rule 3: "attack floors at 0". */
export const TUNE_ATTACK_FLOOR = 0;
/** B3.4 rule 3, the designer's "not below 1 health": a Degrade never takes current health below this. */
export const TUNE_HEALTH_FLOOR = 1;
/**
 * B3.4 rule 3: the keywords a Degrade never removes, because losing them would help the card —
 * "Cannot be in Defense Position" is a static flag (§8 #65.1), not a keyword, so it is never offered.
 */
export const TUNE_HARMFUL_KEYWORDS = ["Can't attack", "Brittle"] as const;
/**
 * B3.4 rule 5: a declared number's default step — 1 for a number up to `small.upTo`, 2 up to
 * `medium.upTo`, and above that a quarter of it, rounded (`largeDivisor`), never less than 1.
 */
export const PARAM_DEFAULT_STEP = {
  small: { upTo: 5, step: 1 },
  medium: { upTo: 12, step: 2 },
  largeDivisor: 4,
} as const;
/**
 * B3.4 rule 5, R386: "an amount never drops below 1" — a tuned number's floor: a declared number that
 * names no `min`, an X, a numbered keyword (Activate X, Tribute X, Armor …) and a Brittle count a
 * Degrade lowers.
 */
export const TUNE_MIN_AMOUNT = 1;

// ---- v0.2.0 constants: field (B3.1 Animated, E20, E21, E22) ----

// ---- v0.2.0 constants: play pipeline (E1, E11, E12, E15) ----

// play pipeline B (E11, E12, E15; R452–R455). A cast's X is its caster's current mana, at least
// MIN_CHOSEN_X (R348, R453); the other numbers of these rules are cards' own (`params`).

/**
 * B5 E11, R454: the fewest Plague Tokens a play from the graveyard that pays with tokens spends
 * (Classic #74 Corpse Plantation: "each such play spends at least 1 token").
 */
export const MIN_PLAGUE_PAYMENT = 1;
/** B5 E11, R454: what one Plague Token spent as mana pays of a price ("each token pays (1)"). */
export const PLAGUE_TOKEN_MANA = 1;
/**
 * B5 E12, R452: how many casts one random cast and every cast made inside its resolution may make in
 * all (Classic+ #47 Jogg's Box, #38.1 Solarius-Prime), as R28 caps a Call to Chaos chain and R58 a
 * cast-on-draw chain: a random cast whose casts cast at random cannot multiply without end.
 */
export const RANDOM_CAST_CHAIN_CAP = 20;

/**
 * B5 E4, R451: the tags whose cards a player's "last face-up card played" record passes over — the
 * AI generated cards (B8), so two Autocompletes can't copy each other for ever.
 */
export const LAST_FACE_UP_SKIPPED_TAGS: readonly Tag[] = ["AI"];

// ---- v0.2.0 constants: activate and turn (B3.2, B4.3, E3, E10) ----

/**
 * B3.2 rule 7, R384: "Activate ♾️" is any number of uses per card per turn, bounded here so a game
 * still ends (a fuzz game's random policy may keep activating). Every ♾️ card in the sets is bounded
 * by a resource too (units to Tribute, Plague Tokens to consume).
 */
export const ACTIVATE_UNLIMITED_CAP = 100;

// ---- v0.2.0 constants: damage and combat (E5, E6, E35, E37) ----

/**
 * B5 E5, E9, R460: how many times one hit may be redirected before it lands where it stands. Each
 * Trap that redirects is spent as it fires, so two players' backrows bound a chain of Traps by
 * themselves; the cap is for a Field Trap, which stays and could send a hit back and forth for ever.
 */
export const DAMAGE_REDIRECT_CAP = 2 * BACKROW_ZONES;

/** B5 E35: the mark a Berserk unit carries in both views (R437's reusable mark), and its colour key. */
export const BERSERK_MARK = { mark: "berserk", color: "red" } as const;

// ---- v0.2.0 constants: prompts and generation (E18, E19, E23–E25) ----

// generation (E19, E23–E25), below A6a's prompts constants:
/**
 * R468: the longest ingredient list a fused id spells out (`t-<n>:<a>+<b>`, R179), in characters of
 * the part after `t-<n>:`. A longer one — a card fused onto again and again, Classic+ #74 — is named
 * by a digest of that list instead (`t-<n>:#<hex>`), and its definition keeps the whole list.
 */
export const FUSED_ID_CAP = 120;
/** R471: the placement multiplier of a card that doubles nothing (the Plague Tokens placed as written). */
export const PLAGUE_MULTIPLIER_NONE = 1;

// ---- v0.2.0 constants: Core patches (R423, R426–R431) ----
/**
 * R423: how many different effects a Radiant Call to Chaos rolls from its list — "Three different
 * random effects, resolved in the order listed" (Core #95's Radiant face since patch v0.2.0, and
 * Classic+ #73's). The base face rolls one.
 */
export const CALL_TO_CHAOS_RADIANT_EFFECTS = 3;

// ---- v0.2.0 constants: Classic+ cards #40–#78 and the AI cards (the cards-plus-d workstream) ----

// Classic+ #42 KY's Test (SPEC §8.7, R420, BUILD §2).
/** R420: the three difficulties, in the order the first prompt offers them. */
export const KY_TEST_DIFFICULTIES = ["Easy", "Medium", "Hard"] as const;
/** R420: the options every problem shows, exactly one of them its answer. */
export const KY_TEST_OPTIONS = 4;
/** R420: the floor of bank problems per difficulty (the bank test's floor, in `packages/cards`). */
export const KY_TEST_MIN_PROBLEMS = 30;
/** R420: an Easy problem is a + b with each addend in this range, inclusive. */
export const KY_TEST_EASY_ADDENDS = { min: 10, max: 99 } as const;
/** R420: an Easy problem's three wrong sums are a + b moved by three different ones of these. */
export const KY_TEST_EASY_MISSES: readonly number[] = [1, -1, 2, -2, 10, -10];

/**
 * R420: one reward a difficulty may roll (BUILD §2 `KY_TEST_REWARDS`). `label` is the reward as the
 * card's text prints it, which the first prompt shows beside its difficulty. A reward is cards: the
 * one card the text names (`defId`: The Coin, KY's Gift), or random cards from a pool of non-token
 * cards of every set (`pool`, R380; never KY's Test itself, R387; repeats allowed, R60). `count` is
 * how many, or `"fill"`: as many as the hand has room for under `HAND_CAP`. `costOverride` is the cost
 * the text sets each card to ("which costs (0)", "which cost (1)").
 */
export type KyTestReward = {
  readonly id: string;
  readonly label: string;
  readonly defId?: string;
  readonly pool?: { readonly tags?: Tag[]; readonly rarity?: "Legendary"; readonly cost?: number };
  readonly count: number | "fill";
  readonly costOverride?: number;
};

/** R420: each difficulty's list of rewards, in the order the text prints them; one is rolled per difficulty. */
export const KY_TEST_REWARDS: { readonly [D in (typeof KY_TEST_DIFFICULTIES)[number]]: readonly KyTestReward[] } = {
  Easy: [
    { id: "coins", label: "3 The Coins", defId: "core-t-coin", count: 3 },
    { id: "ky", label: "a random (2) Cost KY card", pool: { tags: ["KY"], cost: 2 }, count: 1 },
    { id: "legendary", label: "a random Legendary card, which costs (0)", pool: { rarity: "Legendary" }, count: 1, costOverride: 0 },
    { id: "books", label: "2 random Books", pool: { tags: ["Book"] }, count: 2 },
  ],
  Medium: [
    { id: "fours", label: "2 random (4) Cost cards, which cost (1)", pool: { cost: 4 }, count: 2, costOverride: 1 },
    { id: "books", label: "5 random Books", pool: { tags: ["Book"] }, count: 5 },
    { id: "ky", label: "5 random KY cards", pool: { tags: ["KY"] }, count: 5 },
    { id: "fill", label: "fill your hand with random Books", pool: { tags: ["Book"] }, count: "fill" },
  ],
  Hard: [{ id: "gift", label: "KY's Gift, which costs (0)", defId: "classicplus-042-1", count: 1, costOverride: 0 }],
};

// Classic+ #62 KY's Papaya (SPEC §8.7, R422, BUILD §2).
/** R422: the rows of the curve's grid, y 0 (your backrow) to 3 (their backrow). */
export const PAPAYA_ROWS = 4;
/** R422: the most cells a curve is drawn through — four fix a cubic, the highest degree it may have. */
export const PAPAYA_MAX_CELLS = 4;

// Classic+ #65 Two Grapes and #66 Vine of Grapes (SPEC §8.7, R382, BUILD §2).
/**
 * R382: each Grape's chance in percent, in Lucky's order from worst to best (Rotten < Normal < Large <
 * Golden < Mythic): a roll with Lucky keeps the later of its two.
 */
export const GRAPE_ODDS: readonly { readonly defId: string; readonly percent: number }[] = [
  { defId: "classicplus-065-1", percent: 12 },
  { defId: "classicplus-065-2", percent: 60 },
  { defId: "classicplus-065-3", percent: 20 },
  { defId: "classicplus-065-4", percent: 7 },
  { defId: "classicplus-065-5", percent: 1 },
];

// Classic+ #73 Call to Chaos (Classic+ Edition) (SPEC §8.7 row 73, R423): its table's numbers.
/** §8.7 row 73 entry 1: "Add 5 random Fruits to your hand". */
export const CHAOS_PLUS_FRUITS = 5;
/** §8.7 row 73 entry 2: "Add 3 random Books to your hand". */
export const CHAOS_PLUS_BOOKS = 3;
/** §8.7 row 73 entry 4: "Add 3 random Classic cards to your hand". */
export const CHAOS_PLUS_CLASSIC_CARDS = 3;
/** §8.7 row 73 entries 1, 2, 4 and 9: the added and the replacing cards "cost (0)" (`costOverride`). */
export const CHAOS_PLUS_COST = 0;
/** §8.7 row 73 entry 5: "Upgrade every card in your hand and deck twice". */
export const CHAOS_PLUS_UPGRADES = 2;
/** §8.7 row 73 entry 7: "Degrade every card on your opponent's field and in their hand three times". */
export const CHAOS_PLUS_DEGRADES = 3;

// T-AI-4 Chain of Thought (SPEC §8.7, BUILD §2).
/** T-AI-4: the repeats after the first draw, a termination bound: five draws at most. */
export const CHAIN_OF_THOUGHT_REPEATS = 4;
