// GENERATED by `cargo test -p jackioh-engine --test export_config` from crates/engine/src/config.rs
// (docs/v0.3.0/SURFACE.md §5.1). Do not edit: CI regenerates it and fails on a diff. The web imports
// it as `@jackioh/engine/config` (apps/web/vite.config.ts, tsconfig.json).

import type { Difficulty } from "./generated/Difficulty.ts";
import type { Handicap } from "./generated/Handicap.ts";

export type { Difficulty, Handicap };

export const AI_DIFFICULTY: Readonly<Record<Difficulty, Handicap>> = {"easy":{"deckSize":20,"manaBonus":0,"manaCap":4,"extraOpeningCards":0,"extraDrawsPerTurn":0},"medium":{"deckSize":25,"manaBonus":1,"manaCap":5,"extraOpeningCards":1,"extraDrawsPerTurn":0},"hard":{"deckSize":30,"manaBonus":1,"manaCap":7,"extraOpeningCards":1,"extraDrawsPerTurn":1}};
export const AI_TUTORIAL: Handicap = {"deckSize":12,"manaBonus":0,"manaCap":3,"extraOpeningCards":0,"extraDrawsPerTurn":0,"heroHealth":20};
export const COIN_DEF_ID = "core-t-coin";
export const DECK_SIZE = 20;
export const DIFFICULTIES: readonly Difficulty[] = ["easy","medium","hard"];
export const DRAWS_PER_TURN = 1;
export const GLITCH_DEF_ID = "classic-t-glitch";
export const HERO_HEALTH = 30;
export const HUMAN_HANDICAP: Handicap = {"deckSize":20,"manaBonus":0,"manaCap":4,"extraOpeningCards":0,"extraDrawsPerTurn":0};
export const LIBRARY_CAP = 60;
export const MAX_COPIES = 1;
export const MAX_MANA = 4;
export const REPLAY_CHECKPOINT_EVERY = 16;
export const REPLAY_PAGE_STEPS = 16;
export const TURN_CAP_PLAYER_TURNS = 60;
