//! Every rules constant lives here (BUILD §2). The engine never hard-codes these numbers.
//! Rows SPEC §11 marks "decide" (R1, R2, R4, R5, R14, R26, R39) are flipped here in one line.
//!
//! Port of `packages/engine/src/config.ts` (part 1's type freeze, SURFACE §6.4), values verbatim,
//! plus (CLAUDE.md rule 9) the numbers TS stated outside `config.ts` (research A §4), moved here
//! under their TS names, and the training lanes' gate (SURFACE §14.2). A TS constant object becomes
//! a `pub const` of a struct named after it (SURFACE §4.2).
//!
//! Integer types: a game quantity (a stat, a cost, a count of cards, a turn, a lane) is `i32`, as
//! everywhere in the engine (SURFACE §4.3); a bound on how many times a Rust loop runs or how long a
//! Rust collection or string may grow is `usize`, so it compares with `len()` without a cast.

use std::ops::Index;

use serde::{Deserialize, Serialize};

use crate::wire::{GlitchOutcome, KeywordKind, Rarity, Tag, string_union};

/// §2.6
pub const DECK_SIZE: i32 = 20;
/// §2.6, §9.4
pub const MAX_COPIES: i32 = 1;
/// §2.3
pub const MAX_MANA: i32 = 4;
/// §2
pub const HERO_HEALTH: i32 = 30;

/// BUILD M1-T1 (`createGame` yields `turn = 0`): the turn number §2.1's setup runs at. Setup is no
/// player's turn — p1 takes the first turn after it (§2.1 step 5) — so nothing played during it
/// belongs to a turn of its controller's (R155, R241).
pub const SETUP_TURN: i32 = 0;
/// §2.5, R2, R389 (patch v0.2.0, docs/classic-sets.md B4.3): the cap counts player-turns, so 60 means
/// 30 each. Two 20-card decks that do nothing fatigue out at player-turn 48 (§2.4, R3), so the cap is a
/// backstop for games that heal, gain Armor or refill a deck, and fatigue is a long game's usual end.
pub const TURN_CAP_PLAYER_TURNS: i32 = 60;
/// §2.4, R4 (decide): a card drawn or added to a full hand is burned.
pub const HAND_CAP: i32 = 10;

/// §2.1: indexed by seat; the Nth seat (1-based) draws N+2.
pub const OPENING_DRAW: &[i32] = &[3, 4];

/// §2.1, R244: indexed by seat like `OPENING_DRAW`, the copies of The Coin each seat is dealt once both
/// mulligans are answered. Hearthstone's rule: the player going second gets one, the first none.
pub const OPENING_COINS: &[i32] = &[0, 1];
/// §7, R245: the catalog id of The Coin, the one token a rule deals rather than a card.
pub const COIN_DEF_ID: &str = "core-t-coin";

/// R382: a pool named by one of these tags also holds that tag's tokens. The five Grapes are Fruit
/// Tokens "that can be generated by any Fruit card", and appear in no other pool but one that takes
/// every token (`withTokens`).
pub const POOL_TOKEN_TAGS: &[Tag] = &[Tag::Fruit];

/// §3
pub const UNIT_ZONES: i32 = 5;
/// §3
pub const BACKROW_ZONES: i32 = 5;
/// Classic #18 Glitch in the System's number choice (SPEC §8.6 row 18, BUILD §2): the numbers 0 to 10,
/// the same eleven options every time, so the options reveal nothing about any hand or deck.
pub const GLITCH_NUMBERS: &[i32] = &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

// The Glitch Easter egg (SPEC §7, issue #170; R673–R679).
/// R673: the "… in the System" cards — Classic #18 Glitch in the System and Classic #25 Lag in the System.
pub const SYSTEM_CARD_DEF_IDS: &[&str] = &["classic-018", "classic-025"];
/// R673, R674: the catalog id of Glitch, the hidden token a generated card may become.
pub const GLITCH_DEF_ID: &str = "classic-t-glitch";
/// R673: each System play adds this many chances in GLITCH_ODDS_DENOMINATOR that a generated card is Glitch.
pub const GLITCH_ODDS_PER_SYSTEM_PLAY: i32 = 1;
/// R673: "a 1/10000 chance".
pub const GLITCH_ODDS_DENOMINATOR: i32 = 10000;
/// R676: Glitch's four outcomes, in the order the issue lists them; one is drawn uniformly by the match rng.
pub const GLITCH_OUTCOMES: &[GlitchOutcome] = &[
    GlitchOutcome::Reset,
    GlitchOutcome::Swap,
    GlitchOutcome::Boards,
    GlitchOutcome::Void,
];

/// R5 (decide): any unit may attack any enemy unit or hero, subject to Taunt.
pub const LANE_RESTRICTED_ATTACKS: bool = false;
/// R1 (decide): Cry fires only when played from hand or cast by an effect.
pub const CRY_ON_PLAY_ONLY: bool = true;
/// R14 (decide): units and backrow form two independent rings.
pub const ROTATION_RING: &str = "two-rings";
/// R26 (decide): Genn's Greed exiles odd current-cost cards.
pub const GENN_GREED_EXILES: &str = "odd";
/// R39 (decide): Felinor Fiender = printed stats plus the sum of your Felinors.
pub const FIENDER_STATS_MODE: &str = "printed-plus-sum";

/// R3: the Nth draw from an empty library deals N damage.
pub const FATIGUE_DAMAGE: fn(i32) -> i32 = |n| n;

/// §2.5, R36: offers allowed per player per turn.
pub const DRAW_OFFERS_PER_TURN: i32 = 1;
/// §2.5, R36: a declined offer blocks that player for this many of their turns.
pub const DRAW_OFFER_BLOCK_TURNS: i32 = 3;
/// §2.5, R79: the most prompts one `timeout` answers for the active player. A chain of prompts is a
/// handful (KY's Private Tutor asks three times), after which the turn ends. This only bounds a card
/// that would keep asking, so one `timeout` always returns: if a prompt is still open after this many
/// answers, the timeout stops there with the turn still running, and the next expiry carries on. No
/// Core card can reach it.
pub const TIMEOUT_ANSWER_CAP: usize = 500;

/// R28
pub const CALL_TO_CHAOS_CHAIN_CAP: i32 = 20;
/// R58: cast-on-draw cards one draw may cast before the next one goes to hand uncast.
pub const CAST_ON_DRAW_CHAIN_CAP: i32 = 20;

/// `{ base, radiant }`: a number by the face that prints it.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ByFace {
    pub base: i32,
    pub radiant: i32,
}

impl ByFace {
    /// `value[radiant ? "radiant" : "base"]`.
    pub const fn on(&self, radiant: bool) -> i32 {
        if radiant { self.radiant } else { self.base }
    }
}

/// §8 #73: largest single damage instance a hero with Anti-oneshot Armor takes.
pub const ANTI_ONESHOT_CAP: ByFace = ByFace { base: 5, radiant: 3 };

/// `{ paid, embiggen }`: #84 Going Long's Armor by the price paid.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct HeroArmorPrice {
    pub paid: i32,
    pub embiggen: i32,
}

impl HeroArmorPrice {
    /// `value[embiggened ? "embiggen" : "paid"]`.
    pub const fn on(&self, embiggened: bool) -> i32 {
        if embiggened { self.embiggen } else { self.paid }
    }
}

/// `HERO_ARMOR`'s shape.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct HeroArmor {
    pub base: HeroArmorPrice,
    pub radiant: HeroArmorPrice,
}

impl HeroArmor {
    /// `HERO_ARMOR[radiant ? "radiant" : "base"]`.
    pub const fn on(&self, radiant: bool) -> HeroArmorPrice {
        if radiant { self.radiant } else { self.base }
    }
}

/// §8 #84 Going Long: the Armor it gives its controller's hero (§4.4 step 2), by face and by which
/// price was paid — "Armor 2. Paid (4): Armor 4", radiant "Armor 4. Paid (4): Armor 8" (patch
/// v0.1.1). `paid` is the printed cost 2, `embiggen` the embiggen price 4 (R81 records which on the
/// instance).
pub const HERO_ARMOR: HeroArmor = HeroArmor {
    base: HeroArmorPrice { paid: 2, embiggen: 4 },
    radiant: HeroArmorPrice { paid: 4, embiggen: 8 },
};
/// §8 #38 Quickstriker, R281: the multiple of X each granted Combo deals to the enemy hero, by the
/// granting card's face — "Combo X: deal X damage", radiant "deal 2X damage", one hit either way.
pub const QUICKSTRIKER_COMBO_MULTIPLE: ByFace = ByFace { base: 1, radiant: 2 };

/// R636: the attacks a Unit with Windfury may declare in one turn, where every other Unit has one.
pub const WINDFURY_ATTACKS: i32 = 2;

/// R21: Plastic Surgery and Zao Gao draw from this pool; a unit never gets a keyword it has. R346:
/// patch v0.1.1 added Pierce, at the end. R636 added Windfury after it; Deft (R49) was added by
/// patch v0.2.4; Temporary (R637) stays out, since a card on the field is never in a hand to be discarded.
/// (Keyword keys, as `keyword_key` writes them.)
pub const RANDOM_KEYWORD_POOL: &[&str] = &[
    "Taunt",
    "Armor 1",
    "Rush",
    "Charge",
    "First Strike",
    "Poisonous",
    "Lifesteal",
    "Reborn",
    "Divine Shield",
    "Trample",
    "Cleave",
    "Pierce",
    "Windfury",
    "Deft",
];

/// R349: a Unit that prints no Radiant form (the Ghoul Token) is, made Radiant, its base face with
/// its attack and health multiplied by this — a summon's X/X included (§7).
pub const RADIANT_FALLBACK_FACTOR: i32 = 2;

/// R657: an Animated card with no printed stats fights with this attack.
pub const ANIMATED_FALLBACK_ATTACK: i32 = 0;

/// R657: an Animated card with no printed stats fights with this health.
pub const ANIMATED_FALLBACK_HEALTH: i32 = 1;

/// R348: the least X a player may choose for an X-cost card whose X is theirs to choose (#24, #74).
/// Heroic Power's X is its power's and never chosen (R43), so this does not reach it.
pub const MIN_CHOSEN_X: i32 = 1;

/// R25: KY's Math Equation; the index clamps at 11.
pub const FIB: &[i32] = &[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89];

pub fn fib(index: i32) -> i32 {
    let clamped = index.clamp(0, FIB.len() as i32 - 1);
    FIB.get(clamped as usize).copied().unwrap_or(0)
}

/// R80: a library holds at most this many cards.
pub const LIBRARY_CAP: i32 = 60;

/// §6.3
pub const FUSE_COST_CAP: i32 = 4;
/// R9: replacements are drawn before the returned cards are shuffled back.
pub const MULLIGAN_ORDER: &str = "draw-then-shuffle";
/// §10.7: the random policy ends its turn with this probability when other actions exist.
pub const AI_END_TURN_PROBABILITY: f64 = 0.1;
/// R90: the most choice combinations `legalActions` enumerates for one play.
pub const MAX_CHOICE_COMBINATIONS: usize = 64;
/// §9.3: how many answered nonces the state remembers for dedupe.
pub const NONCE_HISTORY: usize = 64;

/// §2.4: the draws each start of turn makes before any handicap (R183).
pub const DRAWS_PER_TURN: i32 = 1;

/// §9.9, R180: the resources one seat plays with. Every field is a non-negative integer. The type
/// lives here because `config.ts` imports nothing; `state.rs` stores it on a `PlayerState`.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(
    feature = "ts",
    derive(ts_rs::TS),
    ts(export, export_to = "../../../apps/web/src/wire/generated/")
)]
#[serde(rename_all = "camelCase")]
pub struct Handicap {
    /// R184: exactly how many cards `createGame` requires in this seat's deck.
    pub deck_size: i32,
    /// R181: crystals added to the turns-started count before the cap.
    pub mana_bonus: i32,
    /// R181: the most max mana a refresh gives, before persistent modifiers.
    pub mana_cap: i32,
    /// R182: cards added to §2.1's opening draw.
    pub extra_opening_cards: i32,
    /// R183: separate draws after DRAWS_PER_TURN at each start of turn.
    pub extra_draws_per_turn: i32,
    /// R290: the health this seat's hero starts the game with, in place of HERO_HEALTH. Absent means
    /// HERO_HEALTH, which is why the three practice tiers never set it and hash exactly as before the
    /// field existed. Only the tutorial's handicap (`AI_TUTORIAL`) sets it, and only lower.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(feature = "ts", ts(optional))]
    pub hero_health: Option<i32>,
}

/// R180: this spec's own resources. A seat with no handicap plays with these.
pub const HUMAN_HANDICAP: Handicap = Handicap {
    deck_size: DECK_SIZE,
    mana_bonus: 0,
    mana_cap: MAX_MANA,
    extra_opening_cards: 0,
    extra_draws_per_turn: 0,
    hero_health: None,
};

string_union! {
    /// §9.9: the three practice tiers.
    pub enum Difficulty {
        Easy = "easy",
        Medium = "medium",
        Hard = "hard",
    }
}

pub const DIFFICULTIES: &[Difficulty] = &[Difficulty::Easy, Difficulty::Medium, Difficulty::Hard];

/// `Readonly<Record<Difficulty, Handicap>>`: `AI_DIFFICULTY`'s shape, indexed by `Difficulty`.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub struct AiDifficulty {
    pub easy: Handicap,
    pub medium: Handicap,
    pub hard: Handicap,
}

impl Index<Difficulty> for AiDifficulty {
    type Output = Handicap;

    fn index(&self, difficulty: Difficulty) -> &Handicap {
        match difficulty {
            Difficulty::Easy => &self.easy,
            Difficulty::Medium => &self.medium,
            Difficulty::Hard => &self.hard,
        }
    }
}

/// §9.9's table (R180): the AI seat's handicap per tier. The AI itself is identical at every tier;
/// only these resources differ. Easy is a human's resources exactly, so an Easy game stores no
/// handicap and hashes like any other game.
pub const AI_DIFFICULTY: AiDifficulty = AiDifficulty {
    easy: HUMAN_HANDICAP,
    medium: Handicap {
        deck_size: 25,
        mana_bonus: 1,
        mana_cap: 5,
        extra_opening_cards: 1,
        extra_draws_per_turn: 0,
        hero_health: None,
    },
    hard: Handicap {
        deck_size: 30,
        mana_bonus: 1,
        mana_cap: 7,
        extra_opening_cards: 1,
        extra_draws_per_turn: 1,
        hero_health: None,
    },
};

/// §9.10, R290: the tutorial opponent's handicap, the one below Easy. It is a handicap like the
/// three tiers (R180) and lowers the AI seat's resources instead of raising them: a 12-card deck
/// (each lesson's own list, R291, so it runs out and fatigues sooner), at most 3 mana crystals, and
/// a hero that starts at 20 health. The AI's search, evaluation and budget are the ones every tier
/// plays with. It is not in `DIFFICULTIES`: nobody picks it, the tutorial deals it.
pub const AI_TUTORIAL: Handicap = Handicap {
    deck_size: 12,
    mana_bonus: 0,
    mana_cap: 3,
    extra_opening_cards: 0,
    extra_draws_per_turn: 0,
    hero_health: Some(20),
};

// ---------------------------------------------------------------------------------------------
// Patch v0.2.0 (docs/classic-sets.md B3–B5). Every number the new rules state, by workstream.
// ---------------------------------------------------------------------------------------------

// ---- v0.2.0 constants: instance data (B3.3 Brittle, B3.4 Degrade and Upgrade) ----

/// B3.3, R385 (the designer's B9 #41: t + 2): a Brittle count started on player-turn t first ticks at
/// the first start of its controller's turn numbered t + this or later, so the card lives through the
/// rest of the turn it got the count on and a whole turn of the other player's first.
pub const BRITTLE_FIRST_TICK_TURNS: i32 = 2;
/// B3.3 rule 2: how much one start-of-turn tick takes off a Brittle count.
pub const BRITTLE_TICK: i32 = 1;
/// B3.3 rule 5, B3.4: how far one Degrade or Upgrade moves a numbered keyword, a Brittle count or an
/// X-cost card's X — one step of "one X on the card gets 1 worse / better".
pub const TUNE_X_STEP: i32 = 1;
/// B3.4 rule 3: how far one Degrade or Upgrade moves a card's cost (`costMod`).
pub const TUNE_COST_STEP: i32 = 1;
/// B3.4 rule 3, the designer's "Increase cost by (1) (up to 4)": a Degrade never lifts a cost above this.
pub const TUNE_COST_CAP: i32 = 4;
/// B3.4 rule 3: an Upgrade never takes a cost below this.
pub const TUNE_COST_FLOOR: i32 = 0;
/// B3.4 rule 3, the designer's "reduces the stats … by a total of 4": the split one stats change
/// rolls, k in 0 to this to attack and the rest to health.
pub const TUNE_STAT_TOTAL: i32 = 4;
/// B3.4 rule 3: "attack floors at 0".
pub const TUNE_ATTACK_FLOOR: i32 = 0;
/// B3.4 rule 3, the designer's "not below 1 health": a Degrade never takes current health below this.
pub const TUNE_HEALTH_FLOOR: i32 = 1;
/// B3.4 rule 3: the keywords a Degrade never removes, because losing them would help the card —
/// "Cannot be in Defense Position" is a static flag (§8 #65.1), not a keyword, so it is never offered.
pub const TUNE_HARMFUL_KEYWORDS: &[KeywordKind] = &[KeywordKind::CantAttack, KeywordKind::Brittle];

/// `{ upTo, step }`: one band of `PARAM_DEFAULT_STEP`.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub struct ParamStepBand {
    pub up_to: i32,
    pub step: i32,
}

/// `PARAM_DEFAULT_STEP`'s shape.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub struct ParamDefaultStep {
    pub small: ParamStepBand,
    pub medium: ParamStepBand,
    pub large_divisor: i32,
}

/// B3.4 rule 5: a declared number's default step — 1 for a number up to `small.upTo`, 2 up to
/// `medium.upTo`, and above that a quarter of it, rounded (`largeDivisor`), never less than 1.
pub const PARAM_DEFAULT_STEP: ParamDefaultStep = ParamDefaultStep {
    small: ParamStepBand { up_to: 5, step: 1 },
    medium: ParamStepBand { up_to: 12, step: 2 },
    large_divisor: 4,
};
/// B3.4 rule 5, R386: "an amount never drops below 1" — a tuned number's floor: a declared number that
/// names no `min`, an X, a numbered keyword (Activate X, Tribute X, Armor …) and a Brittle count a
/// Degrade lowers.
pub const TUNE_MIN_AMOUNT: i32 = 1;

// ---- v0.2.0 constants: field (B3.1 Animated, E20, E21, E22) ----

// ---- v0.2.0 constants: play pipeline (E1, E11, E12, E15) ----

// play pipeline B (E11, E12, E15; R452–R455). A cast's X is its caster's current mana, at least
// MIN_CHOSEN_X (R348, R453); the other numbers of these rules are cards' own (`params`).

/// B5 E11, R454: the fewest Plague Counters a play from the graveyard that pays with tokens spends
/// (Classic #74 Corpse Plantation: "each such play spends at least 1 counter").
pub const MIN_PLAGUE_PAYMENT: i32 = 1;
/// B5 E11, R454: what one Plague Counter spent as mana pays of a price ("each counter pays (1)").
pub const PLAGUE_TOKEN_MANA: i32 = 1;
/// B5 E12, R452: how many casts one random cast and every cast made inside its resolution may make in
/// all (Classic+ #47 Jogg's Box, #38.1 Solarius Prime), as R28 caps a Call to Chaos chain and R58 a
/// cast-on-draw chain: a random cast whose casts cast at random cannot multiply without end.
pub const RANDOM_CAST_CHAIN_CAP: i32 = 20;

/// B5 E4, R451: the tags whose cards a player's "last face-up card played" record passes over — the
/// AI generated cards (B8), so two Autocompletes can't copy each other for ever.
pub const LAST_FACE_UP_SKIPPED_TAGS: &[Tag] = &[Tag::Ai];

// ---- v0.2.0 constants: activate and turn (B3.2, B4.3, E3, E10) ----

/// B3.2 rule 7, R384: "Activate ♾️" is any number of uses per card per turn, bounded here so a game
/// still ends (a fuzz game's random policy may keep activating). Every ♾️ card in the sets is bounded
/// by a resource too (units to Tribute, Plague Counters to consume).
pub const ACTIVATE_UNLIMITED_CAP: i32 = 100;

// ---- v0.2.0 constants: damage and combat (E5, E6, E35, E37) ----

/// B5 E5, E9, R460: how many times one hit may be redirected before it lands where it stands. Each
/// Trap that redirects is spent as it fires, so two players' backrows bound a chain of Traps by
/// themselves; the cap is for a Field Trap, which stays and could send a hit back and forth for ever.
/// (`u32`, the type of the per-call `EngineSink::converting` counter it bounds.)
pub const DAMAGE_REDIRECT_CAP: u32 = 2 * BACKROW_ZONES as u32;

/// `BERSERK_MARK`'s shape: a mark and its colour key (R437).
#[derive(Serialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub struct MarkSpec {
    pub mark: &'static str,
    pub color: &'static str,
}

/// B5 E35: the mark a Berserk unit carries in both views (R437's reusable mark), and its colour key.
pub const BERSERK_MARK: MarkSpec = MarkSpec {
    mark: "berserk",
    color: "red",
};

// ---- v0.2.0 constants: prompts and generation (E18, E19, E23–E25) ----

// generation (E19, E23–E25), below A6a's prompts constants:
/// R468: the longest ingredient list a fused id spells out (`t-<n>:<a>+<b>`, R179), in characters of
/// the part after `t-<n>:`. A longer one — a card fused onto again and again, Classic+ #74 — is named
/// by a digest of that list instead (`t-<n>:#<hex>`), and its definition keeps the whole list.
pub const FUSED_ID_CAP: usize = 120;
/// R471: the placement multiplier of a card that doubles nothing (the Plague Counters placed as written).
pub const PLAGUE_MULTIPLIER_NONE: i32 = 1;

// ---- v0.2.0 constants: Core patches (R423, R426–R431) ----
/// R423: how many different effects a Radiant Call to Chaos rolls from its list — "Three different
/// random effects, resolved in the order listed" (Core #95's Radiant face since patch v0.2.0, and
/// Classic+ #73's). The base face rolls one.
pub const CALL_TO_CHAOS_RADIANT_EFFECTS: i32 = 3;

// ---- v0.2.0 constants: Classic+ cards #1–#39 (cards-plus-c) ----
/// R59, §8.7 C+ #32.3 Blade Storm: the printed round cap, "up to 30 times". The card reads its declared
/// `rounds` (R386), which the catalog prints as this and a Degrade or Upgrade moves on that card only.
pub const BLADE_STORM_ROUNDS: i32 = 30;
/// C+ #35 Rollback (R419): the most player-turns it goes back ("Choose 1, 2 or 3").
pub const ROLLBACK_MAX_TURNS: i32 = 3;
/// R419: the board snapshots the history keeps — this turn's and the ROLLBACK_MAX_TURNS before it.
pub const BOARD_HISTORY_DEPTH: i32 = ROLLBACK_MAX_TURNS + 1;

// ---- v0.2.0 constants: Classic+ cards #40–#78 and the AI cards (the cards-plus-d workstream) ----

// Classic+ #42 KY's Test (SPEC §8.7, R420, BUILD §2).
string_union! {
    /// R420: a KY's Test difficulty.
    pub enum KyTestDifficulty {
        Easy = "Easy",
        Medium = "Medium",
        Hard = "Hard",
    }
}

/// R420: the three difficulties, in the order the first prompt offers them.
pub const KY_TEST_DIFFICULTIES: &[KyTestDifficulty] = &[
    KyTestDifficulty::Easy,
    KyTestDifficulty::Medium,
    KyTestDifficulty::Hard,
];
/// R420: the options every problem shows, exactly one of them its answer.
pub const KY_TEST_OPTIONS: i32 = 4;
/// R420: the floor of bank problems per difficulty (the bank test's floor, in `jackioh-cards`).
pub const KY_TEST_MIN_PROBLEMS: i32 = 30;

/// `{ min, max }`: an inclusive range.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct IntRange {
    pub min: i32,
    pub max: i32,
}

/// R420: an Easy problem is a + b with each addend in this range, inclusive.
pub const KY_TEST_EASY_ADDENDS: IntRange = IntRange { min: 10, max: 99 };
/// R420: an Easy problem's three wrong sums are a + b moved by three different ones of these.
pub const KY_TEST_EASY_MISSES: &[i32] = &[1, -1, 2, -2, 10, -10];

/// `KyTestReward.pool`: a pool of non-token cards of every set (R380).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct KyTestRewardPool {
    pub tags: Option<&'static [Tag]>,
    /// Only ever `Rarity::Legendary`.
    pub rarity: Option<Rarity>,
    pub cost: Option<i32>,
}

/// `KyTestReward.count`: how many, or `"fill"`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum KyTestRewardCount {
    N(i32),
    /// As many as the hand has room for under `HAND_CAP`.
    Fill,
}

/// R420: one reward a difficulty may roll (BUILD §2 `KY_TEST_REWARDS`). `label` is the reward as the
/// card's text prints it, which the first prompt shows beside its difficulty. A reward is cards: the
/// one card the text names (`defId`: The Coin, KY's Gift), or random cards from a pool of non-token
/// cards of every set (`pool`, R380; never KY's Test itself, R387; repeats allowed, R60). `count` is
/// how many, or `"fill"`: as many as the hand has room for under `HAND_CAP`. `costOverride` is the cost
/// the text sets each card to ("which costs (0)", "which cost (1)").
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct KyTestReward {
    pub id: &'static str,
    pub label: &'static str,
    pub def_id: Option<&'static str>,
    pub pool: Option<KyTestRewardPool>,
    pub count: KyTestRewardCount,
    pub cost_override: Option<i32>,
}

/// `KY_TEST_REWARDS`'s shape: each difficulty's list.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct KyTestRewards {
    pub easy: &'static [KyTestReward],
    pub medium: &'static [KyTestReward],
    pub hard: &'static [KyTestReward],
}

impl KyTestRewards {
    /// `KY_TEST_REWARDS[difficulty]`.
    pub const fn of(&self, difficulty: KyTestDifficulty) -> &'static [KyTestReward] {
        match difficulty {
            KyTestDifficulty::Easy => self.easy,
            KyTestDifficulty::Medium => self.medium,
            KyTestDifficulty::Hard => self.hard,
        }
    }
}

const fn pool_of(
    tags: Option<&'static [Tag]>,
    rarity: Option<Rarity>,
    cost: Option<i32>,
) -> Option<KyTestRewardPool> {
    Some(KyTestRewardPool { tags, rarity, cost })
}

/// R420: each difficulty's list of rewards, in the order the text prints them; one is rolled per difficulty.
pub const KY_TEST_REWARDS: KyTestRewards = KyTestRewards {
    easy: &[
        KyTestReward {
            id: "coins",
            label: "3 The Coins",
            def_id: Some("core-t-coin"),
            pool: None,
            count: KyTestRewardCount::N(3),
            cost_override: None,
        },
        KyTestReward {
            id: "ky",
            label: "a random (2) Cost KY card",
            def_id: None,
            pool: pool_of(Some(&[Tag::Ky]), None, Some(2)),
            count: KyTestRewardCount::N(1),
            cost_override: None,
        },
        KyTestReward {
            id: "legendary",
            label: "a random Legendary card, which costs (0)",
            def_id: None,
            pool: pool_of(None, Some(Rarity::Legendary), None),
            count: KyTestRewardCount::N(1),
            cost_override: Some(0),
        },
        KyTestReward {
            id: "books",
            label: "2 random Books",
            def_id: None,
            pool: pool_of(Some(&[Tag::Book]), None, None),
            count: KyTestRewardCount::N(2),
            cost_override: None,
        },
    ],
    medium: &[
        KyTestReward {
            id: "fours",
            label: "2 random (4) Cost cards, which cost (1)",
            def_id: None,
            pool: pool_of(None, None, Some(4)),
            count: KyTestRewardCount::N(2),
            cost_override: Some(1),
        },
        KyTestReward {
            id: "books",
            label: "5 random Books",
            def_id: None,
            pool: pool_of(Some(&[Tag::Book]), None, None),
            count: KyTestRewardCount::N(5),
            cost_override: None,
        },
        KyTestReward {
            id: "ky",
            label: "5 random KY cards",
            def_id: None,
            pool: pool_of(Some(&[Tag::Ky]), None, None),
            count: KyTestRewardCount::N(5),
            cost_override: None,
        },
        KyTestReward {
            id: "fill",
            label: "fill your hand with random Books",
            def_id: None,
            pool: pool_of(Some(&[Tag::Book]), None, None),
            count: KyTestRewardCount::Fill,
            cost_override: None,
        },
    ],
    hard: &[KyTestReward {
        id: "gift",
        label: "KY's Gift, which costs (0)",
        def_id: Some("classicplus-042-1"),
        pool: None,
        count: KyTestRewardCount::N(1),
        cost_override: Some(0),
    }],
};

// Classic+ #62 KY's Papaya (SPEC §8.7, R422, BUILD §2).
/// R422: the rows of the curve's grid, y 0 (your backrow) to 3 (their backrow).
pub const PAPAYA_ROWS: i32 = 4;
/// R422: the most cells a curve is drawn through — four fix a cubic, the highest degree it may have.
pub const PAPAYA_MAX_CELLS: i32 = 4;

// Classic+ #65 Two Grapes and #66 Vine of Grapes (SPEC §8.7, R382, BUILD §2).
/// One Grape and its chance in percent (`GRAPE_ODDS`).
#[derive(Serialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub struct GrapeOdds {
    pub def_id: &'static str,
    pub percent: i32,
}

/// R382: each Grape's chance in percent, in Lucky's order from worst to best (Rotten < Normal < Large <
/// Golden < Mythic): a roll with Lucky keeps the later of its two.
pub const GRAPE_ODDS: &[GrapeOdds] = &[
    GrapeOdds {
        def_id: "classicplus-065-1",
        percent: 12,
    },
    GrapeOdds {
        def_id: "classicplus-065-2",
        percent: 60,
    },
    GrapeOdds {
        def_id: "classicplus-065-3",
        percent: 20,
    },
    GrapeOdds {
        def_id: "classicplus-065-4",
        percent: 7,
    },
    GrapeOdds {
        def_id: "classicplus-065-5",
        percent: 1,
    },
];

// Classic+ #73 Call to Chaos (Classic+ Edition) (SPEC §8.7 row 73, R423): its table's numbers.
/// §8.7 row 73 entry 1: "Add 5 random Fruits to your hand".
pub const CHAOS_PLUS_FRUITS: i32 = 5;
/// §8.7 row 73 entry 2: "Add 3 random Books to your hand".
pub const CHAOS_PLUS_BOOKS: i32 = 3;
/// §8.7 row 73 entry 4: "Add 3 random Classic cards to your hand".
pub const CHAOS_PLUS_CLASSIC_CARDS: i32 = 3;
/// §8.7 row 73 entries 1, 2, 4 and 9: the added and the replacing cards "cost (0)" (`costOverride`).
pub const CHAOS_PLUS_COST: i32 = 0;
/// §8.7 row 73 entry 5: "Upgrade every card in your hand and deck twice".
pub const CHAOS_PLUS_UPGRADES: i32 = 2;
/// §8.7 row 73 entry 7: "Degrade every card on your opponent's field and in their hand three times".
pub const CHAOS_PLUS_DEGRADES: i32 = 3;

// T-AI-4 Chain of Thought (SPEC §8.7, BUILD §2).
/// T-AI-4: the repeats after the first draw, a termination bound: five draws at most.
pub const CHAIN_OF_THOUGHT_REPEATS: i32 = 4;

// ---------------------------------------------------------------------------------------------
// Moved here in v0.3.0 (CLAUDE.md rule 9; research A §4): the numbers TS stated outside
// `config.ts`, under their TS names. Each names the module that reads it.
// ---------------------------------------------------------------------------------------------

/// §10.8, §10.10: how many of the most recent events the view carries for animation (`view_for`).
pub const VIEW_EVENT_LIMIT: usize = 32;

/// §7: a Radiant Sheep Token is "2/2, worth 3 Tributes" — the base one is worth 2 (`play_choices`).
pub const RADIANT_SHEEP_TRIBUTE_VALUE: i32 = 3;
pub const SHEEP_TRIBUTE_VALUE: i32 = 2;

/// §6.3 Discover: "choose 1 of 3" (`effects::last_board`).
pub const LAST_BOARD_DISCOVER_OPTIONS: i32 = 3;
/// C+ #29: "It costs (0)", "Each costs (0)" — a `costOverride` (R65) (`effects::last_board`).
pub const LAST_BOARD_CARD_COST: i32 = 0;

/// §4.5 loops until nothing changes; this bounds a pathological loop loudly (R69, R89) (`state_check`).
pub const STATE_CHECK_PASS_CAP: usize = 100;

/// A drain that keeps parking new work stops here rather than spinning (§2.5's cap spirit) (`work`).
pub const MAX_WORK_STEPS: usize = 500;

/// Enumerating answers is bounded like `legalActions`'s other combinations (R90) (`prompts`).
pub const MAX_PROMPT_ANSWERS: usize = 256;

/// The most keep-subsets `legalActions` lists for one mulligan (`reduce`).
pub const MAX_MULLIGAN_SUBSETS: usize = 256;

/// R77's smallest fusion, as `subsystems::fuse`'s `FUSE_MIN_INGREDIENTS` (`subsystems::last_boards`).
pub const FUSED_MIN_PARTS: usize = 2;

/// §8 #95: "summon 3 random 3-cost Units" (`subsystems::call_to_chaos`).
pub const CHAOS_UNIT_COUNT: i32 = 3;
pub const CHAOS_UNIT_COST: i32 = 3;
/// §8 #95: "heal your hero 30" — a hero heal has no cap (§6.3 Heal).
pub const CHAOS_HEAL: i32 = 30;
/// §8 #95: "draw your whole library and gain 4 mana".
pub const CHAOS_MANA: i32 = 4;
/// §8 #95: "add 3 random cards to hand costing 0".
pub const CHAOS_ADDED_CARDS: i32 = 3;
/// §8 #95 and §7: "summon five Radiant Rush Tokens".
///
/// They used to be a bespoke 5/5 through `statsOverride`, which made #95 the only card in the set
/// that invented a Rush Token size. It now summons the token's own RADIANT face (6/6, Rush), so
/// the stats live in one place — the catalog — and a later change to the radiant token moves this
/// card with it instead of leaving it behind.
pub const CHAOS_RUSH_TOKENS: i32 = 5;
/// §8 #95: "every card in your hand and library costs 2 less".
pub const CHAOS_COST_DISCOUNT: i32 = 2;
/// §8 #95: "summon 5 random Field Spells or Traps … into your backrow".
pub const CHAOS_BACKROW_CARDS: i32 = 5;

/// `SCORER_WEIGHTS`'s shape (`subsystems::scorer`).
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ScorerWeights {
    /// "lethal available → max".
    pub lethal: f64,
    /// "can clear the enemy board → high".
    pub clears_board: f64,
    /// Partial credit: an answer to some of the enemy board is worth less than all of it.
    pub per_kill: f64,
    /// "hero below 10 and card heals → high".
    pub heal: f64,
    /// The fallback: printed stats per mana.
    pub stats_per_mana: f64,
    /// The fallback's second half: what the card leaves behind beyond this turn.
    pub draw_value: f64,
}

/// The weights, in one place so they can be tuned without touching the scoring functions (§10.7:
/// "the weights are engine constants, tested against fixed states"). The tests pin the ranking a
/// fixed state produces, never these numbers, so a tuning pass does not rewrite the test file.
///
/// The gaps are deliberate: the four priorities of §10.7 are a strict order, so no amount of stats
/// per mana can outrank a heal at low health, no heal can outrank a board clear, and nothing
/// outranks lethal.
pub const SCORER_WEIGHTS: ScorerWeights = ScorerWeights {
    lethal: 100_000.0,
    clears_board: 10_000.0,
    per_kill: 1_000.0,
    heal: 5_000.0,
    stats_per_mana: 10.0,
    draw_value: 25.0,
};

/// §10.7: the hero health below which a heal becomes a priority (`subsystems::scorer`).
pub const SCORER_LOW_HEALTH: i32 = 10;

/// How many of one candidate's plays the dry run tries. A play is tried at its strongest price (the
/// largest X, embiggened when that is affordable) in the first zone it could take, so what varies is
/// its targets and modes, taken heroes first (`targetRank`): the enemy hero is lethal's target, the
/// viewer's own a heal's, and the board's units come after them (`subsystems::scorer`).
pub const SCORER_DRY_RUN_PLAYS: usize = 8;

/// R753: Life Tap's "Take 2 damage", dealt to its own hero by the card (`subsystems::hero_power`).
pub const LIFE_TAP_DAMAGE: i32 = 2;
/// R754: how far Steady Shot's Radiant face raises its declared number (`"shot"`) per use.
pub const STEADY_SHOT_RAISE: i32 = 2;
/// R756: Ping's damage.
pub const PING_DAMAGE: i32 = 1;
/// R757: Armor Up's Armor until your next turn, and the Armor Tank Up (its Radiant face) keeps.
pub const ARMOR_UP_ARMOR: i32 = 2;
pub const TANK_UP_ARMOR: i32 = 4;
/// R758: Die Insect's damage, and its Radiant face's Lucky.
pub const DIE_INSECT_DAMAGE: i32 = 8;
pub const DIE_INSECT_LUCKY: i32 = 1;
/// R759: how much KY Brainstorm takes off each Spell in your hand.
pub const BRAINSTORM_DISCOUNT: i32 = 1;
/// R760: what Pluck's Fruit costs.
pub const PLUCK_COST: i32 = 0;
/// R352: Stitching's "Discover two (2) Cost or less Units".
pub const STITCHING_INGREDIENTS: i32 = 2;
pub const STITCHING_MAX_COST: i32 = 2;

/// A playout covers one turn, so this ceiling is far above any reachable turn; it exists only so a
/// card that keeps refilling the hand cannot spin forever (BUILD M3-T7) (`subsystems::ai_policy`).
pub const AI_PLAYOUT_STEP_CAP: usize = 500;

/// E: where a Combo-Index starts (§8 #93) (`subsystems::combo_index`).
pub const FIRST_GRADE: i32 = 1;
/// Grade D: "2 different random hand cards cost 1 less" (§8 #93).
pub const GRADE_D_CARDS: i32 = 2;
pub const GRADE_D_DISCOUNT: i32 = 1;
/// Grade A: "8 damage to the enemy hero with Lifesteal" (§8 #93).
pub const GRADE_A_DAMAGE: i32 = 8;

/// R77: Craft a Card fuses "two or three cards", and #85 fuses two. Fewer is not a fusion
/// (`subsystems::fuse`).
pub const FUSE_MIN_INGREDIENTS: usize = 2;

/// §8 #99: "the result costs 0 and goes to your hand", as a `costOverride` per R65 (`subsystems::fuse`).
pub const CRAFTED_CARD_COST: i32 = 0;

// ---------------------------------------------------------------------------------------------
// The AI training lanes (SURFACE §14.2; docs/v0.3.0/README.md §8).
// ---------------------------------------------------------------------------------------------

/// SURFACE §14.2: the games `cargo jackioh promote` plays against each opponent (random, then the parent).
pub const TRAINING_GAMES: i32 = 100;

/// A promotion gate: the wins out of `TRAINING_GAMES` a candidate needs against each opponent
/// (a draw is not a win).
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub struct TrainingGate {
    pub vs_random: i32,
    pub vs_parent: i32,
}

/// SURFACE §14.2: the `improve` lane's gate.
pub const TRAINING_IMPROVE: TrainingGate = TrainingGate {
    vs_random: 90,
    vs_parent: 85,
};
/// SURFACE §14.2: the `unban` lane's gate (plus strictly fewer shadow bans than the parent).
pub const TRAINING_UNBAN: TrainingGate = TrainingGate {
    vs_random: 90,
    vs_parent: 75,
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fib_clamps_and_fatigue_is_n() {
        assert_eq!(fib(-3), 0);
        assert_eq!(fib(6), 8);
        assert_eq!(fib(40), 89);
        assert_eq!(FATIGUE_DAMAGE(4), 4);
        assert_eq!(DAMAGE_REDIRECT_CAP, 10);
        assert_eq!(BOARD_HISTORY_DEPTH, 4);
        assert_eq!(AI_DIFFICULTY[Difficulty::Easy], HUMAN_HANDICAP);
    }
}
