//! Writes `apps/web/src/wire/engineConfig.ts`, the engine constants the web client imports as
//! `@jackioh/engine/config` (docs/v0.3.0/SURFACE.md §5.1): the values and two types that a file under
//! `apps/web/src` imports from it today (SURFACE's twelve, plus `LIBRARY_CAP`, which a web test
//! imports, R768's two replay constants and R1382's `TRIBAL_TAGS`), generated from `crates/engine/src/config.rs` so the
//! client never restates a rules number (CLAUDE.md rule 9).
//!
//! `cargo test -p jackioh-engine --test export_config` writes it; the file is committed, and CI runs
//! this test and fails on a diff, as it does for the ts-rs types under `wire/generated/` (V20).
//!
//! Each constant is one line, `export const NAME<: type> = <JSON value>;`, sorted by name. The type
//! annotation is the one `packages/engine/src/config.ts` declared, so the client's code typechecks
//! against the same shapes it did (`DIFFICULTIES` is `readonly Difficulty[]`, not `string[]`). The
//! two types come from the generated ts-rs files, which are `config.rs`'s own `Handicap` and
//! `Difficulty`; `TRIBAL_TAGS` is typed with the generated `Tag`.
#![allow(
    clippy::disallowed_methods,
    reason = "a generator, not the rules: it writes the client's constants file, as build.rs writes the registry"
)]

use jackioh_engine::config::{
    AI_DIFFICULTY, AI_TUTORIAL, COIN_DEF_ID, CRAFT_ADJECTIVES, CRAFT_HAT_PRICES, CRAFT_KEYWORD_PRICES,
    CRAFT_MAX_EFFECTS, CRAFT_MAX_N, CRAFT_NOUNS, CRAFT_VERB_PRICES, DECK_SIZE, DIFFICULTIES, DRAWS_PER_TURN,
    GLITCH_DEF_ID, HERO_HEALTH, HUMAN_HANDICAP, LIBRARY_CAP, MAX_COPIES, MAX_MANA, RANDOM_ATTACK_TARGET,
    REPLAY_CHECKPOINT_EVERY, REPLAY_PAGE_STEPS, TRIBAL_TAGS, TURN_CAP_PLAYER_TURNS,
};
use serde::Serialize;

/// Where the file goes, from this crate's manifest directory.
const OUTPUT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../apps/web/src/wire/engineConfig.ts"
);

const HEADER: &str = "\
// GENERATED by `cargo test -p jackioh-engine --test export_config` from crates/engine/src/config.rs
// (docs/v0.3.0/SURFACE.md §5.1). Do not edit: CI regenerates it and fails on a diff. The web imports
// it as `@jackioh/engine/config` (apps/web/vite.config.ts, tsconfig.json).

import type { Difficulty } from \"./generated/Difficulty.ts\";
import type { Handicap } from \"./generated/Handicap.ts\";
import type { CraftHatPrice } from \"./generated/CraftHatPrice.ts\";
import type { CraftKeywordPrice } from \"./generated/CraftKeywordPrice.ts\";
import type { CraftVerbPrice } from \"./generated/CraftVerbPrice.ts\";
import type { Tag } from \"./generated/Tag.ts\";

export type { Difficulty, Handicap, CraftHatPrice, CraftKeywordPrice, CraftVerbPrice };

";

/// One constant: its name, the TypeScript annotation `config.ts` gave it (if any), its JSON value.
struct Constant {
    name: &'static str,
    annotation: Option<&'static str>,
    json: String,
}

fn constant<T: Serialize + ?Sized>(
    name: &'static str,
    annotation: Option<&'static str>,
    value: &T,
) -> Constant {
    let json =
        serde_json::to_string(value).unwrap_or_else(|error| panic!("{name} does not serialise: {error}"));
    Constant {
        name,
        annotation,
        json,
    }
}

/// The file's text: the header, then one line per constant, sorted by name.
fn engine_config_ts() -> String {
    let mut constants = vec![
        constant(
            "AI_DIFFICULTY",
            Some("Readonly<Record<Difficulty, Handicap>>"),
            &AI_DIFFICULTY,
        ),
        constant("AI_TUTORIAL", Some("Handicap"), &AI_TUTORIAL),
        constant("COIN_DEF_ID", None, COIN_DEF_ID),
        constant("CRAFT_ADJECTIVES", Some("readonly string[]"), CRAFT_ADJECTIVES),
        constant(
            "CRAFT_HAT_PRICES",
            Some("readonly CraftHatPrice[]"),
            CRAFT_HAT_PRICES,
        ),
        constant(
            "CRAFT_KEYWORD_PRICES",
            Some("readonly CraftKeywordPrice[]"),
            CRAFT_KEYWORD_PRICES,
        ),
        constant("CRAFT_MAX_EFFECTS", None, &CRAFT_MAX_EFFECTS),
        constant("CRAFT_MAX_N", None, &CRAFT_MAX_N),
        constant("CRAFT_NOUNS", Some("readonly string[]"), CRAFT_NOUNS),
        constant(
            "CRAFT_VERB_PRICES",
            Some("readonly CraftVerbPrice[]"),
            CRAFT_VERB_PRICES,
        ),
        constant("DECK_SIZE", None, &DECK_SIZE),
        constant("DIFFICULTIES", Some("readonly Difficulty[]"), DIFFICULTIES),
        constant("DRAWS_PER_TURN", None, &DRAWS_PER_TURN),
        constant("GLITCH_DEF_ID", None, GLITCH_DEF_ID),
        constant("HERO_HEALTH", None, &HERO_HEALTH),
        constant("HUMAN_HANDICAP", Some("Handicap"), &HUMAN_HANDICAP),
        constant("LIBRARY_CAP", None, &LIBRARY_CAP),
        constant("MAX_COPIES", None, &MAX_COPIES),
        constant("MAX_MANA", None, &MAX_MANA),
        constant("RANDOM_ATTACK_TARGET", None, RANDOM_ATTACK_TARGET),
        constant("REPLAY_CHECKPOINT_EVERY", None, &REPLAY_CHECKPOINT_EVERY),
        constant("REPLAY_PAGE_STEPS", None, &REPLAY_PAGE_STEPS),
        constant("TRIBAL_TAGS", Some("readonly Tag[]"), TRIBAL_TAGS),
        constant("TURN_CAP_PLAYER_TURNS", None, &TURN_CAP_PLAYER_TURNS),
    ];
    constants.sort_by(|a, b| a.name.cmp(b.name));

    let mut text = String::from(HEADER);
    for constant in &constants {
        match constant.annotation {
            Some(annotation) => {
                text.push_str(&format!(
                    "export const {}: {} = {};\n",
                    constant.name, annotation, constant.json
                ));
            }
            None => text.push_str(&format!("export const {} = {};\n", constant.name, constant.json)),
        }
    }
    text
}

#[test]
fn export_engine_config() {
    let text = engine_config_ts();
    // Twenty-four constants, each on its own line, the way the client and the diff check read them.
    assert_eq!(text.matches("\nexport const ").count(), 24, "{text}");
    std::fs::write(OUTPUT, text).unwrap_or_else(|error| panic!("could not write {OUTPUT}: {error}"));
}

#[test]
fn the_constants_are_sorted_and_carry_config_rs_values() {
    let text = engine_config_ts();
    let names: Vec<&str> = text
        .lines()
        .filter_map(|line| line.strip_prefix("export const "))
        .map(|rest| rest.split([':', ' ']).next().unwrap_or(""))
        .collect();
    let mut sorted = names.clone();
    sorted.sort();
    assert_eq!(names, sorted);
    assert!(text.contains(&format!("export const DECK_SIZE = {DECK_SIZE};\n")));
    assert!(
        text.contains("export const DIFFICULTIES: readonly Difficulty[] = [\"easy\",\"medium\",\"hard\"];\n")
    );
}
