//! `jackioh_cards`: the card registry (BUILD M4-T2, SPEC §10.9, SURFACE §7): every card script file
//! plus `catalog.json`, turned into what the engine, the tests, the validator and the client consume.
//! Port of `packages/cards/src/index.ts` and `catalog-data.ts`. Written once by part 1.
//!
//! - `scripts::<set>::<file>` and `REGISTRY`: generated by `build.rs` from `src/scripts/**` (SURFACE
//!   §7.4), which also proves what `buildRegistry` threw on (a file's `ID` names a real catalog card,
//!   no two files claim one) and what `missing-tests.ts` listed (a catalog id with no file).
//! - `register_all()`: hands the catalog and every card's scripts to the engine, once.
//! - `catalog_json()`, `flavour_json()`, `catalog_version()`: the data, compiled in (SURFACE §3: data
//!   reaches a pure crate only at compile time).
//! - `CATALOG`, `CATALOG_IDS`, `CATALOG_VERSION`, `card_def`, `card_def_by_index`: `catalog-data.ts`'s
//!   readers of the shipped catalog, under their TS names (SURFACE §4.2).
//!
//! The engine gets the WHOLE catalog and only the scripts that exist. A catalog id with no script is
//! a playable card with no text: `scripts::script_of` falls back to an empty script, so a missing card
//! file can never crash a game or a test — it just does nothing.
//!
//! Not ported: `buildRegistry`/`CARDS`/`CardModule` (the registry is generated), and `flavour.ts`
//! (the client's: `apps/web/src/cards/flavour.ts`, part 21).

use std::sync::{LazyLock, OnceLock};

use indexmap::IndexMap;
use jackioh_engine::{CardDef, CardDefs, CardScripts, SetName};

include!(concat!(env!("OUT_DIR"), "/registry.rs"));

/// SPEC §5.1's single pool source over the shipped catalog (`catalog.query`, `catalog.pool`, …).
pub mod query;

/// Classic+ #42 KY's Test's problem bank (R420).
pub mod ky_test_bank;

pub use query::*;

/// `packages/cards/catalog.json` as compiled in: the card data proved against SPEC §8.
pub fn catalog_json() -> &'static str {
    include_str!("../catalog.json")
}

/// `packages/cards/flavour.json` as compiled in (the client's flavour lines and artists).
pub fn flavour_json() -> &'static str {
    include_str!("../flavour.json")
}

/// §9.4: the catalog version the engine registers — the newest entry of `patches/patches.json`,
/// read by `build.rs` (SURFACE §7.4, §11.3).
pub fn catalog_version() -> &'static str {
    CATALOG_VERSION
}

/// TS `CATALOG_VERSION`: the same as `catalog_version()`.
pub const CATALOG_VERSION: &str = env!("JACKIOH_CATALOG_VERSION");

/// TS `CATALOG`: every def in `catalog.json`, script or no script, in the file's order. Parsed once,
/// on first use; the catalog is one of the two statics a pure crate may hold (SURFACE §3).
pub static CATALOG: LazyLock<CardDefs> = LazyLock::new(|| {
    serde_json::from_str(catalog_json()).unwrap_or_else(|error| panic!("crates/cards/catalog.json: {error}"))
});

/// TS `CATALOG_IDS`: every catalog id, in `catalog.json` order (`core-001` … `classicplus-t-ai-10`).
pub static CATALOG_IDS: LazyLock<Vec<String>> = LazyLock::new(|| CATALOG.keys().cloned().collect());

/// A def by catalog id. Panics rather than returning `None`: a card file names a real card.
pub fn card_def(id: &str) -> CardDef {
    match CATALOG.get(id) {
        Some(def) => def.clone(),
        None => panic!("no catalog entry \"{id}\" (crates/cards/catalog.json)"),
    }
}

/// A def by its SPEC §5 index ("43", "51.1", "T-rush") within its set — an index is unique only
/// there (B2.2) — for tests and pools named by index.
pub fn card_def_by_index(set: SetName, index: &str) -> CardDef {
    match CATALOG
        .values()
        .find(|entry| entry.set == set && entry.index == index)
    {
        Some(def) => def.clone(),
        None => panic!("no {set} catalog entry with index \"{index}\" (crates/cards/catalog.json)"),
    }
}

/// TS `scriptsOf()`: every card file's scripts, by catalog id, in `REGISTRY`'s (id) order. Each
/// call builds them anew; the engine holds the copy `register_all` handed it.
pub fn scripts_of() -> IndexMap<String, CardScripts> {
    REGISTRY
        .iter()
        .map(|(id, script)| ((*id).to_string(), script()))
        .collect()
}

/// Registers the shipped catalog (§9.4) and the card scripts with the engine (SURFACE §7.4): the
/// engine's two `OnceLock`s are set here, once per process, and read-only after. Idempotent: a second
/// call does nothing. A test that wants fixture cards uses the testkit's thread-local override
/// (`testkit::register_scripts`, SURFACE §8), never a second registration.
pub fn register_all() {
    static REGISTERED: OnceLock<()> = OnceLock::new();
    REGISTERED.get_or_init(|| {
        jackioh_engine::catalog::register_catalog(CATALOG.clone(), CATALOG_VERSION);
        jackioh_engine::scripts::register_scripts(scripts_of());
    });
}

/// The card files' tests' `scenario()`: the shipped cards registered first (TS's vitest globalSetup,
/// which the engine's testkit cannot do: it cannot name this crate), then the testkit's harness.
#[cfg(test)]
pub(crate) fn scenario(opts: serde_json::Value) -> jackioh_engine::testkit::Scenario {
    register_all();
    jackioh_engine::testkit::scenario(opts)
}

/// An engine value as its JSON, for the card tests' comparisons with TS's object literals.
#[cfg(test)]
pub(crate) fn js<T: serde::Serialize + ?Sized>(value: &T) -> serde_json::Value {
    serde_json::to_value(value).expect("an engine value serialises")
}

/// TS `{ ...base, ...over }` on two object literals (a test's side setup over its defaults).
#[cfg(test)]
pub(crate) fn merged(mut base: serde_json::Value, over: serde_json::Value) -> serde_json::Value {
    if let (Some(into), serde_json::Value::Object(from)) = (base.as_object_mut(), over) {
        for (key, value) in from {
            into.insert(key, value);
        }
    }
    base
}

/// R386, B3.4 rule 3's Number row: one Upgrade or Degrade of `card` that draws its declared number
/// `key`, applied as `tune_once` applies that row — `step_param` by the step `steppable_params` offers
/// that way. Panics unless a step that way can move the number; returns the value it moves to.
#[cfg(test)]
fn tune_number(
    s: &mut jackioh_engine::testkit::Scenario,
    card: &str,
    key: &str,
    direction: jackioh_engine::effects::TuneDirection,
) -> i32 {
    use jackioh_engine::prelude::{ParamValueOptions, param_value, step_param, steppable_params};
    let instance = s.card(card).clone();
    let before = param_value(s.state(), Some(&instance), key, ParamValueOptions::default());
    let Some(item) = steppable_params(s.state(), &instance, direction)
        .into_iter()
        .find(|item| item.param.key == key)
    else {
        panic!(
            "{card}: a {} cannot move its number \"{key}\" (R386)",
            direction.as_str()
        );
    };
    step_param(s.card_mut(card), key, item.steps);
    let after = param_value(s.state(), Some(s.card(card)), key, ParamValueOptions::default());
    assert_eq!(after, before + item.delta, "{card} {key}");
    after
}

/// `tune_number` for an Upgrade: the number one step better.
#[cfg(test)]
pub(crate) fn upgrade_number(s: &mut jackioh_engine::testkit::Scenario, card: &str, key: &str) -> i32 {
    tune_number(s, card, key, jackioh_engine::effects::TuneDirection::Upgrade)
}

/// R386: whether a step `direction` would move `card`'s declared number `key` at all — false for a
/// number already at the bound it would cross (an amount at 1, a cost set at (0)).
#[cfg(test)]
fn can_tune_number(
    s: &jackioh_engine::testkit::Scenario,
    card: &str,
    key: &str,
    direction: jackioh_engine::effects::TuneDirection,
) -> bool {
    jackioh_engine::prelude::steppable_params(s.state(), s.card(card), direction)
        .iter()
        .any(|item| item.param.key == key)
}

/// `can_tune_number` for an Upgrade.
#[cfg(test)]
pub(crate) fn can_upgrade_number(s: &jackioh_engine::testkit::Scenario, card: &str, key: &str) -> bool {
    can_tune_number(s, card, key, jackioh_engine::effects::TuneDirection::Upgrade)
}

/// `can_tune_number` for a Degrade.
#[cfg(test)]
pub(crate) fn can_degrade_number(s: &jackioh_engine::testkit::Scenario, card: &str, key: &str) -> bool {
    can_tune_number(s, card, key, jackioh_engine::effects::TuneDirection::Degrade)
}

/// `tune_number` for a Degrade: the number one step worse.
#[cfg(test)]
pub(crate) fn degrade_number(s: &mut jackioh_engine::testkit::Scenario, card: &str, key: &str) -> i32 {
    tune_number(s, card, key, jackioh_engine::effects::TuneDirection::Degrade)
}

/// TS `s.unit(p, lane)?.id ?? ""`: the unit's instance id, or blank for an empty lane.
#[cfg(test)]
pub(crate) fn unit_or_blank(
    s: &jackioh_engine::testkit::Scenario,
    player: jackioh_engine::PlayerId,
    lane: i32,
) -> String {
    s.unit(player, lane).map(|unit| unit.id).unwrap_or_default()
}

/// TS `toMatchObject`: every key the pattern names holds a matching value; arrays match item by item.
#[cfg(test)]
pub(crate) fn matches_object(actual: &serde_json::Value, pattern: &serde_json::Value) -> bool {
    use serde_json::Value;
    match (actual, pattern) {
        (Value::Object(actual), Value::Object(pattern)) => pattern
            .iter()
            .all(|(key, want)| actual.get(key).is_some_and(|got| matches_object(got, want))),
        (Value::Array(actual), Value::Array(pattern)) => {
            actual.len() == pattern.len()
                && actual
                    .iter()
                    .zip(pattern)
                    .all(|(got, want)| matches_object(got, want))
        }
        _ => actual == pattern,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The catalog parses into `CardDef`s and writes back exactly the JSON it was read from, so the
    /// wire types lose and invent nothing (SURFACE §5.1).
    #[test]
    fn the_catalog_round_trips_through_card_defs() {
        let raw: serde_json::Value = serde_json::from_str(catalog_json()).expect("catalog.json is JSON");
        let typed = serde_json::to_value(&*CATALOG).expect("CardDefs serialise");
        assert_eq!(typed, raw);
        assert_eq!(CATALOG_IDS.first().map(String::as_str), Some("core-001"));
        assert_eq!(card_def("core-002").name, "Bigot");
        assert_eq!(card_def_by_index(SetName::Core, "2").id, "core-002");
    }

    #[test]
    fn the_catalog_version_is_the_newest_patch() {
        let patches: serde_json::Value =
            serde_json::from_str(include_str!("../patches/patches.json")).expect("patches.json is JSON");
        let newest = patches
            .as_array()
            .and_then(|p| p.last())
            .and_then(|p| p.get("version"))
            .cloned();
        assert_eq!(newest, Some(serde_json::Value::from(catalog_version())));
    }
}
