// GENERATED by packages/cards/scripts/gen-registry.ts — DO NOT EDIT THIS FILE BY HAND.
//
// One `import * as` per card script file in `src/scripts/`, in SPEC §5 index order, and the
// array `src/index.ts` folds into `CARDS` (BUILD M4-T2). `src/**` is pure, so the registry
// cannot read the directory itself (CLAUDE.md rule 4); this file is that directory read,
// frozen into static imports.
//
// Regenerate after adding, renaming or deleting a card script:
//   pnpm exec tsx packages/cards/scripts/gen-registry.ts
//
// `CardModule` is a type-only import, so it is erased at runtime (verbatimModuleSyntax): the
// index.ts -> _generated.ts -> index.ts cycle exists for the type checker only.

import type { CardModule } from "../index";

import * as m001_big_d_fender from "./001-big-d-fender";
import * as m002_bigot from "./002-bigot";
import * as m003_right_house_defender from "./003-right-house-defender";
import * as m004_gary_the_gambler from "./004-gary-the-gambler";
import * as m005_stockpile from "./005-stockpile";
import * as m006_mana_well from "./006-mana-well";
import * as m007_jewelosco_scarab from "./007-jewelosco-scarab";
import * as m008_mr_vanilla from "./008-mr-vanilla";
import * as m009_moths_to_the_flame from "./009-moths-to-the-flame";
import * as m010_rapid_replenish from "./010-rapid-replenish";
import * as m011_tempo_timmy from "./011-tempo-timmy";
import * as m012_duplicating_felinors from "./012-duplicating-felinors";
import * as m013_jlockeed_shredder_10 from "./013-jlockeed-shredder-10";
import * as m014_jlockeeds_weapons from "./014-jlockeeds-weapons";
import * as m015_me_and_mr_token from "./015-me-and-mr-token";
import * as m016_hit_job from "./016-hit-job";
import * as m017_flood from "./017-flood";
import * as m018_bread_and_butter from "./018-bread-and-butter";
import * as m019_midrange_menace from "./019-midrange-menace";
import * as m020_pointmaster from "./020-pointmaster";
import * as m021_hinder from "./021-hinder";
import * as m022_carnivorous_cube from "./022-carnivorous-cube";
import * as m023_reoccurring_dream from "./023-reoccurring-dream";
import * as m024_efficiency_dividend from "./024-efficiency-dividend";
import * as m025_4_mana_7_7 from "./025-4-mana-7-7";
import * as m026_glowy_jelly_bean from "./026-glowy-jelly-bean";
import * as m027_blood_ridden_glowy_jelly_bean from "./027-blood-ridden-glowy-jelly-bean";
import * as m028_knockoff_temu_glowy_jelly_bean from "./028-knockoff-temu-glowy-jelly-bean";
import * as m029_giga_glowy_jelly_bean from "./029-giga-glowy-jelly-bean";
import * as m030_archivist from "./030-archivist";
import * as m031_kys_math_equation from "./031-kys-math-equation";
import * as m032_prem_panther from "./032-prem-panther";
import * as m033_unstable_clone_machine from "./033-unstable-clone-machine";
import * as m034_collateral_damage from "./034-collateral-damage";
import * as m035_lunar_eclipse from "./035-lunar-eclipse";
import * as m036_magic_jammed from "./036-magic-jammed";
import * as m037_gravedigger from "./037-gravedigger";
import * as m038_quickstriker from "./038-quickstriker";
import * as m039_recycling_initiative from "./039-recycling-initiative";
import * as m040_echoes_of_the_forgotten from "./040-echoes-of-the-forgotten";
import * as m041_sheepish from "./041-sheepish";
import * as m042_eugenics from "./042-eugenics";
import * as m043_big_felinor from "./043-big-felinor";
import * as m044_true_strike from "./044-true-strike";
import * as m045_deft_duelist from "./045-deft-duelist";
import * as m046_suppressive_aura from "./046-suppressive-aura";
import * as m047_fig_of_life from "./047-fig-of-life";
import * as m048_5pek_controller from "./048-5pek-controller";
import * as m049_snom_bunny_mind_control from "./049-snom-bunny-mind-control";
import * as m050_k_pop_fanatic from "./050-k-pop-fanatic";
import * as m051_kys_private_tutor from "./051-kys-private-tutor";
import * as m051_1_kys_empty_notebook from "./051-1-kys-empty-notebook";
import * as m052_silly_silas from "./052-silly-silas";
import * as m053_reno from "./053-reno";
import * as m054_straaza from "./054-straaza";
import * as m055_lava_golem from "./055-lava-golem";
import * as m056_jilliax from "./056-jilliax";
import * as m057_conjure_ky from "./057-conjure-ky";
import * as m058_rush_token_farm from "./058-rush-token-farm";
import * as m059_unbiased_immigration from "./059-unbiased-immigration";
import * as m060_bear_honeypot from "./060-bear-honeypot";
import * as m061_prejudiced_postdoc from "./061-prejudiced-postdoc";
import * as m062_friend_of_felinors from "./062-friend-of-felinors";
import * as m063_plastic_surgery from "./063-plastic-surgery";
import * as m064_gifted_program from "./064-gifted-program";
import * as m065_masochism_mask from "./065-masochism-mask";
import * as m065_1_spikey_pillow from "./065-1-spikey-pillow";
import * as m066_the_rock from "./066-the-rock";
import * as m067_zoomerbin_oomen from "./067-zoomerbin-oomen";
import * as m068_twisted_sorcerer from "./068-twisted-sorcerer";
import * as m069_call_to_arms from "./069-call-to-arms";
import * as m070_spiteful_stab from "./070-spiteful-stab";
import * as m071_intern_stimmy from "./071-intern-stimmy";
import * as m072_reminisce from "./072-reminisce";
import * as m073_anti_oneshot_armor from "./073-anti-oneshot-armor";
import * as m074_adaptive_ui from "./074-adaptive-ui";
import * as m075_infinite_reserves from "./075-infinite-reserves";
import * as m076_field_of_dreams from "./076-field-of-dreams";
import * as m077_professor_curvature from "./077-professor-curvature";
import * as m078_fullsend from "./078-fullsend";
import * as m079_twinspell from "./079-twinspell";
import * as m080_zao_gao from "./080-zao-gao";
import * as m081_radiant_saintess from "./081-radiant-saintess";
import * as m082_kys_trial from "./082-kys-trial";
import * as m083_transmogulate from "./083-transmogulate";
import * as m084_going_long from "./084-going-long";
import * as m085_unlicensed_experimentation from "./085-unlicensed-experimentation";
import * as m086_miss_mrow from "./086-miss-mrow";
import * as m087_pocket_chaos from "./087-pocket-chaos";
import * as m088_twisting_nether from "./088-twisting-nether";
import * as m089_corpse_eater from "./089-corpse-eater";
import * as m090_cn_viral_injection from "./090-cn-viral-injection";
import * as m090_1_cn_virus from "./090-1-cn-virus";
import * as m091_fed_fauci from "./091-fed-fauci";
import * as m092_felinor_fiender from "./092-felinor-fiender";
import * as m093_combo_index from "./093-combo-index";
import * as m093_1_combo_fodder from "./093-1-combo-fodder";
import * as m094_genns_greed from "./094-genns-greed";
import * as m095_call_to_chaos from "./095-call-to-chaos";
import * as m095_1_chaos_golem from "./095-1-chaos-golem";
import * as m096_my_pawn from "./096-my-pawn";
import * as m097_zephyrs from "./097-zephyrs";
import * as m098_heroic_power from "./098-heroic-power";
import * as m099_craft_a_card from "./099-craft-a-card";
import * as m100_ceaseless_void from "./100-ceaseless-void";
import * as mt_bread from "./t-bread";
import * as mt_coin from "./t-coin";
import * as mt_felinor from "./t-felinor";
import * as mt_ghoul from "./t-ghoul";
import * as mt_rush from "./t-rush";
import * as mt_sheep from "./t-sheep";
import * as mclassic_001_curse_of_the_forgotten_classic from "./classic/001-curse-of-the-forgotten-classic";
import * as mclassic_002_the_trickster from "./classic/002-the-trickster";
import * as mclassic_003_book_of_heal from "./classic/003-book-of-heal";
import * as mclassic_004_palantir from "./classic/004-palantir";
import * as mclassic_005_tesla from "./classic/005-tesla";
import * as mclassic_006_cloaked_toe_cracker from "./classic/006-cloaked-toe-cracker";
import * as mclassic_007_infiniscepter from "./classic/007-infiniscepter";
import * as mclassic_008_pickle from "./classic/008-pickle";
import * as mclassic_009_income_tax from "./classic/009-income-tax";
import * as mclassic_010_exile from "./classic/010-exile";
import * as mclassic_011_mind_melt from "./classic/011-mind-melt";
import * as mclassic_012_book_of_blood from "./classic/012-book-of-blood";
import * as mclassic_013_boots_on_the_ground from "./classic/013-boots-on-the-ground";
import * as mclassic_014_shadowstep from "./classic/014-shadowstep";
import * as mclassic_015_nose_hunter from "./classic/015-nose-hunter";
import * as mclassic_016_book_of_flame from "./classic/016-book-of-flame";
import * as mclassic_017_counterspell from "./classic/017-counterspell";
import * as mclassic_018_glitch_in_the_system from "./classic/018-glitch-in-the-system";
import * as mclassic_019_lizards_breath from "./classic/019-lizards-breath";
import * as mclassic_020_the_power_to_punish from "./classic/020-the-power-to-punish";
import * as mclassic_021_turtinator from "./classic/021-turtinator";
import * as mclassic_022_mid_runner from "./classic/022-mid-runner";
import * as mclassic_023_devils_pact from "./classic/023-devils-pact";
import * as mclassic_024_book_of_knowledge from "./classic/024-book-of-knowledge";
import * as mclassic_025_lag_in_the_system from "./classic/025-lag-in-the-system";
import * as mclassic_026_rapid_draw from "./classic/026-rapid-draw";
import * as mclassic_027_pestilent_slime from "./classic/027-pestilent-slime";
import * as mclassic_028_second_wind from "./classic/028-second-wind";
import * as mclassic_029_book_of_vital_kill from "./classic/029-book-of-vital-kill";
import * as mclassic_030_recycle from "./classic/030-recycle";
import * as mclassic_031_cookie_guild from "./classic/031-cookie-guild";
import * as mclassic_032_felinor_feelings from "./classic/032-felinor-feelings";
import * as mclassic_033_joro from "./classic/033-joro";
import * as mclassic_034_ancient_acquisition from "./classic/034-ancient-acquisition";
import * as mclassic_035_prep from "./classic/035-prep";
import * as mclassic_036_burn from "./classic/036-burn";
import * as mclassic_037_last_hurrah from "./classic/037-last-hurrah";
import * as mclassic_038_jackiestan_auctioneer from "./classic/038-jackiestan-auctioneer";
import * as mclassic_039_outbreak from "./classic/039-outbreak";
import * as mclassic_040_mc_tech from "./classic/040-mc-tech";
import * as mclassic_041_state_of_the_game from "./classic/041-state-of-the-game";
import * as mclassic_042_transmutable_toxins from "./classic/042-transmutable-toxins";
import * as mclassic_043_plague_nuke from "./classic/043-plague-nuke";
import * as mclassic_044_back_from_the_gy from "./classic/044-back-from-the-gy";
import * as mclassic_045_nature_titan from "./classic/045-nature-titan";
import * as mclassic_plus_040_appropriations from "./classic-plus/040-appropriations";
import * as mclassic_plus_041_kys_constant from "./classic-plus/041-kys-constant";
import * as mclassic_plus_042_kys_test from "./classic-plus/042-kys-test";
import * as mclassic_plus_042_1_kys_gift from "./classic-plus/042-1-kys-gift";
import * as mclassic_plus_043_ai_slop from "./classic-plus/043-ai-slop";
import * as mclassic_plus_044_simplicity_audit from "./classic-plus/044-simplicity-audit";
import * as mclassic_plus_045_complexity_audit from "./classic-plus/045-complexity-audit";
import * as mclassic_plus_062_kys_papaya from "./classic-plus/062-kys-papaya";
import * as mclassic_plus_063_fruit_tree from "./classic-plus/063-fruit-tree";
import * as mclassic_plus_064_mulch_muncher from "./classic-plus/064-mulch-muncher";
import * as mclassic_plus_065_two_grapes from "./classic-plus/065-two-grapes";
import * as mclassic_plus_065_1_rotten_grape from "./classic-plus/065-1-rotten-grape";
import * as mclassic_plus_065_2_normal_grape from "./classic-plus/065-2-normal-grape";
import * as mclassic_plus_065_3_large_grape from "./classic-plus/065-3-large-grape";
import * as mclassic_plus_065_4_golden_grape from "./classic-plus/065-4-golden-grape";
import * as mclassic_plus_065_5_mythic_grape from "./classic-plus/065-5-mythic-grape";
import * as mclassic_plus_066_vine_of_grapes from "./classic-plus/066-vine-of-grapes";
import * as mclassic_plus_067_pear from "./classic-plus/067-pear";
import * as mclassic_plus_068_organic_produce from "./classic-plus/068-organic-produce";
import * as mclassic_plus_069_buff_billy from "./classic-plus/069-buff-billy";
import * as mclassic_plus_070_chaos_machine from "./classic-plus/070-chaos-machine";
import * as mclassic_plus_071_book_of_buff from "./classic-plus/071-book-of-buff";
import * as mclassic_plus_072_book_of_nerf from "./classic-plus/072-book-of-nerf";
import * as mclassic_plus_075_j_lease_j_jungle_ex_plorer from "./classic-plus/075-j-lease-j-jungle-ex-plorer";
import * as mclassic_plus_075_1_j_lease_j_jungle_ex_plorer_pack from "./classic-plus/075-1-j-lease-j-jungle-ex-plorer-pack";
import * as mclassic_plus_076_brother_lar from "./classic-plus/076-brother-lar";
import * as mclassic_plus_076_1_brother_ping from "./classic-plus/076-1-brother-ping";
import * as mclassic_plus_077_anti_softlock from "./classic-plus/077-anti-softlock";
import * as mclassic_plus_t_ai_01_helpful_assistant from "./classic-plus/t-ai-01-helpful-assistant";
import * as mclassic_plus_t_ai_02_scaling_law from "./classic-plus/t-ai-02-scaling-law";
import * as mclassic_plus_t_ai_03_hallucination from "./classic-plus/t-ai-03-hallucination";
import * as mclassic_plus_t_ai_10_fine_tuning from "./classic-plus/t-ai-10-fine-tuning";

export const SCRIPT_MODULES: readonly CardModule[] = [
  m001_big_d_fender,
  m002_bigot,
  m003_right_house_defender,
  m004_gary_the_gambler,
  m005_stockpile,
  m006_mana_well,
  m007_jewelosco_scarab,
  m008_mr_vanilla,
  m009_moths_to_the_flame,
  m010_rapid_replenish,
  m011_tempo_timmy,
  m012_duplicating_felinors,
  m013_jlockeed_shredder_10,
  m014_jlockeeds_weapons,
  m015_me_and_mr_token,
  m016_hit_job,
  m017_flood,
  m018_bread_and_butter,
  m019_midrange_menace,
  m020_pointmaster,
  m021_hinder,
  m022_carnivorous_cube,
  m023_reoccurring_dream,
  m024_efficiency_dividend,
  m025_4_mana_7_7,
  m026_glowy_jelly_bean,
  m027_blood_ridden_glowy_jelly_bean,
  m028_knockoff_temu_glowy_jelly_bean,
  m029_giga_glowy_jelly_bean,
  m030_archivist,
  m031_kys_math_equation,
  m032_prem_panther,
  m033_unstable_clone_machine,
  m034_collateral_damage,
  m035_lunar_eclipse,
  m036_magic_jammed,
  m037_gravedigger,
  m038_quickstriker,
  m039_recycling_initiative,
  m040_echoes_of_the_forgotten,
  m041_sheepish,
  m042_eugenics,
  m043_big_felinor,
  m044_true_strike,
  m045_deft_duelist,
  m046_suppressive_aura,
  m047_fig_of_life,
  m048_5pek_controller,
  m049_snom_bunny_mind_control,
  m050_k_pop_fanatic,
  m051_kys_private_tutor,
  m051_1_kys_empty_notebook,
  m052_silly_silas,
  m053_reno,
  m054_straaza,
  m055_lava_golem,
  m056_jilliax,
  m057_conjure_ky,
  m058_rush_token_farm,
  m059_unbiased_immigration,
  m060_bear_honeypot,
  m061_prejudiced_postdoc,
  m062_friend_of_felinors,
  m063_plastic_surgery,
  m064_gifted_program,
  m065_masochism_mask,
  m065_1_spikey_pillow,
  m066_the_rock,
  m067_zoomerbin_oomen,
  m068_twisted_sorcerer,
  m069_call_to_arms,
  m070_spiteful_stab,
  m071_intern_stimmy,
  m072_reminisce,
  m073_anti_oneshot_armor,
  m074_adaptive_ui,
  m075_infinite_reserves,
  m076_field_of_dreams,
  m077_professor_curvature,
  m078_fullsend,
  m079_twinspell,
  m080_zao_gao,
  m081_radiant_saintess,
  m082_kys_trial,
  m083_transmogulate,
  m084_going_long,
  m085_unlicensed_experimentation,
  m086_miss_mrow,
  m087_pocket_chaos,
  m088_twisting_nether,
  m089_corpse_eater,
  m090_cn_viral_injection,
  m090_1_cn_virus,
  m091_fed_fauci,
  m092_felinor_fiender,
  m093_combo_index,
  m093_1_combo_fodder,
  m094_genns_greed,
  m095_call_to_chaos,
  m095_1_chaos_golem,
  m096_my_pawn,
  m097_zephyrs,
  m098_heroic_power,
  m099_craft_a_card,
  m100_ceaseless_void,
  mt_bread,
  mt_coin,
  mt_felinor,
  mt_ghoul,
  mt_rush,
  mt_sheep,
  mclassic_001_curse_of_the_forgotten_classic,
  mclassic_002_the_trickster,
  mclassic_003_book_of_heal,
  mclassic_004_palantir,
  mclassic_005_tesla,
  mclassic_006_cloaked_toe_cracker,
  mclassic_007_infiniscepter,
  mclassic_008_pickle,
  mclassic_009_income_tax,
  mclassic_010_exile,
  mclassic_011_mind_melt,
  mclassic_012_book_of_blood,
  mclassic_013_boots_on_the_ground,
  mclassic_014_shadowstep,
  mclassic_015_nose_hunter,
  mclassic_016_book_of_flame,
  mclassic_017_counterspell,
  mclassic_018_glitch_in_the_system,
  mclassic_019_lizards_breath,
  mclassic_020_the_power_to_punish,
  mclassic_021_turtinator,
  mclassic_022_mid_runner,
  mclassic_023_devils_pact,
  mclassic_024_book_of_knowledge,
  mclassic_025_lag_in_the_system,
  mclassic_026_rapid_draw,
  mclassic_027_pestilent_slime,
  mclassic_028_second_wind,
  mclassic_029_book_of_vital_kill,
  mclassic_030_recycle,
  mclassic_031_cookie_guild,
  mclassic_032_felinor_feelings,
  mclassic_033_joro,
  mclassic_034_ancient_acquisition,
  mclassic_035_prep,
  mclassic_036_burn,
  mclassic_037_last_hurrah,
  mclassic_038_jackiestan_auctioneer,
  mclassic_039_outbreak,
  mclassic_040_mc_tech,
  mclassic_041_state_of_the_game,
  mclassic_042_transmutable_toxins,
  mclassic_043_plague_nuke,
  mclassic_044_back_from_the_gy,
  mclassic_045_nature_titan,
  mclassic_plus_040_appropriations,
  mclassic_plus_041_kys_constant,
  mclassic_plus_042_kys_test,
  mclassic_plus_042_1_kys_gift,
  mclassic_plus_043_ai_slop,
  mclassic_plus_044_simplicity_audit,
  mclassic_plus_045_complexity_audit,
  mclassic_plus_062_kys_papaya,
  mclassic_plus_063_fruit_tree,
  mclassic_plus_064_mulch_muncher,
  mclassic_plus_065_two_grapes,
  mclassic_plus_065_1_rotten_grape,
  mclassic_plus_065_2_normal_grape,
  mclassic_plus_065_3_large_grape,
  mclassic_plus_065_4_golden_grape,
  mclassic_plus_065_5_mythic_grape,
  mclassic_plus_066_vine_of_grapes,
  mclassic_plus_067_pear,
  mclassic_plus_068_organic_produce,
  mclassic_plus_069_buff_billy,
  mclassic_plus_070_chaos_machine,
  mclassic_plus_071_book_of_buff,
  mclassic_plus_072_book_of_nerf,
  mclassic_plus_075_j_lease_j_jungle_ex_plorer,
  mclassic_plus_075_1_j_lease_j_jungle_ex_plorer_pack,
  mclassic_plus_076_brother_lar,
  mclassic_plus_076_1_brother_ping,
  mclassic_plus_077_anti_softlock,
  mclassic_plus_t_ai_01_helpful_assistant,
  mclassic_plus_t_ai_02_scaling_law,
  mclassic_plus_t_ai_03_hallucination,
  mclassic_plus_t_ai_10_fine_tuning,
];
