// T-ghoul Ghoul Token (SPEC §7, R346, R349, R353): cost 0, Unit/Token, "X/X Unit with Pierce", a
// card of its own in patch v0.1.1 (issue #27). Generated by #74 Adaptive UI, which summons it X/X
// (radiant 3X/3X).
//
// There is no script. Everything the §7 row states is catalog data or an engine rule:
//
//   X/X      — printed 0/0, like the Bread Token (§7): no number can be printed for an X, so the
//              card that summons it passes the X as `statsOverride`, which §10.4 layer 1 reads ahead
//              of the printed face (`faceOf` in engine/src/layers.ts).
//   Pierce   — printed on both catalog faces; §4.4 step 2 reads it off the source through the layers
//              (`damage.pierces`), so every hit it makes ignores Armor (R346).
//   Radiant  — the designer printed no Radiant form, so the catalog marks it `radiantFallback` and
//              R349's fallback applies: made Radiant, it is its base face with its attack and health
//              doubled, the X/X included (`layers.wornStatsOverride`). Its Radiant face in the catalog
//              is that fallback written out: the same Pierce and text, the printed 0/0 doubled.
//   Token    — `token: true` and the `Token` tag keep it out of every random pool (§5.1), and R11
//              makes it cease to exist when it leaves the field (`zones.isUnitToken`).
//
// So both faces run the empty script, as the Rush Token's do.

import type { Script } from "@jackioh/engine";
import { cardDef } from "../catalog-data";

export const def = cardDef("core-t-ghoul");

export const base: Script = {};

/** R349: the fallback Radiant face is data and an engine rule; there is no text for a script to carry. */
export const radiant: Script = base;
