//! #95.1 Chaos Golem (SPEC §8.4, §7, R11, R275, R276). Generated by #95 Call to Chaos's eighth
//! effect.
//!
//! Base: 10/10 "Rush, Lifesteal, Divine Shield, First Strike". Radiant: 20/20 "Charge, Lifesteal,
//! Divine Shield, First Strike" (R276 gave the token a Radiant face: R275 doubles its stats and, a
//! keyword-only unit, trades Rush for the stronger Charge). There is no script: all four keywords
//! and the stats of each face are printed on the catalog, and §10.4 layer 1 reads them off the face
//! the instance's radiant flag picks, so granting any of them here would either duplicate them in the
//! keyword set or re-print a stat the catalog already owns (the contract: a script never restates its
//! card's data).
//!
//! Where each keyword's behaviour lives instead:
//!   Rush          — §4.1: lifts summoning sickness for UNIT targets only, so the turn it arrives it
//!                   may attack a unit but not the hero. `isSick`/`whyCannotAttack` in `combat.ts`.
//!   Charge        — the radiant face's in Rush's place: no summoning sickness at all, so a Golem
//!                   made Radiant the turn it arrived may attack the hero at once (§5.2: a keyword
//!                   the radiant face gains applies immediately).
//!   Lifesteal     — §4.4 step 8: heals its controller's hero by the amount actually dealt, after
//!                   Armor and the Anti-oneshot cap, and by nothing when R63 reduced the hit to 0.
//!   Divine Shield — §4.4 step 1: negates the whole first hit and is spent (`divineShieldSpent`),
//!                   and R63's zero rule keeps the shield when the hit was 0 to begin with.
//!   First Strike  — §4.3: it deals its damage before the defender strikes back, so a defender it
//!                   kills never hits it.
//!
//! R11 and §7 are the rest of the card, and are likewise data: `token: true` with `type: "Unit"`
//! makes `isUnitToken` true, so `moveToZone` has it cease to exist the moment it leaves the field —
//! bounce, destroy, exile or transform — and it never enters a graveyard or exile, which is also why
//! it can never feed #89 Corpse Eater (R11).

use jackioh_engine::prelude::*;

pub const ID: &str = "core-095-1";

pub fn script() -> CardScripts {
    let base = Script::default();

    // The radiant face differs in data only — 20/20, Charge for Rush — which layer 1 reads off
    // `def.radiant`; neither face has text a script would carry, so the radiant Script is the base one.
    let radiant = base.clone();

    CardScripts { base, radiant }
}

// #95.1 Chaos Golem (SPEC §8.4, §7, §6.1, §4.3, §4.4; R11, R275, R276). BUILD M4-T4 row 95.1: "10/10
// Rush, Lifesteal, Divine Shield, First Strike; radiant 20/20 with Charge". The token's own cases, on
// its own: #95 Call to Chaos summoning it, and a Golem made Radiant mid-turn, are in
// `c095_call_to_chaos.rs`, beside the card that makes it.
#[cfg(test)]
mod tests {
    use jackioh_engine::testkit::*;

    const P1: PlayerId = PlayerId::P1;
    const P2: PlayerId = PlayerId::P2;

    const GOLEM: &str = "core-095-1"; // Unit token, 10/10 → 20/20
    /// #61 Postdoc is a 2/4 with no Taunt, so nothing but the Golem's own keywords decides a target.
    const POSTDOC: &str = "core-061";
    /// A radiant #91 Fed Fauci is 2/12: it survives a 10-attack First Strike and strikes back.
    const FAUCI: &str = "core-091";
    /// A radiant #19 Menace is 18/18: it survives the Golem's 10 and kills an unshielded 10/10.
    const MENACE: &str = "core-019";
    /// §2.5/R82 TURN ANCHOR. #10 Rapid Replenish is a 0-cost Spell, always an affordable play, so one
    /// in hand keeps p1's turn from auto-ending under the assertions.
    const ANCHOR: &str = "core-010";

    fn golem_of(s: &Scenario) -> CardInstance {
        s.unit(P1, 1)
            .unwrap_or_else(|| panic!("expected p1's Chaos Golem in lane 1"))
    }

    fn enemy_of(s: &Scenario) -> CardInstance {
        s.unit(P2, 1)
            .unwrap_or_else(|| panic!("expected p2's unit in lane 1"))
    }

    /// The face's keywords, sorted, as the view prints them.
    fn keywords_of(s: &Scenario, card: &CardInstance) -> Vec<String> {
        let mut out: Vec<String> = s
            .stats(card)
            .keywords
            .iter()
            .map(|keyword| crate::js(keyword)["kind"].as_str().unwrap_or_default().to_string())
            .collect();
        out.sort();
        out
    }

    /// §4.1: the scenario places units that arrived on an earlier turn; this one arrived now.
    fn arrived_this_turn(s: &mut Scenario, card: &CardInstance) {
        let turn = s.state().turn;
        s.card_mut(card).summoned_turn = Some(turn);
    }

    mod n95_1_chaos_golem_base {
        use super::*;

        #[test]
        fn s7_a_10_10_whose_four_keywords_are_printed_data_with_no_script_on_either_face() {
            crate::register_all();
            let mut s = scenario(json!({ "p1": { "field": [GOLEM], "hand": [ANCHOR] } }));
            let golem = golem_of(&s);

            s.expect_stats(&golem, json!({ "attack": 10, "health": 10, "maxHealth": 10 }));
            assert_eq!(
                keywords_of(&s, &golem),
                vec!["Divine Shield", "First Strike", "Lifesteal", "Rush"]
            );
            let scripts = super::super::script();
            assert!(scripts.base.cry.is_none() && scripts.radiant.cry.is_none());
            assert!(scripts.base.targets.is_empty() && scripts.radiant.targets.is_empty());
        }

        #[test]
        fn s6_1_rush_on_the_turn_it_arrives_it_may_attack_a_unit_and_first_strike_kills_it_untouched() {
            crate::register_all();
            let mut s = scenario(json!({
                "p1": { "field": [GOLEM], "hand": [ANCHOR] },
                "p2": { "field": [POSTDOC] },
            }));
            let golem = golem_of(&s);
            arrived_this_turn(&mut s, &golem);

            s.expect_refused_with(|s| s.attack(&golem, "hero"), "Rush cannot hit the hero");
            let postdoc = enemy_of(&s);
            s.attack(&golem, &postdoc);

            // §4.3: its 10 lands first and kills the 2/4, which never strikes back.
            s.expect_in_zone(&postdoc, "graveyard");
            s.expect_stats(&golem, json!({ "health": 10 }));
            assert!(s.card(&golem).divine_shield_spent.is_none());
        }

        #[test]
        fn s4_4_divine_shield_negates_the_hit_back_and_lifesteal_heals_the_10_it_dealt() {
            crate::register_all();
            let mut s = scenario(json!({
                "p1": { "field": [GOLEM], "hand": [ANCHOR], "health": 15 },
                "p2": { "field": [{ "def": FAUCI, "radiant": true }] },
            }));
            let golem = golem_of(&s);
            let fauci = enemy_of(&s);

            s.attack(&golem, &fauci);

            s.expect_stats(&fauci, json!({ "health": 2 })); // 12 − 10
            s.expect_stats(&golem, json!({ "health": 10 })); // the 2 back, negated whole
            assert_eq!(s.card(&golem).divine_shield_spent, Some(true));
            s.expect_health(P1, 25); // 15 + the 10 dealt
        }

        #[test]
        fn r11_a_unit_token_that_dies_ceases_to_exist_and_reaches_no_graveyard() {
            crate::register_all();
            let mut s = scenario(json!({
                "p1": { "field": [GOLEM], "hand": [ANCHOR] },
                "p2": { "field": [{ "def": MENACE, "radiant": true }] },
            }));
            let golem = golem_of(&s);
            // The state one blocked hit leaves (§4.4 step 1), so this one exchange is lethal.
            s.card_mut(&golem).divine_shield_spent = Some(true);
            let menace = enemy_of(&s);

            s.attack(&golem, &menace);

            s.expect_in_zone(&golem, "gone");
            assert!(!s.pile(P1, "graveyard").iter().any(|card| card.def_id == GOLEM));
        }
    }

    mod n95_1_chaos_golem_radiant {
        use super::*;

        #[test]
        fn r275_a_20_20_with_charge_in_rush_s_place() {
            crate::register_all();
            let mut s = scenario(json!({
                "p1": { "field": [{ "def": GOLEM, "radiant": true }], "hand": [ANCHOR] },
            }));
            let golem = golem_of(&s);

            s.expect_stats(&golem, json!({ "attack": 20, "health": 20, "maxHealth": 20 }));
            assert_eq!(
                keywords_of(&s, &golem),
                vec!["Charge", "Divine Shield", "First Strike", "Lifesteal"]
            );
        }

        #[test]
        fn r275_charge_on_the_turn_it_arrives_it_may_hit_the_hero_and_lifesteal_heals_the_20() {
            crate::register_all();
            let mut s = scenario(json!({
                "p1": { "field": [{ "def": GOLEM, "radiant": true }], "hand": [ANCHOR], "health": 5 },
            }));
            let golem = golem_of(&s);
            arrived_this_turn(&mut s, &golem);

            s.attack(&golem, "hero");

            s.expect_health(P2, 10); // 30 − 20
            s.expect_health(P1, 25); // 5 + the 20 dealt
        }
    }
}
