//! T-bread Bread Token (SPEC §7, R37): cost 0, Unit/Token, printed 0/0, no text, radiant form X/X, Armor X.
//! Generated by #18 Bread and Butter only.
//!
//! R37 is the whole card: the source names no token ("a X/X Token"), so the spec names it Bread
//! Token, gives it cost 0 and no keywords, and says "it counts as a Token for every filter" — which
//! `catalog.json`'s `token: true` plus the `Token` tag already do (§5.1, `asksForTokens` in
//! engine/src/catalog.ts). There is nothing for a script to add.
//!
//! PRINTED 0/0 AND THE X/X IT IS ALWAYS SUMMONED AS (§7 "Stat overrides", R37, R52).
//! §7: "Printed 0/0; always summoned as X/X through `statsOverride`". The override is instance data
//! (§10.1) written by the `summon` verb, and §10.4 layer 1 reads it AHEAD of the printed face —
//! `faceOf` (engine/src/layers.ts) is `instance.statsOverride?.attack ?? face.attack`, so a Bread
//! Token summoned as 3/3 is a 3/3 everywhere, with the printed 0/0 only ever showing through the def.
//! A Bread Token that somehow reaches the field with no override is its printed 0/0 and dies at the
//! next state check (§4.5) — and being a unit token it ceases to exist rather than reaching a
//! graveyard (R11).
//!
//! The X itself belongs to #18, not here: "X = that player's unspent mana" at the end-of-turn trap
//! window (R62), radiant 3X, and R52 gives the token to the TRAP'S controller whichever player ended
//! the turn with mana left. A reviewer should look for all of that in `src/scripts/018-…`, which
//! calls `summon({ defId: "core-t-bread", statsOverride: { attack: x, health: x } })`.
//! R57 keeps that `statsOverride` on a copy, and R78 clears it when the token leaves the field —
//! both engine-side, neither this card's.
//!
//! Radiant form: §7 prints X/X, Armor X (issue #1). The radiant catalog face carries the Armor, and
//! the X rides on the instance as `armorOverride` beside `statsOverride` (§10.4 layer 1, `faceOf`), so
//! the radiant Script is the base Script itself: neither face has text a script would carry.

use jackioh_engine::prelude::*;

pub const ID: &str = "core-t-bread";

pub fn script() -> CardScripts {
    let base = Script::default();
    CardScripts {
        // §7's radiant X/X, Armor X is the catalog face plus the instance's overrides; there is no script.
        radiant: base.clone(),
        base,
    }
}

// T-bread Bread Token (SPEC §7, R37; §4.5, §5.1, §10.4, R11, R52, R74). BUILD M4-T4's token row:
// "Vanish on leaving the field; … Bread is X/X with no text; none in random pools".
//
// §7 gives this token NO radiant form, so both `describe`s below prove the same behaviour, once on
// each face, and the data block proves the faces are one face (`def.radiant` equals `def.base`).
//
// R37 and §7's "Stat overrides" bullet are the card: printed 0/0, always summoned as X/X through
// `statsOverride`, so §10.4 layer 1 (`faceOf`) has to read the override rather than the printed
// face. The X itself belongs to #18 Bread and Butter (R52), not here.
#[cfg(test)]
mod tests {
    use super::*;
    use jackioh_engine::catalog::{def_of, query};
    use jackioh_engine::effects::summon;
    use jackioh_engine::layers::{face_of, keywords_of, stats_with_buffs};
    use jackioh_engine::resolve::{HookOptions, apply_effects, make_context};
    use jackioh_engine::state::find_instance;
    use jackioh_engine::testkit::*;
    use jackioh_engine::zones::{MoveResult, OffFieldZone, is_unit_token, move_to_zone};

    const P1: PlayerId = PlayerId::P1;
    const P2: PlayerId = PlayerId::P2;

    const SEED: &str = "t-bread";

    /// TS `Object.keys(script)`: the TS names of the fields a script sets.
    fn set_fields(script: &Script) -> Vec<&'static str> {
        let mut keys = Vec::new();
        let mut put = |set: bool, key: &'static str| {
            if set {
                keys.push(key);
            }
        };
        put(script.cost.is_some(), "cost");
        put(script.cry.is_some(), "cry");
        put(script.death.is_some(), "death");
        put(script.start_of_game.is_some(), "startOfGame");
        put(!script.resume.is_empty(), "resume");
        put(script.delayed.is_some(), "delayed");
        put(script.set_stat.is_some(), "setStat");
        put(script.start_of_turn.is_some(), "startOfTurn");
        put(script.end_of_turn.is_some(), "endOfTurn");
        put(script.aura.is_some(), "aura");
        put(!script.triggers.is_empty(), "triggers");
        put(script.on_play_hook.is_some(), "onPlayHook");
        put(!script.hand_triggers.is_empty(), "handTriggers");
        put(script.static_flags.is_some(), "staticFlags");
        put(!script.targets.is_empty(), "targets");
        put(!script.modes.is_empty(), "modes");
        put(script.condition_met.is_some(), "conditionMet");
        put(script.preview.is_some(), "preview");
        put(!script.activations.is_empty(), "activations");
        put(!script.target_checks.is_empty(), "targetChecks");
        put(script.cost_aura.is_some(), "costAura");
        put(script.graveyard_play.is_some(), "graveyardPlay");
        put(script.targeting_discards.is_some(), "targetingDiscards");
        put(script.records_play_as.is_some(), "recordsPlayAs");
        put(script.draw_limit.is_some(), "drawLimit");
        put(!script.replacements.is_empty(), "replacements");
        put(script.hero_guard.is_some(), "heroGuard");
        put(script.conditional_keywords.is_some(), "conditionalKeywords");
        put(script.after_attack.is_some(), "afterAttack");
        put(script.plague_multiplier.is_some(), "plagueMultiplier");
        put(!script.deck_triggers.is_empty(), "deckTriggers");
        put(!script.graveyard_triggers.is_empty(), "graveyardTriggers");
        put(script.quests.is_some(), "quests");
        put(script.tribute_when.is_some(), "tributeWhen");
        put(script.would_counter.is_some(), "wouldCounter");
        put(script.start_of_opponent_turn.is_some(), "startOfOpponentTurn");
        keys
    }

    /// The ids of a query's answer.
    fn ids<'a>(defs: impl IntoIterator<Item = &'a CardDef>) -> Vec<String> {
        defs.into_iter().map(|entry| entry.id.clone()).collect()
    }

    /// §7: "always summoned as X/X through `statsOverride`", driven the way #18 Bread and Butter drives
    /// it — the shipped definition plus a `statsOverride` on the summon. The `summon` verb itself lets a
    /// test pick any X, a radiant flag and an armor override; the tests below that play #18 prove the
    /// card's own path.
    ///
    /// `args` is TS's `{ statsOverride?, radiant?, armorOverride? }`, spread into the summon.
    fn summon_bread_token(s: &mut Scenario, args: Value) -> CardInstance {
        let mut summon_args = json!({ "defId": ID, "player": "self", "lane": 1 });
        if let Some(extra) = args.as_object() {
            for (key, value) in extra {
                summon_args[key.as_str()] = value.clone();
            }
        }
        let effects = vec![summon(json_as(summon_args))];
        let state = s.state_mut();
        let mut rng = Rng::new(&state.seed, state.rng_cursor);
        let mut events: Vec<GameEvent> = Vec::new();
        {
            let mut sink = EngineSink::new(&mut *state, &mut events, &mut rng);
            let mut ctx = make_context(
                &mut sink,
                None,
                HookOptions {
                    controller: Some(P1),
                    ..Default::default()
                },
            );
            apply_effects(&effects, &mut ctx);
        }
        state.rng_cursor = rng.cursor();
        s.unit(P1, 1).expect("the summon should have put a Bread Token in p1's lane 1")
    }

    mod t_bread_bread_token_spec_s7_r37 {
        use super::*;

        mod card_data_s7_r37 {
            use super::*;

            #[test]
            fn r37_names_the_unnamed_x_x_token_gives_it_cost_0_printed_0_0_and_no_text_or_keywords() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.index, "T-bread");
                assert_eq!(def.name, "Bread Token");
                assert_eq!(serde_json::to_value(def.cost).unwrap(), json!(0));
                assert_eq!(def.type_, CardType::Unit);
                assert!(def.token);
                assert!(def.tags.contains(&Tag::Token));
                assert_eq!(def.base.attack, Some(0));
                assert_eq!(def.base.health, Some(0));
                assert!(def.base.keywords.is_empty());
                assert_eq!(def.base.text, "");
            }

            #[test]
            fn s7_gives_the_bread_token_a_radiant_face_x_x_with_armor_x_build_m4_t1() {
                crate::register_all();
                let def = crate::card_def(ID);
                // Its X/X is a `statsOverride`, so BOTH printed faces stay 0/0; the radiant one differs by
                // printing Armor, whose `n` is a placeholder the summon fills in for the same reason.
                assert_eq!(def.radiant.attack, Some(0));
                assert_eq!(def.radiant.keywords, vec![Keyword::Armor { n: 0 }]);
                assert!(def.base.keywords.is_empty(), "the base face prints nothing");
            }

            #[test]
            fn s7_needs_no_script_for_either_face_and_the_radiant_script_is_the_base_script_r74() {
                crate::register_all();
                // TS `toEqual({})` and `toBe(base)`: both faces are the empty Script.
                let scripts = script();
                assert!(set_fields(&scripts.base).is_empty());
                assert!(set_fields(&scripts.radiant).is_empty());
            }
        }

        mod base {
            use super::*;

            #[test]
            fn r37_a_bread_token_summoned_with_statsoverride_is_an_x_x_while_its_printed_face_stays_0_0() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED }));
                let token = summon_bread_token(&mut s, json!({ "statsOverride": { "attack": 4, "health": 4 } }));

                assert_eq!(token.def_id, ID);
                // §10.4 layer 1 reads the override ahead of the printed face, and no later layer touches it.
                s.expect_stats(&token, json!({ "attack": 4, "health": 4, "maxHealth": 4 }));
                let face = face_of(s.state(), &token);
                assert_eq!((face.attack, face.health), (4, 4));
                assert!(face.keywords.is_empty());
                let buffed = stats_with_buffs(s.state(), &token);
                assert_eq!((buffed.attack, buffed.max_health), (4, 4));
                // The definition is untouched: the X lives on the instance (§10.1), not on the card.
                assert_eq!(def_of(Some(s.state()), &token.def_id).base.attack, Some(0));
                assert_eq!(def_of(Some(s.state()), &token.def_id).base.health, Some(0));
            }

            #[test]
            fn r37_a_bread_token_has_no_keywords_and_no_text_of_its_own_at_any_x() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": "core-t-bread", "statsOverride": { "attack": 9, "health": 9 } }] },
                }));
                let token = s.unit(P1, 1).unwrap();

                s.expect_stats(&token, json!({ "attack": 9, "health": 9, "maxHealth": 9 }));
                assert!(keywords_of(s.state(), &token).is_empty());
                assert_eq!(def_of(Some(s.state()), &token.def_id).base.text, "");
                assert_eq!(
                    def_of(Some(s.state()), &token.def_id).radiant.text,
                    "Armor X",
                    "the radiant face does"
                );
            }

            #[test]
            fn s7_and_s4_5_with_no_override_a_bread_token_is_its_printed_0_0_so_it_dies_at_the_state_check() {
                crate::register_all();
                // The harness settles the board once after setup (§4.5), exactly as play would.
                let s = scenario(json!({ "seed": SEED, "p1": { "field": ["core-t-bread"] } }));

                assert!(s.unit(P1, 1).is_none());
                // R11: it died as a unit token, so it is in no pile.
                assert!(s.pile(P1, "graveyard").is_empty());
                assert!(s.pile(P1, "exile").is_empty());
            }

            #[test]
            fn r11_a_bread_token_that_dies_in_combat_ceases_to_exist_and_never_reaches_a_graveyard() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": "core-t-bread", "statsOverride": { "attack": 3, "health": 3 } }] },
                    "p2": { "field": ["core-025"] },
                }));
                let token = s.unit(P1, 1).unwrap();
                assert!(is_unit_token(s.state(), &token));

                let wall = s.unit(P2, 1).unwrap();
                s.attack(&token, &wall);

                s.expect_events(json!("destroyed"));
                s.expect_in_zone(&token, "gone");
                // R11: "nothing can reach it again" — the engine's own lookup no longer finds it. (The
                // instance this test holds is a pre-`reduce` snapshot, so its own `zone` is stale; the
                // `gone` tag is asserted below, where `moveToZone` mutates the live instance in place.)
                assert!(find_instance(s.state(), &token.id).is_none());
                assert!(s.pile(P1, "graveyard").is_empty());
                assert!(s.pile(P1, "exile").is_empty());
            }

            #[test]
            fn r11_an_exiled_bread_token_ceases_to_exist_rather_than_entering_the_exile_pile() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED }));
                let mut token = summon_bread_token(&mut s, json!({ "statsOverride": { "attack": 2, "health": 2 } }));

                // Called directly so this test holds the instance the engine mutates (`reduce` clones).
                let moved = move_to_zone(s.state_mut(), &mut token, OffFieldZone::Exile, Default::default());
                assert!(matches!(moved, MoveResult::Vanished));

                s.expect_in_zone(&token, "gone");
                assert_eq!(token.zone.z(), ZoneName::Gone);
                assert!(s.pile(P1, "exile").is_empty());
            }

            #[test]
            fn r11_a_unit_token_never_enters_a_graveyard_or_exile_so_a_fixture_may_not_put_one_there() {
                crate::register_all();
                expect_throw_with(
                    || {
                        scenario(json!({ "seed": SEED, "p1": { "graveyard": ["core-t-bread"] } }));
                    },
                    "unit token",
                );
                expect_throw_with(
                    || {
                        scenario(json!({ "seed": SEED, "p1": { "exile": ["core-t-bread"] } }));
                    },
                    "unit token",
                );
            }

            #[test]
            fn s5_1_and_r37_the_bread_token_counts_as_a_token_for_every_filter_so_query_hides_it() {
                crate::register_all();
                let id = ID.to_string();

                assert!(!ids(query(&json_as(json!({ "type": "Unit" })))).contains(&id));
                assert!(!ids(query(&json_as(json!({ "cost": 0 })))).contains(&id));
                assert!(!ids(query(&json_as(json!({ "costRange": { "min": 0, "max": 0 } })))).contains(&id));
                assert!(ids(query(&json_as(json!({ "token": true })))).contains(&id));
                assert_eq!(ids(query(&json_as(json!({ "defId": "core-t-bread" })))), vec![id]);
            }

            #[test]
            fn s7_r52_and_r62_n18_bread_and_butter_summons_this_token_as_x_x_for_the_trap_s_controller_at_the_opponent_s_end_of_turn() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "active": "p2",
                    "p1": { "backrow": ["core-018"], "library": ["core-010"] },
                    "p2": { "mana": 3, "library": ["core-010"] },
                }));

                s.end_turn();

                // R52: p2 ended the turn with 3 unspent, and the token is p1's, the trap's controller.
                let token = s.unit(P1, 1).unwrap();
                assert_eq!(token.def_id, ID);
                s.expect_stats(&token, json!({ "attack": 3, "health": 3, "maxHealth": 3 }));
                assert!(keywords_of(s.state(), &token).is_empty());
                for lane in [1, 2, 3, 4, 5] {
                    assert!(s.unit(P2, lane).is_none());
                }
            }

            #[test]
            fn s7_and_r52_x_0_summons_no_bread_token_at_all_not_a_0_0_that_dies() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "backrow": ["core-018"], "mana": 0, "library": ["core-010"] },
                    "p2": { "library": ["core-010"] },
                }));

                s.end_turn();

                assert!(!s.events().iter().any(|event| event.event_type() == GameEventType::Summoned));
                for lane in [1, 2, 3, 4, 5] {
                    assert!(s.unit(P1, lane).is_none());
                }
            }
        }

        // §7's "Radiant form" column reads "none", so every case above holds for a radiant instance too:
        // R74 sets the flag, and the flag selects the same face and the same (empty) Script.
        mod radiant_s7_x_x_armor_x {
            use super::*;

            #[test]
            fn s7_a_radiant_bread_token_summoned_as_x_x_carries_armor_x_the_same_x() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED }));
                let token = summon_bread_token(
                    &mut s,
                    json!({ "radiant": true, "statsOverride": { "attack": 6, "health": 6 }, "armorOverride": 6 }),
                );

                assert!(token.radiant);
                s.expect_stats(&token, json!({ "attack": 6, "health": 6, "maxHealth": 6 }));
                let face = face_of(s.state(), &token);
                assert_eq!((face.attack, face.health), (6, 6));
                assert_eq!(face.keywords, vec![Keyword::Armor { n: 6 }]);
                assert_eq!(keywords_of(s.state(), &token), vec![Keyword::Armor { n: 6 }]);
            }

            /// Without the override the printed placeholder stands, which is Armor 0 — not Armor X.
            #[test]
            fn s7_a_radiant_bread_token_with_no_armor_override_reads_the_printed_armor_0() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED }));
                let token = summon_bread_token(
                    &mut s,
                    json!({ "radiant": true, "statsOverride": { "attack": 6, "health": 6 } }),
                );

                assert_eq!(keywords_of(s.state(), &token), vec![Keyword::Armor { n: 0 }]);
            }

            #[test]
            fn s7_a_radiant_bread_token_with_no_override_is_the_same_printed_0_0_and_dies_at_the_state_check() {
                crate::register_all();
                let s = scenario(json!({ "seed": SEED, "p1": { "field": [{ "def": "core-t-bread", "radiant": true }] } }));

                assert!(s.unit(P1, 1).is_none());
                assert!(s.pile(P1, "graveyard").is_empty());
            }

            #[test]
            fn r11_a_radiant_bread_token_that_leaves_the_field_ceases_to_exist_just_as_the_base_face_does() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": {
                        "field": [{ "def": "core-t-bread", "radiant": true, "statsOverride": { "attack": 2, "health": 2 } }],
                    },
                }));
                let mut token = s.unit(P1, 1).unwrap();

                let moved = move_to_zone(s.state_mut(), &mut token, OffFieldZone::Graveyard, Default::default());
                assert!(matches!(moved, MoveResult::Vanished));

                s.expect_in_zone(&token, "gone");
                assert_eq!(token.zone.z(), ZoneName::Gone);
                assert!(s.pile(P1, "graveyard").is_empty());
            }
        }
    }
}
