//! T-felinor Felinor Token (SPEC §7, R275): cost 1, Unit/Felinor/Token, 1/1, no text, radiant form
//! 2/2 with Rush. Generated by #62 Friend of Felinors and #98 Heroic Power.
//!
//! There is no script: the Felinor tag is catalog data (`tags: ["Felinor", "Token"]`), and every
//! card that cares reads the def's tags through the engine rather than asking the token anything:
//!   #43 Big Felinor      — `destroyAll({ notTags: ["Felinor"] })`, so it survives the Cry on either face.
//!   #92 Felinor Fiender  — `setStat` (§10.4 layer 2, R39) sums "all your Felinors, including ones
//!                          under a Stack" (R13), and this token is one of them.
//!   #62 / #98            — name this def when they summon it; the summon verb is theirs.
//! The Token tag is the §5.1 pool rule: a Felinor pool never offers this token unless it asks for tokens.
//! 1/1 is printed on the catalog face (§10.4 layer 1), and R11's vanishing is the engine's (see `t_rush.rs`).
//! Radiant form: §7 prints 2/2 with Rush (R275), catalog data on `def.radiant`, so the radiant Script
//! is the base Script itself; Rush is §4.1's.

use jackioh_engine::prelude::*;

pub const ID: &str = "core-t-felinor";

pub fn script() -> CardScripts {
    let base = Script::default();
    CardScripts {
        radiant: base.clone(),
        base,
    }
}

// T-felinor Felinor Token (SPEC §7; §3.2, §4.1, §5.1, §6.1, R11, R64, R74, R275). BUILD M4-T4's
// token row: "Vanish on leaving the field; … none in random pools; radiant … Felinor Token 2/2 Rush".
// The radiant face is data only (R275: double the stats, plus Rush), so both faces prove the shared
// behaviour and the radiant one adds Rush's. The Felinor TAG is proved as catalog data and through
// #43 Big Felinor, whose "destroy all non-Felinor units" must spare it (#92's `setStat` counts it, R39).
#[cfg(test)]
mod tests {
    use super::*;
    use jackioh_engine::catalog::{def_of, query, query_cost};
    use jackioh_engine::layers::keywords_of;
    use jackioh_engine::state::find_instance;
    use jackioh_engine::testkit::*;
    use jackioh_engine::zones::{MoveResult, OffFieldZone, is_unit_token, move_to_zone};

    const P1: PlayerId = PlayerId::P1;
    const P2: PlayerId = PlayerId::P2;

    const SEED: &str = "t-felinor";
    const LANES: [i32; 5] = [1, 2, 3, 4, 5];

    /// #62 Friend of Felinors: "Fill your board with Felinor Tokens" — the token's own summoner.
    const FRIEND_OF_FELINORS: &str = "core-062";
    /// #29 GIGA Glowy Jelly Bean, whose radiant face makes every permanent you control Radiant.
    const GIGA: &str = "core-029";
    /// #4 Gary is a 1/1 with a Cry and nothing else: inert on a `field` setup.
    const GARY: &str = "core-004";
    /// #5 Stockpile: a card in each hand, so §2.5's auto-end stays off the assertions.
    const STOCKPILE: &str = "core-005";

    /// The camelCase names of the fields a script sets.
    fn set_fields(script: &Script) -> Vec<&'static str> {
        let mut keys = Vec::new();
        let mut put = |set: bool, key: &'static str| {
            if set {
                keys.push(key);
            }
        };
        put(script.cost.is_some(), "cost");
        put(script.cry.is_some(), "cry");
        put(script.death.is_some(), "death");
        put(script.start_of_game.is_some(), "startOfGame");
        put(!script.resume.is_empty(), "resume");
        put(script.delayed.is_some(), "delayed");
        put(script.set_stat.is_some(), "setStat");
        put(script.start_of_turn.is_some(), "startOfTurn");
        put(script.end_of_turn.is_some(), "endOfTurn");
        put(script.aura.is_some(), "aura");
        put(!script.triggers.is_empty(), "triggers");
        put(script.on_play_hook.is_some(), "onPlayHook");
        put(!script.hand_triggers.is_empty(), "handTriggers");
        put(script.static_flags.is_some(), "staticFlags");
        put(!script.targets.is_empty(), "targets");
        put(!script.modes.is_empty(), "modes");
        put(script.condition_met.is_some(), "conditionMet");
        put(script.preview.is_some(), "preview");
        put(!script.activations.is_empty(), "activations");
        put(!script.target_checks.is_empty(), "targetChecks");
        put(script.cost_aura.is_some(), "costAura");
        put(script.graveyard_play.is_some(), "graveyardPlay");
        put(script.targeting_discards.is_some(), "targetingDiscards");
        put(script.records_play_as.is_some(), "recordsPlayAs");
        put(script.draw_limit.is_some(), "drawLimit");
        put(!script.replacements.is_empty(), "replacements");
        put(script.hero_guard.is_some(), "heroGuard");
        put(script.conditional_keywords.is_some(), "conditionalKeywords");
        put(script.after_attack.is_some(), "afterAttack");
        put(script.plague_multiplier.is_some(), "plagueMultiplier");
        put(!script.deck_triggers.is_empty(), "deckTriggers");
        put(!script.graveyard_triggers.is_empty(), "graveyardTriggers");
        put(script.quests.is_some(), "quests");
        put(script.tribute_when.is_some(), "tributeWhen");
        put(script.would_counter.is_some(), "wouldCounter");
        put(script.start_of_opponent_turn.is_some(), "startOfOpponentTurn");
        keys
    }

    /// The ids of a query's answer.
    fn ids<'a>(defs: impl IntoIterator<Item = &'a CardDef>) -> Vec<String> {
        defs.into_iter().map(|entry| entry.id.clone()).collect()
    }

    /// Felinor Tokens summoned this turn by #62 (so the one in lane 1 is summoning sick, §4.1), facing #4
    /// Gary in p2's lane 1. No Core card summons the token Radiant, so for `radiantFace` a Radiant #29
    /// turns the fresh tokens Radiant on the field, still on their summon turn, when Rush lets a unit
    /// attack a unit and not the hero (§6.1).
    fn fresh_felinor_token(radiant_face: bool) -> (Scenario, CardInstance, CardInstance) {
        let hand = if radiant_face {
            json!([FRIEND_OF_FELINORS, { "def": GIGA, "radiant": true }, STOCKPILE])
        } else {
            json!([FRIEND_OF_FELINORS, STOCKPILE])
        };
        // R65's printed prices, read off the catalog: exactly the mana the plays below spend.
        let mana = query_cost(&crate::card_def(FRIEND_OF_FELINORS))
            + if radiant_face { query_cost(&crate::card_def(GIGA)) } else { 0 };
        let mut s = scenario(json!({
            "seed": SEED,
            "p1": { "hand": hand, "mana": mana },
            "p2": { "field": [GARY], "hand": [STOCKPILE] },
        }));

        s.play(FRIEND_OF_FELINORS, json!({}));
        if radiant_face {
            s.play(GIGA, json!({}));
        }

        let token = match s.unit(P1, 1) {
            Some(token) if token.def_id == ID => token,
            _ => panic!("#62 should have put a Felinor Token in lane 1"),
        };
        let gary = match s.unit(P2, 1) {
            Some(gary) => gary,
            None => panic!("p2 should have #4 Gary in lane 1"),
        };
        // Still p1's turn, so the refusals below are the fresh token's (§4.1), not the turn's.
        assert_eq!(s.state().active, P1);
        assert_eq!(s.card(&token).radiant, radiant_face);
        (s, token, gary)
    }

    mod t_felinor_felinor_token_spec_s7 {
        use super::*;

        mod card_data_s7 {
            use super::*;

            #[test]
            fn s7_prints_a_1_cost_unit_felinor_token_with_1_1_no_keywords_and_no_text() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.index, "T-felinor");
                assert_eq!(serde_json::to_value(def.cost).unwrap(), json!(1));
                assert_eq!(def.type_, CardType::Unit);
                assert!(def.token);
                assert!(def.tags.contains(&Tag::Felinor));
                assert!(def.tags.contains(&Tag::Token));
                assert_eq!(def.base.attack, Some(1));
                assert_eq!(def.base.health, Some(1));
                assert!(def.base.keywords.is_empty());
                assert_eq!(def.base.text, "");
            }

            #[test]
            fn s7_r275_gives_the_felinor_token_a_radiant_face_2_2_with_rush_build_m4_t1() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.radiant.attack, Some(2));
                assert_eq!(def.radiant.health, Some(2));
                assert_eq!(def.radiant.keywords, vec![Keyword::Rush]);
                assert_eq!(def.base.attack, Some(1), "and the base face is untouched at 1/1");
                assert!(def.base.keywords.is_empty(), "with no keywords");
            }

            #[test]
            fn s7_needs_no_script_for_either_face_and_the_radiant_script_is_the_base_script_r74() {
                crate::register_all();
                let scripts = script();
                assert!(set_fields(&scripts.base).is_empty());
                assert!(set_fields(&scripts.radiant).is_empty());
            }
        }

        mod base {
            use super::*;

            #[test]
            fn s7_and_r64_n62_fills_every_empty_unit_zone_with_1_1_felinor_tokens() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "hand": ["core-062"] } }));

                s.play("core-062", json!({}));

                for lane in LANES {
                    let token = s.unit(P1, lane);
                    assert_eq!(
                        token.as_ref().map(|card| card.def_id.as_str()),
                        Some(ID),
                        "lane {lane} should hold a Felinor Token"
                    );
                    let token = token.unwrap();
                    s.expect_stats(&token, json!({ "attack": 1, "health": 1, "maxHealth": 1 }));
                    assert!(keywords_of(s.state(), &token).is_empty());
                }
            }

            #[test]
            fn s7_the_felinor_token_carries_the_felinor_tag_so_n43_s_non_felinor_sweep_spares_it() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "hand": ["core-043"], "field": ["core-t-felinor", "core-025"] },
                    "p2": { "field": ["core-025"] },
                }));
                let token = s.unit(P1, 1).unwrap();
                let ally = s.unit(P1, 2).unwrap();
                let enemy = s.unit(P2, 1).unwrap();
                assert!(def_of(Some(s.state()), &token.def_id).tags.contains(&Tag::Felinor));

                // Base #43: "Cry: destroy all non-Felinor units on both sides".
                s.play("core-043", json!({}));

                s.expect_in_zone(&token, "field");
                s.expect_stats(&token, json!({ "attack": 1, "health": 1, "maxHealth": 1 }));
                s.expect_in_zone(&ally, "graveyard");
                s.expect_in_zone(&enemy, "graveyard");
                s.expect_in_zone("core-043", "field");
            }

            #[test]
            fn r11_a_felinor_token_that_dies_in_combat_ceases_to_exist_and_never_reaches_a_graveyard() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": ["core-t-felinor"] },
                    "p2": { "field": ["core-025"] },
                }));
                let token = s.unit(P1, 1).unwrap();
                assert!(is_unit_token(s.state(), &token));

                let wall = s.unit(P2, 1).unwrap();
                s.attack(&token, &wall);

                s.expect_events(json!("destroyed"));
                s.expect_in_zone(&token, "gone");
                // R11: "nothing can reach it again". The held instance is a pre-`reduce` snapshot, so
                // its own `zone` is stale; the engine's lookup is the check.
                assert!(find_instance(s.state(), &token.id).is_none());
                assert!(s.pile(P1, "graveyard").is_empty());
                assert!(s.pile(P1, "exile").is_empty());
            }

            #[test]
            fn r11_and_s3_2_bounce_all_units_clears_them_a_bounced_felinor_token_reaches_no_hand() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": ["core-t-felinor"] } }));
                let mut token = s.unit(P1, 1).unwrap();

                // Called directly so this test holds the instance the engine mutates (`reduce` clones).
                let moved = move_to_zone(s.state_mut(), &mut token, OffFieldZone::Hand, Default::default());
                assert!(matches!(moved, MoveResult::Vanished));

                s.expect_in_zone(&token, "gone");
                assert_eq!(token.zone.z(), ZoneName::Gone);
                assert!(s.hand(P1).is_empty());
                assert!(s.unit(P1, 1).is_none());
            }

            #[test]
            fn r11_a_unit_token_never_enters_a_graveyard_or_exile_so_a_fixture_may_not_put_one_there() {
                crate::register_all();
                expect_throw_with(
                    || {
                        scenario(json!({ "seed": SEED, "p1": { "graveyard": ["core-t-felinor"] } }));
                    },
                    "unit token",
                );
                expect_throw_with(
                    || {
                        scenario(json!({ "seed": SEED, "p1": { "exile": ["core-t-felinor"] } }));
                    },
                    "unit token",
                );
            }

            #[test]
            fn s5_1_and_s7_a_felinor_pool_never_offers_the_token_unless_it_also_asks_for_tokens() {
                crate::register_all();
                let id = ID.to_string();

                assert!(!ids(query(&json_as(json!({ "tags": ["Felinor"] })))).contains(&id));
                assert!(!ids(query(&json_as(json!({ "type": "Unit" })))).contains(&id));
                assert!(ids(query(&json_as(json!({ "tags": ["Felinor", "Token"] })))).contains(&id));
                assert!(ids(query(&json_as(json!({ "token": true })))).contains(&id));
                assert_eq!(ids(query(&json_as(json!({ "defId": "core-t-felinor" })))), vec![id]);
            }
        }

        // §7's radiant face is data: R74 sets the flag, and the flag selects the 2/2 Rush face and the same
        // (empty) Script. Every base case holds for a radiant instance, and Rush is added.
        mod radiant_s7_2_2_rush {
            use super::*;

            #[test]
            fn r74_r275_a_radiant_felinor_token_is_a_2_2_with_rush_and_keeps_the_felinor_tag() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": "core-t-felinor", "radiant": true }] },
                }));
                let token = s.unit(P1, 1).unwrap();

                assert!(token.radiant);
                s.expect_stats(&token, json!({ "attack": 2, "health": 2, "maxHealth": 2 }));
                assert_eq!(keywords_of(s.state(), &token), vec![Keyword::Rush]);
                assert!(def_of(Some(s.state()), &token.def_id).tags.contains(&Tag::Felinor));
            }

            #[test]
            fn r275_rush_s6_1_summoned_this_turn_a_radiant_felinor_token_may_attack_a_unit_but_not_the_hero() {
                crate::register_all();
                let (mut s, token, gary) = fresh_felinor_token(true);
                assert_eq!(keywords_of(s.state(), s.card(&token)), vec![Keyword::Rush]);

                s.expect_refused_with(
                    |s| s.attack(&token, "hero"),
                    "Rush cannot hit the hero on its summon turn",
                );
                s.attack(&token, &gary);
                s.expect_in_zone(&gary, "graveyard");
                s.expect_stats(&token, json!({ "attack": 2, "health": 1, "maxHealth": 2 }));
            }

            #[test]
            fn s4_1_the_base_face_has_no_rush_summoned_this_turn_it_may_attack_nothing() {
                crate::register_all();
                let (mut s, token, gary) = fresh_felinor_token(false);
                assert!(keywords_of(s.state(), s.card(&token)).is_empty());

                s.expect_refused_with(|s| s.attack(&token, &gary), "summoning sick");
                s.expect_refused_with(|s| s.attack(&token, "hero"), "summoning sick");
            }

            #[test]
            fn s7_a_radiant_felinor_token_is_spared_by_n43_s_non_felinor_sweep_exactly_as_the_base_face_is() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": {
                        "hand": ["core-043"],
                        "field": [{ "def": "core-t-felinor", "radiant": true }, { "def": "core-025" }],
                    },
                }));
                let token = s.unit(P1, 1).unwrap();
                let ally = s.unit(P1, 2).unwrap();

                s.play("core-043", json!({}));

                s.expect_in_zone(&token, "field");
                s.expect_in_zone(&ally, "graveyard");
            }

            #[test]
            fn r11_a_radiant_felinor_token_that_leaves_the_field_ceases_to_exist_just_as_the_base_face_does() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": "core-t-felinor", "radiant": true }] },
                }));
                let mut token = s.unit(P1, 1).unwrap();

                let moved = move_to_zone(s.state_mut(), &mut token, OffFieldZone::Exile, Default::default());
                assert!(matches!(moved, MoveResult::Vanished));

                s.expect_in_zone(&token, "gone");
                assert_eq!(token.zone.z(), ZoneName::Gone);
                assert!(s.pile(P1, "exile").is_empty());
            }
        }
    }
}
