//! T-ghoul Ghoul Token (SPEC §7, R346, R349, R353): cost 0, Unit/Token, "X/X Unit with Pierce".
//! Generated by #74 Adaptive UI, which summons it X/X (radiant 3X/3X).
//!
//! There is no script. Everything the §7 row states is catalog data or an engine rule:
//!
//!   X/X      — printed 0/0, like the Bread Token (§7): the card that summons it passes the X as
//!              `statsOverride`, which §10.4 layer 1 reads ahead of the printed face.
//!   Pierce   — printed on both catalog faces; §4.4 step 2 reads it through the layers
//!              (`damage.pierces`), so every hit it makes ignores Armor (R346).
//!   Radiant  — no Radiant form is printed, so the catalog marks it `radiantFallback` and R349's
//!              fallback applies: the base face with attack and health doubled, the X/X included
//!              (`layers.wornStatsOverride`).
//!   Token    — `token: true` and the `Token` tag keep it out of every random pool (§5.1), and R11
//!              makes it cease to exist when it leaves the field (`zones.isUnitToken`).
//!
//! So both faces run the empty script, as the Rush Token's do.

use jackioh_engine::prelude::*;

pub const ID: &str = "core-t-ghoul";

pub fn script() -> CardScripts {
    let base = Script::default();
    CardScripts {
        // R349: the fallback Radiant face is data and an engine rule; there is no text for a script to carry.
        radiant: base.clone(),
        base,
    }
}

// T-ghoul Ghoul Token (SPEC §7; R11, R346, R349, R353; §4.4, §5.1, §10.4).
//
// Base: an X/X (the X a `statsOverride`) whose every hit ignores Armor (R346). Radiant: R349's
// fallback, the base face with attack and health doubled, the X/X included.
#[cfg(test)]
mod tests {
    use super::*;
    use jackioh_engine::catalog::query;
    use jackioh_engine::effects::{fuse_cards, set_radiant, summon};
    use jackioh_engine::layers::{face_of, unit_view};
    use jackioh_engine::resolve::{HookOptions, apply_effects, make_context};
    use jackioh_engine::testkit::*;
    use jackioh_engine::zones::is_unit_token;

    const P1: PlayerId = PlayerId::P1;
    const P2: PlayerId = PlayerId::P2;

    const SEED: &str = "t-ghoul";
    /// #25 4-mana 7/7: Armor 7, the wall a plain hit cannot get through.
    const WALL: &str = "core-025";
    /// #84 Going Long: hero Armor 2 on its base price.
    const GOING_LONG: &str = "core-084";

    fn pierce() -> Value {
        json!({ "kind": "Pierce" })
    }

    use crate::js;

    use crate::matches_object;

    /// The names of the fields a script sets.
    fn set_fields(script: &Script) -> Vec<&'static str> {
        let mut keys = Vec::new();
        let mut put = |set: bool, key: &'static str| {
            if set {
                keys.push(key);
            }
        };
        put(script.cost.is_some(), "cost");
        put(script.cry.is_some(), "cry");
        put(script.death.is_some(), "death");
        put(script.start_of_game.is_some(), "startOfGame");
        put(!script.resume.is_empty(), "resume");
        put(script.delayed.is_some(), "delayed");
        put(script.set_stat.is_some(), "setStat");
        put(script.start_of_turn.is_some(), "startOfTurn");
        put(script.end_of_turn.is_some(), "endOfTurn");
        put(script.aura.is_some(), "aura");
        put(!script.triggers.is_empty(), "triggers");
        put(script.on_play_hook.is_some(), "onPlayHook");
        put(!script.hand_triggers.is_empty(), "handTriggers");
        put(script.static_flags.is_some(), "staticFlags");
        put(!script.targets.is_empty(), "targets");
        put(!script.modes.is_empty(), "modes");
        put(script.condition_met.is_some(), "conditionMet");
        put(script.preview.is_some(), "preview");
        put(!script.activations.is_empty(), "activations");
        put(!script.target_checks.is_empty(), "targetChecks");
        put(script.cost_aura.is_some(), "costAura");
        put(script.graveyard_play.is_some(), "graveyardPlay");
        put(script.targeting_discards.is_some(), "targetingDiscards");
        put(script.records_play_as.is_some(), "recordsPlayAs");
        put(script.draw_limit.is_some(), "drawLimit");
        put(!script.replacements.is_empty(), "replacements");
        put(script.hero_guard.is_some(), "heroGuard");
        put(script.conditional_keywords.is_some(), "conditionalKeywords");
        put(script.after_attack.is_some(), "afterAttack");
        put(script.plague_multiplier.is_some(), "plagueMultiplier");
        put(!script.deck_triggers.is_empty(), "deckTriggers");
        put(!script.graveyard_triggers.is_empty(), "graveyardTriggers");
        put(script.quests.is_some(), "quests");
        put(script.tribute_when.is_some(), "tributeWhen");
        put(script.would_counter.is_some(), "wouldCounter");
        put(script.start_of_opponent_turn.is_some(), "startOfOpponentTurn");
        keys
    }

    /// Apply engine effects as p1, the way the card that summons the token would (#74 owns the call).
    fn run(s: &mut Scenario, effects: Vec<Effect>) {
        let state = s.state_mut();
        let mut rng = Rng::new(&state.seed, state.rng_cursor);
        let mut events: Vec<GameEvent> = Vec::new();
        {
            let mut sink = EngineSink::new(&mut *state, &mut events, &mut rng);
            let mut ctx = make_context(
                &mut sink,
                None,
                HookOptions {
                    controller: Some(P1),
                    ..Default::default()
                },
            );
            apply_effects(&effects, &mut ctx);
        }
        state.rng_cursor = rng.cursor();
    }

    fn summon_ghoul(s: &mut Scenario, x: i32, radiant: bool) -> CardInstance {
        let mut args = json!({
            "defId": ID,
            "player": "self",
            "lane": 1,
            "statsOverride": { "attack": x, "health": x },
        });
        if radiant {
            args["radiant"] = json!(true);
        }
        run(s, vec![summon(json_as(args))]);
        let token = s.unit(P1, 1);
        assert_eq!(
            token.as_ref().map(|card| card.def_id.as_str()),
            Some(ID),
            "the summon should have put a Ghoul Token in p1's lane 1"
        );
        token.unwrap()
    }

    mod t_ghoul_ghoul_token_spec_s7_r353 {
        use super::*;

        mod card_data_s7 {
            use super::*;

            #[test]
            fn r353_prints_a_0_cost_unit_token_printed_0_0_for_its_x_x_with_pierce_and_no_other_text() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.id, "core-t-ghoul");
                assert_eq!(def.index, "T-ghoul");
                assert_eq!(def.name, "Ghoul Token");
                assert_eq!(js(&def.cost), json!(0));
                assert_eq!(js(&def.type_), json!("Unit"));
                assert!(def.token);
                assert_eq!(js(&def.tags), json!(["Token"]));
                assert_eq!(
                    js(&def.base),
                    json!({ "attack": 0, "health": 0, "keywords": [pierce()], "text": "Pierce" })
                );
            }

            #[test]
            fn r349_prints_no_radiant_form_so_its_radiant_face_is_the_fallback_the_base_face_doubled() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.radiant_fallback, Some(true));
                let mut doubled = js(&def.base);
                doubled["attack"] = json!(2 * def.base.attack.unwrap_or(0));
                doubled["health"] = json!(2 * def.base.health.unwrap_or(0));
                assert_eq!(js(&def.radiant), doubled);
            }

            #[test]
            fn s7_needs_no_script_for_either_face_and_the_radiant_script_is_the_base_script() {
                crate::register_all();
                // Both faces are the empty Script.
                let scripts = script();
                assert!(set_fields(&scripts.base).is_empty());
                assert!(set_fields(&scripts.radiant).is_empty());
            }

            #[test]
            fn s5_1_is_in_no_random_pool_tokens_are_out_of_every_query_that_does_not_name_them() {
                crate::register_all();
                let all: Vec<String> = query(&json_as(json!({}))).into_iter().map(|card| card.id.clone()).collect();
                assert!(!all.contains(&ID.to_string()));
                let free_units: Vec<String> =
                    query(&json_as(json!({ "type": "Unit", "costRange": { "max": 0 } })))
                        .into_iter()
                        .map(|card| card.id.clone())
                        .collect();
                assert!(!free_units.contains(&ID.to_string()));
            }
        }

        mod base {
            use super::*;

            #[test]
            fn r353_is_the_x_x_its_summon_names_with_pierce_through_s10_4_layer_1() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED }));
                let ghoul = summon_ghoul(&mut s, 3, false);
                s.expect_stats(&ghoul, json!({ "attack": 3, "health": 3, "maxHealth": 3 }));
                assert_eq!(js(&face_of(s.state(), &ghoul)), json!({ "attack": 3, "health": 3, "keywords": [pierce()] }));
                assert_eq!(js(&unit_view(s.state(), &ghoul).keywords), json!([pierce()]));
            }

            #[test]
            fn r346_its_hit_on_a_unit_ignores_that_unit_s_armor_3_through_armor_7() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": ID, "statsOverride": { "attack": 3, "health": 3 } }] },
                    "p2": { "field": [WALL] },
                }));
                let wall = s.unit(P2, 1).unwrap();
                let ghoul = s.unit(P1, 1).unwrap();
                s.attack(&ghoul, &wall);
                s.expect_stats(&wall, json!({ "health": 4, "maxHealth": 7 }));
                let hit = s
                    .last_events()
                    .iter()
                    .map(js)
                    .find(|event| event["type"] == "damage" && event["targetId"] == wall.id.as_str());
                assert!(hit.as_ref().is_some_and(|hit| matches_object(hit, &json!({ "amount": 3, "combat": true }))));
            }

            #[test]
            fn r346_its_hit_on_a_hero_ignores_that_hero_s_armor_n84_going_long() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": ID, "statsOverride": { "attack": 3, "health": 3 } }] },
                    "p2": { "backrow": [GOING_LONG] },
                }));
                assert_eq!(js(&s.view(Some(P2)))["you"]["hero"]["armor"], json!(2));
                let ghoul = s.unit(P1, 1).unwrap();
                s.attack(&ghoul, "hero");
                s.expect_health(P2, 27);
            }

            #[test]
            fn r346_the_unit_it_attacks_still_pays_its_own_armor_on_the_strike_back() {
                crate::register_all();
                // The Ghoul pierces; the wall does not, so its 7 comes back in full against a Ghoul with no
                // Armor, and a Ghoul in Defense Position would take 7 − 1.
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": ID, "statsOverride": { "attack": 9, "health": 9 } }] },
                    "p2": { "field": [WALL] },
                }));
                let ghoul = s.unit(P1, 1).unwrap();
                let wall = s.unit(P2, 1).unwrap();
                s.attack(&ghoul, &wall);
                s.expect_stats(&ghoul, json!({ "health": 2 }));
                let wall_card = s.card(WALL).clone();
                s.expect_in_zone(&wall_card, "graveyard");
            }

            #[test]
            fn r11_a_ghoul_token_that_dies_ceases_to_exist_and_never_reaches_a_graveyard() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": ID, "statsOverride": { "attack": 1, "health": 1 } }] },
                    "p2": { "field": [WALL] },
                }));
                let ghoul = s.unit(P1, 1).unwrap();
                assert!(is_unit_token(s.state(), &ghoul));
                let wall = s.unit(P2, 1).unwrap();
                s.attack(&ghoul, &wall);
                s.expect_in_zone(&ghoul, "gone");
                assert!(s.pile(P1, "graveyard").is_empty());
            }
        }

        mod radiant_r349_s_fallback {
            use super::*;

            #[test]
            fn r349_a_ghoul_summoned_radiant_as_3_3_is_a_6_6_with_pierce_the_x_doubles() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED }));
                let ghoul = summon_ghoul(&mut s, 3, true);
                assert!(ghoul.radiant);
                s.expect_stats(&ghoul, json!({ "attack": 6, "health": 6, "maxHealth": 6 }));
                assert_eq!(js(&unit_view(s.state(), &ghoul).keywords), json!([pierce()]));
            }

            #[test]
            fn r349_a_ghoul_made_radiant_on_the_field_doubles_its_base_stat_layer_and_keeps_its_damage_s5_2() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": ID, "statsOverride": { "attack": 4, "health": 4 }, "damage": 1 }] },
                }));
                let ghoul = s.unit(P1, 1).unwrap();
                s.expect_stats(&ghoul, json!({ "attack": 4, "health": 3, "maxHealth": 4 }));
                run(&mut s, vec![set_radiant(json_as(json!({ "instanceId": ghoul.id })))]);
                s.expect_stats(&ghoul, json!({ "attack": 8, "health": 7, "maxHealth": 8 }));
                assert_eq!(
                    js(&s.card(&ghoul).stats_override),
                    json!({ "attack": 4, "health": 4 }),
                    "the X on the instance is the base face's; the Radiant face reads it doubled"
                );
            }

            #[test]
            fn r349_a_radiant_ghoul_still_pierces() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": ID, "radiant": true, "statsOverride": { "attack": 2, "health": 2 } }] },
                    "p2": { "field": [WALL] },
                }));
                let wall = s.unit(P2, 1).unwrap();
                let ghoul = s.unit(P1, 1).unwrap();
                s.attack(&ghoul, &wall);
                s.expect_stats(&wall, json!({ "health": 3 }));
            }

            #[test]
            fn r349_r77_a_fusion_onto_a_ghoul_sums_its_x_on_the_base_face_and_its_doubled_x_on_the_radiant_face() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": {
                        "field": [{ "def": ID, "statsOverride": { "attack": 3, "health": 3 } }],
                        "hand": ["core-011"],
                    },
                }));
                let ghoul = s.unit(P1, 1).unwrap();
                let timmy = s.hand(Some(P1))[0].clone();
                run(
                    &mut s,
                    vec![fuse_cards(json_as(json!({ "instanceIds": [timmy.id], "targetInstanceId": ghoul.id })))],
                );
                let fused = s.unit(P1, 1).unwrap();
                let fused_def = s.state().transient_defs.get(&fused.def_id).map(js).unwrap_or(Value::Null);
                // #11 Tempo Timmy is 3/3 → 6/6; the Ghoul adds 3/3 on the base face and 6/6 on the Radiant one.
                assert!(matches_object(&fused_def["base"], &json!({ "attack": 6, "health": 6 })));
                assert!(matches_object(&fused_def["radiant"], &json!({ "attack": 12, "health": 12 })));
                let keywords = fused_def["base"]["keywords"].as_array().cloned().unwrap_or_default();
                assert!(keywords.contains(&pierce()));
            }
        }
    }
}
