//! T-rush Rush Token (SPEC §7, R275): cost 1, Unit/Token, 3/3, "Rush", radiant form 6/6, Rush, Cleave.
//! Generated by #15, #58, #60, #75, #80, #95 (Radiant), #98. (#74 summons the Ghoul Token since patch
//! v0.1.1, R353.)
//!
//! There is no script. Everything the §7 row states is either catalog data or an engine rule, and a
//! card file that restated any of it would double it:
//!
//!   3/3 and Rush  — printed on the catalog face. §10.4 layer 1 reads them off the def (`faceOf` in
//!                   engine/src/layers.ts) for both faces, so `grantKeyword({ kind: "Rush" })` here
//!                   would add a second, redundant source of the same keyword. Rush itself is §4.1's
//!                   and §4.2's: it lifts summoning sickness for unit targets only, which
//!                   `combat.ts` enforces (`isSick`, `whyCannotAttack`).
//!   Token         — `token: true` plus the `Token` tag in `catalog.json`, which is what keeps it out
//!                   of every random pool and Discover unless the pool names tokens (§5.1,
//!                   `asksForTokens` in engine/src/catalog.ts).
//!   Vanishing     — R11 and §3.2: a unit token ceases to exist when it leaves the field and never
//!                   enters a graveyard or exile, and a unit-token CARD in a hand or library (#75
//!                   Infinite Reserves, or a copy per R34/R57) ceases to exist if it leaves that zone
//!                   other than by being drawn or played, burning included. That is `isUnitToken` and
//!                   `moveToZone` in engine/src/zones.ts, one rule for every token, so no card file
//!                   owns it. `test/t-rush.test.ts` asserts it rather than implementing it.
//!
//! Radiant form: §7 prints 6/6, Rush, Cleave (issue #1; R275 added Cleave), which is catalog data on
//! `def.radiant` that layer 1 reads off the radiant face, so the radiant Script is the base Script
//! itself: neither face has text a script would carry. Cleave is §4.4 step 10's, a combat rule.
//!
//! WHERE THE §7 "STAT OVERRIDES" BULLET LIVES — NOT HERE. A reviewer should not look for any of
//! these in this file:
//!   #95 Call to Chaos — not one of these any more: it summons five on the token's own Radiant
//!                      face (6/6, §7), a plain `summon` with `radiant: true`.
//!   #58 Rush Token Farm radiant — "+3/+3 to all your Rush Tokens" is an `aura` (§10.4 layer 5) on
//!                      the FIELD SPELL, keyed on this def, so it belongs to `058-…`'s AuraHook.
//!   #75 Infinite Reserves — `staticFlags.infiniteReserves` on #75 puts a Rush Token CARD in hand
//!                      instead of taking fatigue; the card that sits in the hand is this def.
//! A `statsOverride` is instance data (§10.1) that `faceOf` reads ahead of the printed 3/3, so this
//! token needs nothing for any of them.

use jackioh_engine::prelude::*;

pub const ID: &str = "core-t-rush";

pub fn script() -> CardScripts {
    let base = Script::default();
    // §7's radiant 6/6, Rush, Cleave is printed on the catalog face; there is no text for a script to carry.
    let radiant = base.clone();
    CardScripts { base, radiant }
}

// T-rush Rush Token (SPEC §7; R11, R74; §3.2, §5.1, §10.4). BUILD M4-T4's token row: "Vanish on
// leaving the field; … none in random pools".
//
// §7 gives this token a Radiant face that is data only: 6/6 with Rush and Cleave (R275: double the
// stats, and a keyword-only unit adds a keyword). So the radiant Script is still the base Script,
// and the two `describe`s below prove the shared behaviour on each face plus what the radiant face
// adds.
//
// R11 has two halves and each gets its own case: a unit token leaving the FIELD, and a unit-token
// CARD leaving a hand or library other than by being drawn or played (#75 Infinite Reserves).
#[cfg(test)]
mod tests {
    use super::*;
    use jackioh_engine::testkit::*;

    const P1: PlayerId = PlayerId::P1;
    const P2: PlayerId = PlayerId::P2;

    const SEED: &str = "t-rush";

    /// TS `expect(base).toEqual({})`: a Script with no hook, no declaration and no flag.
    fn is_empty_script(script: &Script) -> bool {
        script.cost.is_none()
            && script.cry.is_none()
            && script.death.is_none()
            && script.start_of_game.is_none()
            && script.resume.is_empty()
            && script.delayed.is_none()
            && script.set_stat.is_none()
            && script.start_of_turn.is_none()
            && script.end_of_turn.is_none()
            && script.aura.is_none()
            && script.triggers.is_empty()
            && script.on_play_hook.is_none()
            && script.hand_triggers.is_empty()
            && script.static_flags.is_none()
            && script.targets.is_empty()
            && script.modes.is_empty()
            && script.condition_met.is_none()
            && script.preview.is_none()
            && script.activations.is_empty()
            && script.target_checks.is_empty()
            && script.cost_aura.is_none()
            && script.graveyard_play.is_none()
            && script.targeting_discards.is_none()
            && script.records_play_as.is_none()
            && script.draw_limit.is_none()
            && script.replacements.is_empty()
            && script.hero_guard.is_none()
            && script.conditional_keywords.is_none()
            && script.after_attack.is_none()
            && script.plague_multiplier.is_none()
            && script.deck_triggers.is_empty()
            && script.graveyard_triggers.is_empty()
            && script.quests.is_none()
            && script.tribute_when.is_none()
            && script.would_counter.is_none()
            && script.start_of_opponent_turn.is_none()
    }

    /// The ids of a catalog query's answer (TS `ids(query(…))`).
    fn query_ids(args: Value) -> Vec<String> {
        jackioh_engine::catalog::query(&json_as(args))
            .iter()
            .map(|entry| entry.id.clone())
            .collect()
    }

    /// The (target, amount) of every damage instance this unit dealt, in event order.
    fn hits_from(s: &Scenario, source: &CardInstance) -> Vec<(String, i32)> {
        s.events()
            .iter()
            .filter_map(|event| match event {
                GameEvent::Damage { source_id: Some(from), target_id, amount, .. } if *from == source.id => {
                    Some((target_id.clone(), *amount))
                }
                _ => None,
            })
            .collect()
    }

    /// §7's "Stat overrides" bullet, driven the way an X/X summon drives it (#74 Adaptive UI's Rush Token
    /// was one until patch v0.1.1 gave it a Ghoul Token, R353): the shipped token definition plus a
    /// `statsOverride` on the summon. The summoning card's script owns that call, so
    /// this reaches for the `summon` verb directly rather than for a card that is not this one; the
    /// harness has no `statsOverride` in `FieldSetup`, which is reported as a harness request.
    ///
    /// `args` is TS's `{ statsOverride?, radiant? }`, spread into the summon's literal.
    fn summon_rush_token(s: &mut Scenario, args: Value) -> CardInstance {
        let mut literal = json!({ "defId": ID, "player": "self", "lane": 1 });
        if let (Some(into), Some(extra)) = (literal.as_object_mut(), args.as_object()) {
            for (key, value) in extra {
                into.insert(key.clone(), value.clone());
            }
        }
        let state = s.state_mut();
        let mut events = Vec::new();
        let mut rng = Rng::new(&state.seed, state.rng_cursor);
        {
            let mut sink = EngineSink::new(&mut *state, &mut events, &mut rng);
            let mut ctx = make_context(
                &mut sink,
                None,
                HookOptions { controller: Some(P1), ..Default::default() },
            );
            apply_effects(&[jackioh_engine::effects::summon(json_as(literal))], &mut ctx);
        }
        state.rng_cursor = rng.cursor();
        let token = s.unit(P1, 1);
        assert!(token.is_some(), "the summon should have put a Rush Token in p1's lane 1");
        token.expect("the summon should have put a Rush Token in p1's lane 1")
    }

    mod t_rush_rush_token_spec_s7 {
        use super::*;

        mod card_data_s7 {
            use super::*;

            #[test]
            fn s7_prints_a_1_cost_unit_token_with_3_3_and_rush() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.index, "T-rush");
                assert_eq!(def.cost, CardCost::Fixed(1));
                assert_eq!(def.type_, CardType::Unit);
                assert!(def.token);
                assert!(def.tags.contains(&Tag::Token));
                assert_eq!(def.base.attack, Some(3));
                assert_eq!(def.base.health, Some(3));
                assert_eq!(def.base.keywords, vec![Keyword::Rush]);
            }

            #[test]
            fn s7_r275_gives_the_rush_token_a_radiant_face_6_6_rush_cleave_build_m4_t1() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.radiant.attack, Some(6));
                assert_eq!(def.radiant.health, Some(6));
                assert_eq!(def.radiant.keywords, vec![Keyword::Rush, Keyword::Cleave]);
                assert_eq!(def.base.attack, Some(3), "and the base face is untouched at 3/3");
                assert_eq!(def.base.keywords, vec![Keyword::Rush], "and prints no Cleave");
            }

            #[test]
            fn s7_needs_no_script_for_either_face_and_the_radiant_script_is_the_base_script_r74() {
                crate::register_all();
                let scripts = script();
                assert!(is_empty_script(&scripts.base));
                // TS `toBe(base)`: the radiant face is the base Script itself, so it is empty too.
                assert!(is_empty_script(&scripts.radiant));
            }
        }

        mod base {
            use super::*;

            #[test]
            fn s7_a_rush_token_summoned_by_n15_is_a_3_3_whose_rush_comes_through_unitview_s10_4_layer_1() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "hand": ["core-015"] } }));
                s.play("core-015", json!({}));

                // #15 takes the leftmost free zone itself, so its Cry's token lands in lane 2 (R64).
                let token = s.unit(P1, 2);
                assert_eq!(token.as_ref().map(|card| card.def_id.clone()), Some(ID.to_string()));
                let token = token.expect("a Rush Token in p1's lane 2");
                s.expect_stats(&token, json!({ "attack": 3, "health": 3, "maxHealth": 3 }));
                assert!(unit_view(s.state(), &token).keywords.contains(&Keyword::Rush));
                assert!(unit_has(s.state(), &token, KeywordKind::Rush));
                s.expect_events(json!(["cardPlayed", "summoned"]));
            }

            #[test]
            fn s7_stat_overrides_a_rush_token_summoned_as_5_5_n95_shows_5_5_and_keeps_rush_and_cost_1() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED }));
                let token = summon_rush_token(&mut s, json!({ "statsOverride": { "attack": 5, "health": 5 } }));

                s.expect_stats(&token, json!({ "attack": 5, "health": 5, "maxHealth": 5 }));
                // §10.4 layer 1 reads the override ahead of the printed face; the def is untouched.
                assert_eq!(
                    serde_json::to_value(face_of(s.state(), &token)).expect("faceOf serialises"),
                    json!({ "attack": 5, "health": 5, "keywords": [{ "kind": "Rush" }] })
                );
                assert_eq!(crate::card_def(ID).base.attack, Some(3));
                assert!(unit_has(s.state(), &token, KeywordKind::Rush));
                assert_eq!(def_of(Some(s.state()), &token.def_id).cost, CardCost::Fixed(1));
            }

            #[test]
            fn r11_a_rush_token_that_dies_in_combat_ceases_to_exist_and_never_reaches_a_graveyard_or_exile() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": ["core-t-rush"] }, "p2": { "field": ["core-025"] } }));
                let token = s.unit(P1, 1).expect("a Rush Token in p1's lane 1");
                assert!(is_unit_token(s.state(), &token));

                // 4-mana 7/7 with Armor 7: the token's 3 is absorbed (R63) and the 7 back kills it.
                let defender = s.unit(P2, 1).expect("p2's unit in lane 1");
                s.attack(&token, &defender);

                s.expect_events(json!(["destroyed"]));
                s.expect_in_zone(&token, "gone");
                assert!(s.pile(P1, "graveyard").is_empty());
                assert!(s.pile(P1, "exile").is_empty());
                assert!(s.unit(P1, 1).is_none());
            }

            #[test]
            fn r11_and_s10_1_a_vanished_rush_token_is_in_no_pile_and_its_zone_says_so_tagged_gone() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": ["core-t-rush"] } }));
                let mut token = s.unit(P1, 1).expect("a Rush Token in p1's lane 1");

                // `moveToZone` is called directly so the instance this test holds IS the one the engine
                // mutates (`reduce` clones the state, which would leave a stale snapshot behind).
                let result = move_to_zone(s.state_mut(), &mut token, OffFieldZone::Graveyard, Default::default());

                assert_eq!(result, MoveResult::Vanished);
                s.expect_in_zone(&token, "gone");
                assert!(s.pile(P1, "graveyard").is_empty());
                // R11: "A card that has ceased to exist is in no pile and its zone says so, tagged `gone`
                // (§10.1)". `zones.ts` writes `{ z: "exile" }` instead, which is the engine gap this asserts.
                assert_eq!(token.zone.z(), ZoneName::Gone);
            }

            #[test]
            fn r11_a_unit_token_never_enters_a_graveyard_so_a_fixture_may_not_put_one_there() {
                crate::register_all();
                expect_throw_with(
                    || {
                        scenario(json!({ "seed": SEED, "p1": { "graveyard": ["core-t-rush"] } }));
                    },
                    "unit token",
                );
                expect_throw_with(
                    || {
                        scenario(json!({ "seed": SEED, "p1": { "exile": ["core-t-rush"] } }));
                    },
                    "unit token",
                );
            }

            #[test]
            fn r11_a_rush_token_card_sits_in_a_library_and_a_hand_and_is_drawn_and_played_normally_n75() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "hand": ["core-015"], "library": ["core-t-rush"] } }));
                let card = s.pile(P1, "library").into_iter().next().expect("the Rush Token card in the library");
                s.expect_in_zone(&card, "library");

                s.start_turn();
                s.expect_in_zone(&card, "hand");

                s.play(&card, json!({}));
                s.expect_in_zone(&card, "field");
                s.expect_stats(&card, json!({ "attack": 3, "health": 3, "maxHealth": 3 }));
            }

            #[test]
            fn r11_a_rush_token_card_leaving_a_hand_any_other_way_ceases_to_exist_burning_included() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "hand": ["core-t-rush"] } }));
                let mut card = s.hand(P1).into_iter().next().expect("the Rush Token card in hand");
                s.expect_in_zone(&card, "hand");

                let result = move_to_zone(s.state_mut(), &mut card, OffFieldZone::Graveyard, Default::default());

                assert_eq!(result, MoveResult::Vanished);
                s.expect_in_zone(&card, "gone");
                assert!(s.pile(P1, "graveyard").is_empty());
                assert!(s.hand(P1).is_empty());
            }

            #[test]
            fn s5_1_and_s7_query_never_offers_the_rush_token_unless_the_pool_names_tokens() {
                crate::register_all();
                let id = ID.to_string();

                assert!(!query_ids(json!({ "type": "Unit" })).contains(&id));
                assert!(!query_ids(json!({ "cost": 1 })).contains(&id));
                assert!(query_ids(json!({ "token": true })).contains(&id));
                assert!(query_ids(json!({ "tags": ["Token"] })).contains(&id));
                assert_eq!(query_ids(json!({ "defId": "core-t-rush" })), vec![id]);
            }
        }

        // §7's radiant face is data: R74 sets the flag, the flag selects the 6/6 Rush, Cleave face, and
        // the Script is the same. Every base case holds for a radiant instance, and Cleave is added.
        mod radiant_s7_6_6_rush_cleave {
            use super::*;

            #[test]
            fn r74_r275_a_radiant_rush_token_reads_6_6_with_rush_and_cleave() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": [{ "def": "core-t-rush", "radiant": true }] } }));
                let token = s.unit(P1, 1).expect("a radiant Rush Token in p1's lane 1");

                assert!(token.radiant);
                s.expect_stats(&token, json!({ "attack": 6, "health": 6, "maxHealth": 6 }));
                // The two faces are no longer the same face — that is the whole change.
                let mut flat = token.clone();
                flat.radiant = false;
                assert_ne!(
                    serde_json::to_value(face_of(s.state(), &token)).expect("faceOf serialises"),
                    serde_json::to_value(face_of(s.state(), &flat)).expect("faceOf serialises")
                );
                assert!(unit_view(s.state(), &token).keywords.contains(&Keyword::Rush));
                assert_eq!(keywords_of(s.state(), &token), vec![Keyword::Rush, Keyword::Cleave]);
            }

            #[test]
            fn r275_cleave_a_radiant_rush_token_s_attack_also_hits_the_units_beside_its_target_s3_1_r63() {
                crate::register_all();
                // #61 Postdoc (2/4), #53 Reno (4/6) and #4 Gary (1/1) have a Cry and nothing else, so a
                // `field` setup leaves them inert. The token swings at Reno in the middle.
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": "core-t-rush", "radiant": true }], "hand": ["core-005"] },
                    "p2": { "field": ["core-061", "core-053", "core-004"], "hand": ["core-005"] },
                }));
                let token = s.unit(P1, 1).expect("a radiant Rush Token in p1's lane 1");
                let left = s.unit(P2, 1).expect("p2's unit in lane 1");
                let target = s.unit(P2, 2).expect("p2's unit in lane 2");
                let right = s.unit(P2, 3).expect("p2's unit in lane 3");

                s.attack(&token, &target);

                let hits = hits_from(&s, &token);
                for expected in [(target.id.clone(), 6), (left.id.clone(), 6), (right.id.clone(), 6)] {
                    assert!(hits.contains(&expected), "expected the hit {expected:?} among {hits:?}");
                }
                for unit in [&left, &target, &right] {
                    s.expect_in_zone(unit, "graveyard");
                }
                // Reno's 4 back does not kill a 6/6.
                s.expect_stats(&token, json!({ "health": 2 }));
            }

            #[test]
            fn the_base_face_has_no_cleave_its_attack_hits_the_target_alone() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": ["core-t-rush"], "hand": ["core-005"] },
                    "p2": { "field": ["core-061", "core-004", "core-061"], "hand": ["core-005"] },
                }));
                let token = s.unit(P1, 1).expect("a Rush Token in p1's lane 1");
                let left = s.unit(P2, 1).expect("p2's unit in lane 1");
                let target = s.unit(P2, 2).expect("p2's unit in lane 2");
                let right = s.unit(P2, 3).expect("p2's unit in lane 3");

                s.attack(&token, &target);

                let hit: Vec<String> = hits_from(&s, &token).into_iter().map(|(id, _)| id).collect();
                assert_eq!(hit, vec![target.id.clone()]);
                s.expect_stats(&left, json!({ "health": 4 }));
                s.expect_stats(&right, json!({ "health": 4 }));
            }

            #[test]
            fn s7_stat_overrides_on_the_radiant_face_a_5_5_radiant_rush_token_shows_5_5_and_keeps_rush_and_cleave() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED }));
                let token = summon_rush_token(
                    &mut s,
                    json!({ "radiant": true, "statsOverride": { "attack": 5, "health": 5 } }),
                );

                assert!(token.radiant);
                s.expect_stats(&token, json!({ "attack": 5, "health": 5, "maxHealth": 5 }));
                assert!(unit_has(s.state(), &token, KeywordKind::Rush));
                assert!(unit_has(s.state(), &token, KeywordKind::Cleave));
            }

            #[test]
            fn r11_a_radiant_rush_token_that_dies_in_combat_ceases_to_exist_just_as_the_base_face_does() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": "core-t-rush", "radiant": true }] },
                    "p2": { "field": ["core-025"] },
                }));
                let token = s.unit(P1, 1).expect("a radiant Rush Token in p1's lane 1");

                let defender = s.unit(P2, 1).expect("p2's unit in lane 1");
                s.attack(&token, &defender);

                s.expect_in_zone(&token, "gone");
                assert!(s.pile(P1, "graveyard").is_empty());
                assert!(s.pile(P1, "exile").is_empty());
            }

            #[test]
            fn r11_and_s10_1_a_vanished_radiant_rush_token_is_in_no_pile_and_its_zone_says_gone() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": [{ "def": "core-t-rush", "radiant": true }] } }));
                let mut token = s.unit(P1, 1).expect("a radiant Rush Token in p1's lane 1");

                assert_eq!(
                    move_to_zone(s.state_mut(), &mut token, OffFieldZone::Exile, Default::default()),
                    MoveResult::Vanished
                );
                s.expect_in_zone(&token, "gone");
                assert!(s.pile(P1, "exile").is_empty());
                assert_eq!(token.zone.z(), ZoneName::Gone);
            }
        }
    }
}
