//! T-sheep Sheep Token (SPEC §7): cost 1, Unit/Token, 1/1, "worth 2 Tributes"; radiant 2/2, "worth
//! 3 Tributes". Generated by #41 Sheepish, its only generator.
//!
//! The script is one static flag. The 1/1 is printed on the catalog face (§10.4 layer 1, `faceOf`),
//! the Token tag keeps it out of every random pool (§5.1, `asksForTokens`), and R11's vanishing is
//! `isUnitToken`/`moveToZone` in engine/src/zones.ts — see `src/scripts/t-rush.ts` for that list.
//!
//! "WORTH 2 TRIBUTES" (§3.2, §6.3, §7).
//!   §3.2: "Sheep Tokens are worth 2 Tributes while on the field", and §7's radiant face is worth 3.
//!   §6.3 Tribute X: "the Sheep Token counts as 2 toward that X while it is on the field (§3.2) …
//!   A tribute written into a card's script is an ordinary Sacrifice of the permanent that script
//!   names, where the Sheep Token's 2 never applies."
//! The worth is the face's text, so it is this file's static flag, `tributeWorth`, and the play
//! validator reads it through `tributeValueOf` (engine/src/playChoices.ts): the Tribute X cost of
//! #55 Lava Golem and #66 The Rock, which `legalTributeSets`/`refuseTributes` build and check with it.
//! A script tribute (#22 Carnivorous Cube's Cry) is a plain `sacrifice` and never reads it (R41). As a
//! flag of the face, it goes with the face: a Vanilla Sheep has no text and is worth 1 (R115), the
//! radiant face's 3 is read off a Radiant Sheep, and a Sheep #85 fused a unit onto keeps its worth,
//! since a fused card's flags take the larger of its ingredients' (R102). The numbers are the
//! engine's named constants (CLAUDE.md rule 9). `test/t-sheep.test.ts` asserts the worth through the
//! engine's own `tributeValueOf`.
//!
//! Radiant form: §7 prints "2/2, worth 3 Tributes", so the radiant Script carries the 3.

use jackioh_engine::prelude::*;

pub const ID: &str = "core-t-sheep";

pub fn script() -> CardScripts {
    // §3.2: "worth 2 Tributes while on the field".
    let base = Script {
        static_flags: Some(StaticFlags {
            tribute_worth: Some(SHEEP_TRIBUTE_VALUE),
            ..StaticFlags::default()
        }),
        ..Script::default()
    };

    // §7's radiant face: "2/2, worth 3 Tributes".
    let radiant = Script {
        static_flags: Some(StaticFlags {
            tribute_worth: Some(RADIANT_SHEEP_TRIBUTE_VALUE),
            ..StaticFlags::default()
        }),
        ..Script::default()
    };

    CardScripts { base, radiant }
}

// T-sheep Sheep Token (SPEC §7; §3.2, §6.3, R11, R41, R74). BUILD M4-T4's token row: "Vanish on
// leaving the field; Sheep counts 2 toward Tribute; … none in random pools".
//
// §7 gives this token a radiant face, 2/2 and worth 3 Tributes, so the `describe`s below prove the
// base and the radiant behaviour, and the data block proves each face's numbers.
//
// The "worth 2 Tributes" rule is the face's static flag, which the play validator reads (see
// `src/scripts/t-sheep.ts`), so it is asserted through the engine's own
// `tributeValueOf`/`legalTributeUnits` (playChoices.ts).
// §6.3's second half — "a tribute written into a card's script is an ordinary Sacrifice … where the
// Sheep Token's 2 never applies" — is proved end to end with #22 Carnivorous Cube, the one shipped
// card that tributes from its own text (R41).
#[cfg(test)]
mod tests {
    use super::*;
    use jackioh_engine::testkit::*;

    const P1: PlayerId = PlayerId::P1;
    const P2: PlayerId = PlayerId::P2;

    const SEED: &str = "t-sheep";

    /// TS `expect(face).toEqual({ staticFlags: { tributeWorth: n } })`: the Script holds that one flag
    /// and nothing else — no hook, no declaration, no other flag.
    fn is_only_tribute_worth(script: &Script, worth: i32) -> bool {
        script.static_flags
            == Some(StaticFlags {
                tribute_worth: Some(worth),
                ..StaticFlags::default()
            })
            && script.cost.is_none()
            && script.cry.is_none()
            && script.death.is_none()
            && script.start_of_game.is_none()
            && script.resume.is_empty()
            && script.delayed.is_none()
            && script.set_stat.is_none()
            && script.start_of_turn.is_none()
            && script.end_of_turn.is_none()
            && script.aura.is_none()
            && script.triggers.is_empty()
            && script.on_play_hook.is_none()
            && script.hand_triggers.is_empty()
            && script.targets.is_empty()
            && script.modes.is_empty()
            && script.condition_met.is_none()
            && script.preview.is_none()
            && script.activations.is_empty()
            && script.target_checks.is_empty()
            && script.cost_aura.is_none()
            && script.graveyard_play.is_none()
            && script.targeting_discards.is_none()
            && script.records_play_as.is_none()
            && script.draw_limit.is_none()
            && script.replacements.is_empty()
            && script.hero_guard.is_none()
            && script.conditional_keywords.is_none()
            && script.after_attack.is_none()
            && script.plague_multiplier.is_none()
            && script.deck_triggers.is_empty()
            && script.graveyard_triggers.is_empty()
            && script.quests.is_none()
            && script.tribute_when.is_none()
            && script.would_counter.is_none()
            && script.start_of_opponent_turn.is_none()
    }

    /// The ids of a catalog query's answer (TS `ids(query(…))`).
    fn query_ids(args: Value) -> Vec<String> {
        jackioh_engine::catalog::query(&json_as(args))
            .iter()
            .map(|entry| entry.id.clone())
            .collect()
    }

    mod t_sheep_sheep_token_spec_s7 {
        use super::*;

        mod card_data_s7 {
            use super::*;

            #[test]
            fn s7_prints_a_1_cost_unit_token_with_1_1_no_keywords_and_the_worth_2_reminder() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.index, "T-sheep");
                assert_eq!(def.cost, CardCost::Fixed(1));
                assert_eq!(def.type_, CardType::Unit);
                assert!(def.token);
                assert!(def.tags.contains(&Tag::Token));
                assert_eq!(def.base.attack, Some(1));
                assert_eq!(def.base.health, Some(1));
                assert!(def.base.keywords.is_empty());
                assert!(fill_params(&def, FaceKind::Base, None).contains("2 Tributes"));
            }

            #[test]
            fn s7_gives_the_sheep_token_a_radiant_face_2_2_worth_3_tributes_build_m4_t1() {
                crate::register_all();
                let def = crate::card_def(ID);
                assert_eq!(def.radiant.attack, Some(2));
                assert_eq!(def.radiant.health, Some(2));
                assert_eq!(def.base.attack, Some(1), "and the base face is untouched at 1/1");
            }

            #[test]
            fn s7_each_face_s_script_is_its_worth_toward_a_tribute_and_nothing_else_s3_2_r102() {
                crate::register_all();
                let scripts = script();
                assert!(is_only_tribute_worth(&scripts.base, SHEEP_TRIBUTE_VALUE));
                assert!(is_only_tribute_worth(&scripts.radiant, RADIANT_SHEEP_TRIBUTE_VALUE));
            }
        }

        mod base {
            use super::*;

            #[test]
            fn s7_a_sheep_token_on_the_field_is_a_1_1_with_no_keywords() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": ["core-t-sheep"] } }));
                let sheep = s.unit(P1, 1).expect("a Sheep Token in p1's lane 1");

                assert_eq!(sheep.def_id, ID);
                s.expect_stats(&sheep, json!({ "attack": 1, "health": 1, "maxHealth": 1 }));
                assert!(keywords_of(s.state(), &sheep).is_empty());
            }

            #[test]
            fn s3_2_and_s6_3_a_sheep_token_on_the_field_is_worth_2_tributes_every_other_unit_1() {
                crate::register_all();
                let s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": ["core-t-sheep", "core-t-felinor", "core-025"] },
                }));

                let lane = |n: i32| s.unit(P1, n).expect("a unit in that lane");
                assert_eq!(tribute_value_of(s.state(), &lane(1)), 2);
                assert_eq!(tribute_value_of(s.state(), &lane(2)), 1);
                assert_eq!(tribute_value_of(s.state(), &lane(3)), 1);
            }

            #[test]
            fn r386_an_upgrade_makes_it_worth_3_tributes_and_a_degrade_1() {
                for (upgrade, worth) in [(true, 3), (false, 1)] {
                    crate::register_all();
                    let mut s = scenario(json!({ "seed": SEED, "p1": { "field": ["core-t-sheep"] } }));
                    let sheep = s.unit(P1, 1).expect("the Sheep Token").id;
                    let moved = if upgrade {
                        crate::upgrade_number(&mut s, &sheep, "worth")
                    } else {
                        crate::degrade_number(&mut s, &sheep, "worth")
                    };
                    assert_eq!(moved, worth);
                    assert_eq!(tribute_value_of(s.state(), s.card(sheep.as_str())), worth);
                }
            }

            #[test]
            fn s3_2_while_on_the_field_a_sheep_token_card_in_hand_is_no_tribute_candidate_at_all() {
                crate::register_all();
                let s = scenario(json!({
                    "seed": SEED,
                    "p1": { "hand": ["core-022", "core-t-sheep"], "field": ["core-t-sheep"] },
                }));
                let cube = s.hand(P1).into_iter().next().expect("the Cube in hand");
                let on_field = s.unit(P1, 1).expect("a Sheep Token in p1's lane 1");

                let candidates: Vec<String> = legal_tribute_units(s.state(), P1, &cube)
                    .iter()
                    .map(|unit| unit.id.clone())
                    .collect();
                assert_eq!(candidates, vec![on_field.id.clone()]);
            }

            #[test]
            fn s6_3_one_sheep_token_alone_pays_n66_the_rock_s_tribute_1() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "hand": ["core-066"], "field": ["core-t-sheep"] } }));
                let sheep = s.unit(P1, 1).expect("a Sheep Token in p1's lane 1");

                s.play("core-066", json!({ "tributes": [sheep.id] }));

                s.expect_in_zone("core-066", "field");
                // R11: the paid Sheep ceases to exist rather than reaching the graveyard.
                s.expect_in_zone(&sheep, "gone");
                assert!(s.pile(P1, "graveyard").is_empty());
            }

            #[test]
            fn s6_3_two_sheep_tokens_pay_n55_lava_golem_s_tribute_3_where_one_ordinary_unit_more_would_not() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "hand": ["core-055"], "field": ["core-t-sheep", "core-t-sheep"] },
                }));
                let sheep = vec![
                    s.unit(P1, 1).expect("a Sheep Token in p1's lane 1"),
                    s.unit(P1, 2).expect("a Sheep Token in p1's lane 2"),
                ];
                let sheep_ids: Vec<String> = sheep.iter().map(|unit| unit.id.clone()).collect();

                s.play("core-055", json!({ "tributes": sheep_ids }));

                s.expect_in_zone("core-055", "field");
                for unit in &sheep {
                    s.expect_in_zone(unit, "gone");
                }

                // Two ordinary units are worth 2, short of the 3 the two Sheep paid.
                let mut ordinary = scenario(json!({
                    "seed": SEED,
                    "p1": { "hand": ["core-055"], "field": ["core-025", "core-025"] },
                }));
                let pair: Vec<String> = [1, 2]
                    .iter()
                    .map(|lane| ordinary.unit(P1, *lane).expect("an ordinary unit").id)
                    .collect();
                ordinary.expect_refused_with(|o| o.play("core-055", json!({ "tributes": pair })), "Tribute 3");
                ordinary.expect_in_zone("core-055", "hand");
            }

            #[test]
            fn s6_3_and_r41_a_script_tribute_n22_sacrifices_only_the_permanent_it_names_the_2_never_applies() {
                crate::register_all();
                let mut s = scenario(json!({
                    "seed": SEED,
                    "p1": { "hand": ["core-022"], "field": ["core-t-sheep", "core-025"] },
                }));
                let sheep = s.unit(P1, 1).expect("a Sheep Token in p1's lane 1");
                let other = s.unit(P1, 2).expect("p1's other unit in lane 2");

                // R81: the meal travels in the play action. #22's Cry is a plain `sacrifice` of that one
                // permanent, so being worth 2 Tributes buys the Sheep nothing here.
                s.play("core-022", json!({ "targets": [{ "pick": "instance", "instanceId": sheep.id }] }));

                s.expect_events(json!(["cardPlayed", "destroyed"]));
                // R11: sacrificed from the field, so it ceases to exist instead of reaching the graveyard.
                s.expect_in_zone(&sheep, "gone");
                assert!(s.pile(P1, "graveyard").is_empty());
                // Exactly one permanent was eaten: the other unit and the Cube itself are untouched.
                s.expect_in_zone(&other, "field");
                s.expect_in_zone("core-022", "field");
                // §6.3: the Cube's meal is not a Tribute *cost* — its declaration carries no `amount`, so the
                // play charged no Tribute and the Sheep's 2 never entered the arithmetic at all.
                assert_eq!(tribute_cost_of(s.state(), s.card("core-022")), 0);
            }

            #[test]
            fn r11_a_sheep_token_that_dies_in_combat_ceases_to_exist_and_never_reaches_a_graveyard() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": ["core-t-sheep"] }, "p2": { "field": ["core-025"] } }));
                let sheep = s.unit(P1, 1).expect("a Sheep Token in p1's lane 1");
                assert!(is_unit_token(s.state(), &sheep));

                let defender = s.unit(P2, 1).expect("p2's unit in lane 1");
                s.attack(&sheep, &defender);

                s.expect_events(json!(["destroyed"]));
                s.expect_in_zone(&sheep, "gone");
                // R11: "nothing can reach it again" — the engine's own lookup no longer finds it. (The
                // instance this test holds is a pre-`reduce` snapshot, so its own `zone` is stale; the
                // `gone` tag is asserted below, where `moveToZone` mutates the live instance in place.)
                assert!(find_instance(s.state(), &sheep.id).is_none());
                assert!(s.pile(P1, "graveyard").is_empty());
                assert!(s.pile(P1, "exile").is_empty());
            }

            #[test]
            fn r11_a_bounced_sheep_token_ceases_to_exist_rather_than_returning_to_a_hand_s3_2() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": ["core-t-sheep"] } }));
                let mut sheep = s.unit(P1, 1).expect("a Sheep Token in p1's lane 1");

                // Called directly so this test holds the instance the engine mutates (`reduce` clones).
                assert_eq!(
                    move_to_zone(s.state_mut(), &mut sheep, OffFieldZone::Hand, Default::default()),
                    MoveResult::Vanished
                );

                s.expect_in_zone(&sheep, "gone");
                assert_eq!(sheep.zone.z(), ZoneName::Gone);
                assert!(s.hand(P1).is_empty());
            }

            #[test]
            fn r11_a_unit_token_never_enters_a_graveyard_or_exile_so_a_fixture_may_not_put_one_there() {
                crate::register_all();
                expect_throw_with(
                    || {
                        scenario(json!({ "seed": SEED, "p1": { "graveyard": ["core-t-sheep"] } }));
                    },
                    "unit token",
                );
                expect_throw_with(
                    || {
                        scenario(json!({ "seed": SEED, "p1": { "exile": ["core-t-sheep"] } }));
                    },
                    "unit token",
                );
            }

            #[test]
            fn s5_1_and_s7_query_never_offers_the_sheep_token_unless_the_pool_names_tokens() {
                crate::register_all();
                let id = ID.to_string();

                assert!(!query_ids(json!({ "type": "Unit" })).contains(&id));
                assert!(!query_ids(json!({ "cost": 1 })).contains(&id));
                assert!(query_ids(json!({ "token": true })).contains(&id));
                assert_eq!(query_ids(json!({ "defId": "core-t-sheep" })), vec![id]);
            }
        }

        // §7's radiant face: R74 sets the flag, and the flag selects the 2/2 face and its Script, whose
        // worth is 3.
        mod radiant_s7_2_2_worth_3_tributes {
            use super::*;

            #[test]
            fn r74_a_radiant_sheep_token_is_a_2_2_with_no_keywords() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": [{ "def": "core-t-sheep", "radiant": true }] } }));
                let sheep = s.unit(P1, 1).expect("a radiant Sheep Token in p1's lane 1");

                assert!(sheep.radiant);
                s.expect_stats(&sheep, json!({ "attack": 2, "health": 2, "maxHealth": 2 }));
                assert!(keywords_of(s.state(), &sheep).is_empty());
            }

            #[test]
            fn s3_2_s7_a_radiant_sheep_token_is_worth_3_tributes_where_the_base_one_is_worth_2() {
                crate::register_all();
                let s = scenario(json!({
                    "seed": SEED,
                    "p1": { "field": [{ "def": "core-t-sheep", "radiant": true }, { "def": "core-t-felinor", "radiant": true }] },
                }));

                // The Radiant face is worth 3; the base one, added below, is still worth 2.
                let first = s.unit(P1, 1).expect("a radiant Sheep Token in p1's lane 1");
                let second = s.unit(P1, 2).expect("a radiant Felinor Token in p1's lane 2");
                assert_eq!(tribute_value_of(s.state(), &first), 3);
                assert_eq!(tribute_value_of(s.state(), &second), 1);

                let base = scenario(json!({ "seed": SEED, "p1": { "field": [{ "def": "core-t-sheep" }] } }));
                let plain = base.unit(P1, 1).expect("a Sheep Token in p1's lane 1");
                assert_eq!(tribute_value_of(base.state(), &plain), 2);
            }

            #[test]
            fn r11_a_radiant_sheep_token_that_leaves_the_field_ceases_to_exist_just_as_the_base_face_does() {
                crate::register_all();
                let mut s = scenario(json!({ "seed": SEED, "p1": { "field": [{ "def": "core-t-sheep", "radiant": true }] } }));
                let mut sheep = s.unit(P1, 1).expect("a radiant Sheep Token in p1's lane 1");

                assert_eq!(
                    move_to_zone(s.state_mut(), &mut sheep, OffFieldZone::Graveyard, Default::default()),
                    MoveResult::Vanished
                );

                s.expect_in_zone(&sheep, "gone");
                assert_eq!(sheep.zone.z(), ZoneName::Gone);
                assert!(s.pile(P1, "graveyard").is_empty());
            }
        }
    }
}
